= Vision Object Field Reference

The _Vision Object_ record type is used to specify an object, from which
a mobile user launches CT Vision.

Create a separate _Vision Object_ record for each object, which is
supposed to take and view photos.

'''''

Record Type API Name: [.apiobject]#VisionObject#

'''''

The following fields must be created on the [.object]#Vision Settings# object for this record type:

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Vision Object |[.apiobject]#ctv\__VisionObject__c# |Text(255) a| NOTE: Required field.

Specify the API name of the object on the layout of which you want to add the *CT Vision* button.
|Vision Object Record Type |[.apiobject]#ctv\__VisionObjectRecordType__c# |Text(255) a| If there is at least one record type for the [.object]#Vision# object, specify its API name to apply the setting for the corresponding record type. Leave empty, if there are no record types for the [.object]#Vision# object.

|Vision Photo Lookup |[.apiobject]#ctv\__VisionPhotoLookup__c# |Text(255) a| NOTE: Required field.

Specify the API name of the [.apiobject]#\{VisionObjectid}# field on
the xref:../vision-photo-field-reference-ir-2-9.adoc[Vision Photo] object.

|Parent Object |[.apiobject]#ctv\__ParentObject__c# |Text(255) a| NOTE: Applies only to CT Vision Mobile.

Specify the API name of the object used for aggregating photos from related records (for example, photos from _Activities_ with specified _Accounts_

|Parent Object Lookup |[.apiobject]#ctv\__ParentObjectLookup__c# |Text(255) a|
NOTE: Applies only to CT Vision Mobile.

Specify the API name of the lookup field from the [.object]#Vision# object to its parent object. For example: [.apiobject]#CTCPG\__AccountId__c#

|Enable Gallery |[.apiobject]#ctv\__IsGalleryEnabled__c# |Checkbox a|
NOTE: Applies only to CT Vision Mobile.

If active, a mobile user can add photos from the device gallery by long
tapping the camera icon.

|Enable Simple View |[.apiobject]#ctv\__IsSimpleViewEnabled__c# |Checkbox a| NOTE: Applies only to CT Vision Mobile.

If active, the information from the header of the xref:CT-Vision-IR-for-CT-Mobile-2.9/CT-Vision-IR-Administrator-Guide/working-with-ct-vision-ir-in-the-ct-mobile-app-2-9.adoc#h2_1831185552[Report Summary] screen (actual and planned number of photos, the number of errors, and the actual number of the required report summaries) and the final summary report will not be displayed.

|Plan |[.apiobject]#ctv\__Plan__c# |Number(18,0) a| NOTE: Applies only to CT Vision Mobile.

Planned number of photos to take during the visit. If not specified, then the planned number of photos is got from the *Plan* field of the link:vision-shelf-field-reference-ir-2-9[Vision Shelf] object.

|Interface Fields |[.apiobject]#ctv\__InterfaceFields__с# |Long Text Area(32768) a| NOTE: Applies only to CT Vision Salesforce.

Specify API names of the fields from the Vision object that should be displayed under the photos in the xref:CT-Vision-IR-for-CT-Mobile-2.9/CT-Vision-IR-Administrator-Guide/working-with-ct-vision-ir-in-salesforce-2-9.adoc#h2_1552458132[Picture Gallery] (maximum 3 fields). The *Name* field is always displayed, even if not specified.

|Filter Fields |[.apiobject]#ctv\__FilterFields__c# |Long Text Area(32768) a| NOTE: Applies only to CT Vision Salesforce.

Specify API names of the fields (in one string, comma separated) from the [.object]#Vision# object that should be displayed as filters in the separate section of the xref:CT-Vision-IR-for-CT-Mobile-2.9/CT-Vision-IR-Administrator-Guide/working-with-ct-vision-ir-in-salesforce-2-9.adoc#h2_1552458132[Picture Gallery]. The following field types cannot be used for filtering:

* Text area
* Time
* Geolocation

|Provider |[.apiobject]#ctv\__Provider__c# |Text(255) a|
Available values:

* _cg_cloud_
* _vision_
* _vision_light_
* _vertex_
* _easypicky_
* _einstein_
* _planorama_
* _intelligence_retail_

|===
