= Sales Organization Management

the [.object]#Sales Organization# object represents the customer
company.



You can specify sales organization records per country and bricks,
customer departments, or according to other criteria.

* If you use customer ERP {plus} Salesforce CRM, you can inherit the
client segmentation from ERP for Sales Organization.
* If you use only Salesforce CRM, the segmentation can be inherited from
the CT CPG or CT Pharma package.



Read the Sales Organization description and configuration:

:toc: :toclevels: 3



To configure the xref:sales-organization-field-reference[Sales
Organization] record:

. Check the target system segmentation options to specify Sales
Organization for unique territories and specific distributors.
A representative should have access to the target system objects, such
as CT Product, CT Product Component, an[.object]#Activity#
object, etc.
[NOTE] ==== It is necessary to check the representative and
manager permissions to target system objects. Also, if additional custom
objects will be created, for example, an[.object]#Address ====
object, permission for representatives and managers should be
specified.#
. ​Configure xref:admin-guide/getting-started/setting-up-an-instance/configuring-object-setting[the main CT Orders
settings], such as the object setting, layout settings, etc.
A representative should have at least permission to read records and all
fields of the xref:admin-guide/managing-ct-orders/sales-organization-management/settings-and-sales-organization-data-model/settings-fields-reference/index.adoc[Settings] object.
Users with the manager role can also have permission to edit records.
. Optionally, customize the *Sales Organization* Lightning page in the
https://help.salesforce.com/articleView?id=lightning_app_builder_overview.htm&type=5[Lightning
App Builder].
The Lightning page should be available for representatives and managers.
. xref:admin-guide/workshops/workshop1-0-creating-basic-order/creating-a-sales-organization-1-0.adoc[Create a Sales
Organization].
A representative should have permission to read records and all fields
of the *Sales Organization* records. Users with the manager role can
also have permission to edit records.
Available options:
* create a Sales Organization for Salesforce CRM;
* relate a Sales Organization with a record in the customer ERP system.
. xref:admin-guide/workshops/workshop1-0-creating-basic-order/creating-a-sales-organization-user-1-0.adoc[Assign users for
Sales Organizations].
xref:sales-organization-user-field-reference[Users] should have the
same permissions as listed in the steps above.
. xref:catalogs-field-reference[Assign at least one Catalog for a
Sales Organization].
[NOTE] ==== The *Catalog* record should include *CT Product*
records, be assigned to at least one *Account* record that relates to
selected *CT Products*, and be active as well as *Catalog Line Items*
records should be active too. ==== The representative should have
permission to read records of the *Catalog* and *Catalog Line Item*, *CT
Price Book*, and *CT Price Book Line Item*, as well as access to the
Lightning pages for these objects.
. Assign at least one *Price Book* for a *Sales Organization*.
. Optionally, specify xref:promotion-field-reference[Promotions]
and xref:pricing-procedure-fields-reference[pricing procedures].

The Sales Org is configured. The sales rep can
xref:order-management[create an order].



 See also:

* xref:sales-organization-tab[Sales Organization Tab]
* xref:how-to-create-a-sales-organization[How to Create a Sales
Organization]
* xref:how-to-create-a-sales-organization-user[How to Create a
Sales Organization User]
* xref:how-to-create-an-account[How to Create an Account]
* xref:how-to-define-an-order-type[How to Define an Order Type]
* xref:how-to-configure-totals-panel-setting[How to Configure
Totals Panel Setting]
* xref:settings-and-sales-organization-data-model[Settings and
Sales Organization Data Model]
* xref:workshop1-0-creating-basic-order[Workshop 1.0: Creating
Basic Order]
