= Sales Organization Management

The [.object]#Sales Organization# object represents the customer company.

You can specify sales organization records per country and bricks, customer departments, or according to other criteria.

* If you use customer ERP {plus} Salesforce CRM, you can inherit the client segmentation from ERP for Sales Organization.
* If you use only Salesforce CRM, the segmentation can be inherited from the CT CPG or CT Pharma package.

Read the Sales Organization description and configuration:

To configure the xref:./settings-and-sales-organization-data-model/sales-organization-field-reference.adoc[Sales Organization] record:

. Check the target system segmentation options to specify Sales Organization for unique territories and specific distributors.
+
A representative should have access to the target system objects, such as CT Product, CT Product Component, an [.object]#Activity# object, etc.
+
NOTE: It is necessary to check the representative and manager permissions to target system objects. Also, if additional custom objects will be created, for example, an [.object]#Address# object, permission for representatives and managers should be specified.
. Configure xref:admin-guide/getting-started/setting-up-an-instance/configuring-object-setting.adoc[the main CT Orders settings], such as the object setting, layout settings, etc.
+
A representative should have at least permission to read records and all fields of the xref:admin-guide/managing-ct-orders/sales-organization-management/settings-and-sales-organization-data-model/settings-fields-reference/index.adoc[Settings] object. Users with the manager role can also have permission to edit records.
. Optionally, customize the *Sales Organization* Lightning page in the link:https://help.salesforce.com/articleView?id=lightning_app_builder_overview.htm&type=5[Lightning
App Builder].
+
The Lightning page should be available for representatives and managers.
. xref:./howtos/how-to-create-a-sales-organization.adoc[Create a Sales Organization].
+
A representative should have permission to read records and all fields of the _Sales Organization_ records. Users with the manager role can also have permission to edit records.
+
Available options:

* create a Sales Organization for Salesforce CRM;
* relate a Sales Organization with a record in the customer ERP system.
. xref:./howtos/how-to-create-a-sales-organization-user.adoc[Assign users for Sales Organizations].
xref:./settings-and-sales-organization-data-model/sales-organization-user-field-reference.adoc[Users] should have the same permissions as listed in the steps above.
. xref:admin-guide/managing-ct-orders/catalog-management/catalog-data-model/catalogs-field-reference.adoc[Assign at least one Catalog for a Sales Organization].
+
NOTE: The _Catalog_ record should include _CT Product_ records, be assigned to at least one _Account_ record that relates to selected _CT Products_, and be active as well as _Catalog Line Items_ records should be active too.
+
The representative should have permission to read records of the [.object]#Catalog# and [.object]#Catalog Line Item#, [.object]#CT Price Book#, and [.object]#CT Price Book Line Item#, as well as access to the Lightning pages for these objects.
. Assign at least one [.object]#Price Book# for a [.object]#Sales Organization#.
. Optionally, specify xref:admin-guide/managing-ct-orders/discount-management/promotion-data-model/promotion-field-reference.adoc[Promotions] and xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-fields-reference.adoc[pricing procedures].

The Sales Org is configured. The sales rep can xref:admin-guide/managing-ct-orders/order-management/index.adoc[create an order].

See also:

* xref:./sales-organization-tab.adoc[]
* xref:./howtos/how-to-create-a-sales-organization.adoc[]
* xref:./howtos/how-to-create-a-sales-organization-user.adoc[]
* xref:./howtos/how-to-create-an-account/index.adoc[]
* xref:./howtos/how-to-define-an-order-type.adoc[]
* xref:./howtos/how-to-configure-totals-panel-setting.adoc[]
* xref:./settings-and-sales-organization-data-model/index.adoc[]
* xref:admin-guide/workshops/workshop-1-0-creating-basic-order/index.adoc[]
