= 6. Configuring Application Settings

After xref:installing-ct-pharma-package[the CT Pharma package
installation], xref:remote-site-settings[creating the additional
remote site], and xref:managing-ct-pharma-licenses[assigning the CT
Pharma licenses], xref:admin-guide/getting-started/user-permission-settings.adoc[profiles&#44; and
permission sets to users], manage the *Global* record
of xref:admin-guide/application-settings-management/index.adoc[Application Settings] or
create a new one if you want to specify more than one marketing cycle.



To manage the *Global* record of *Application Settings* or create a new
one, you can customize sets of data
in the xref:admin-guide/ct-pharma-control-panel/index.adoc[CT Pharma Control Panel] or
follow these steps:

. Go to *Setup→ Custom Code → Custom Settings →* click *Manage* next
to *Application Settings*.
. Click *Edit* next to the *Global* record, or click *New* to create a
new record.
. Specify the required parameters.
* Read the description of each
parameter xref:application-settings[here].
* It is necessary to update records of *Application Settings* in case of
using xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/add-and-set-up-divisions.adoc[new divisions].
. ​Click *Save*.

The setup is complete.
