= Limit Rule Field Reference

The [.object]#Limit Rule# object is intended to store the minimum and maximum product quantity for an order and each delivery.

NOTE: All appropriate limit rules are applied to a single order.

'''''

Object API name: [.apiobject]#orders\__LimitRule__c#

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Amount Field |[.apiobject]#orders\__AmountField__c#
|Text(255) |The API name of the field from the [.object]#Delivery Line Item# object that stores the final price for the [.object]#Order#, for example, [.apiobject]#orders\__TotalPrice__c#.

|Apply Condition
|[.apiobject]#orders\__ApplyCondition__c# |Long Text Area(32768) a|
The condition, under which the limit rule is applied to [.object]#Delivery Line Item# records in the [.object]#Order#.

* The user must have at least permission to read all fields in the condition.
* To see the example, refer to xref:admin-guide/managing-ct-orders/product-validation-in-order/limit-rules/limit-rule-field-reference/limit-rule-applycondition-c-field-specification.adoc[Limit Rule: ApplyCondition__c Field Specification].
* This field is ignored if the *Global Exception* = _true_.

|Custom Validation Message
|[.apiobject]#orders\__CustomValidationMessage__c#
|Text(255) a|
Contains API name of link:https://help.salesforce.com/s/articleView?id=sf.cl_about.htm&type=5[custom label], which is displayed as the validation message when the Limit Rule is applied to the order or delivery.

If the field is empty, the standard validation message will be displayed.

|Delivery Criteria Path
|[.apiobject]#orders\__DeliveryCriteriaPath__c#
|Text(255) a|
This field is responsible for the delivery grouping to apply limit rules to that group. Specify the criteria that will distribute deliveries into separate groups as a path to the required fields, for example, [.apiobject]#Warehouse\__c,orders__DeliveryDate\__c,Address__c#.

* The user must have at least permission to read all fields in the condition.
* Fields must be on the [.object]#Delivery# object or related objects.
* Not applied for the Limit Rule with the _Order_ record type.

|Exceptions Condition |[.apiobject]#orders_ExceptionsCondition__c# |Long Text Area(32768) a|
The condition under which the limit rule is not applied to _Delivery Line Item_ records in the [.object]#Order#.

* The user must have at least permission to read all fields in the condition.
* To see the example, refer to xref:admin-guide/managing-ct-orders/product-validation-in-order/limit-rules/limit-rule-field-reference/limit-rule-exceptioncondition-c-field-specification.adoc[Limit Rule: ExceptionCondition__с Field Specification].

|Global Exception |[.apiobject]#orders_GlobalException__c# |Checkbox a|
* If enabled, triggers searching *Exceptions Condition* field in the whole order, disregarding the value of the *Apply Condition* field. If the *Exceptions Condition* is met in any delivery, the Limit Rule will not apply.
* If disabled (by default), the standard logic of the Limit Rule with the *Record type* = _Delivery_ takes place.
* Applies only to Limit Rules with the *Record type* = _Delivery_.

|Maximum Amount |[.apiobject]#orders_MaxAmount__c#
|Currency(16,2) a| The maximum amount of all products for a single delivery or order.

The actual amount is set in the field specified in the [.apiobject]#orders\__AmountField__c# field.

|Maximum Quantity |[.apiobject]#orders_MaxQuantity__c# |Number(18, 0) a|
The maximum quantity of all products for a single delivery or order.

The actual quantity is set in the field specified in the [.apiobject]#orders\__Quantity__c# field of the [.object]#Delivery Line Item# object.

|Minimum Amount |[.apiobject]#orders_MinAmount__c#
|Currency(16,2) a| The minimum amount of all products for a single delivery or order.

The actual amount is set in the field specified in the [.apiobject]#orders\__AmountField__c# field.

|Minimum Quantity |[.apiobject]#orders_MinQuantity__c# |Number(18,0) a|
The minimum quantity of all products for a single delivery or order.

The actual quantity is set in the field specified in the [.apiobject]#orders\__Quantity__c# field of the [.object]#Delivery Line Item# object.

|Order Type |[.apiobject]#orders_OrderType__c# |Multipicklist a|
Select one or more xref:admin-guide/managing-ct-orders/order-management/ref-guide/ct-order-data-model/ct-order-field-reference.adoc[order types] to apply the limit rule.

* Order
* Return
* Pre-Sale

|Record Type |[.apiobject]#RecordTypeId# |Record Type a| It determines to which object the limit rule should be applied. The available objects:

* Order
** Validation is applied to overall products quantity or amount in the order.
Delivery grouping based on fields in the [.apiobject]#orders\__DeliveryCriteriaPath__c# field is not available for this record type.
* Delivery
** Validation is applied only to products of a certain delivery.
** Limit rules are applied after the split is done, i.e., the limit rule logic processes products quantity or amount per each delivery in the order.
To apply the limit rule to a delivery grouped by address and date, you need to use the delivery grouping based on fields in the [.apiobject]#orders\__DeliveryCriteriaPath__c# field.

|Sales Organization Id |[.apiobject]#orders_SalesOrganizationId__c#
|Lookup(Sales Organization) |If needed, specify the _Sales Organization_ record to apply the limit rule.
|===
