= Limit Rule: ApplyCondition__c Field Specification

If the condition from
xref:admin-guide/managing-ct-orders/product-validation-in-order/limit-rules/limit-rule-field-reference/limit-rule-exceptioncondition-c-field-specification[the
orders__ExceptionCondition__c field] is not met, the system
checks the [.apiobject]#orders__ApplyCondition__c#
field.

* If this field contains the condition, the limit rule will be applied
to certain products in the delivery, delivery group, or order according
to the parameters in the appropriate _Limit Rule_ records.
* Otherwise, the limit rule will be applied to all products in the
delivery, delivery group, or order according to the parameters in the
appropriate _Limit Rule_ records.

Example:



Use the [.apiobject]#$.deliveryOrder# operator to refer to
certain index of the delivery in the order (0, 1, 2 etc.) or _max_ as
the last delivery. You can use the following operators:

* less
* greater
* lessOrEqual
* greaterOrEqual
* equal
* notEqual

Example:




