= Limit Rule: ExceptionCondition__с Field Specification

The[.apiobject]#orders__ExceptionsCondition__c# field
contains the condition that this limit rule does not apply to the
specified order, delivery, or delivery group. If the condition is not
met, the system checks
the xref:admin-guide/managing-ct-orders/product-validation-in-order/limit-rules/limit-rule-field-reference/limit-rule-applycondition-c-field-specification[orders__ApplyCondition__c] field.



The JSON syntax:

*[.apiobject]#productCount# stores the condition to not apply
the limit rule.
**[.apiobject]#filter# defines the _Delivery Line Item_ records
for calculating a unique number of products. If the
[.apiobject]#value# is 0, the condition will not be applied.
**[.apiobject]#minCount# is a minimum quantity of unique
products that are found according to the[.apiobject]#filter#.
Starting this quantity, the limit rule will not be applied.

[TIP] ==== Use the [.apiobject]#AND ==== operator to
check [.apiobject]#minCount# for all listed products, or use the[.apiobject]#OR# operator if at least one product must meet
[.apiobject]#minCount#.#

*[.apiobject]#requiredProducts# specifies the mandatory
products from the founded according to the [.apiobject]#filter.#
*[.apiobject]#productIdField# is the product unique ID to
search the required product. If set,
the [.apiobject]#ExternalId__c# value is used for products
with [.apiobject]#minCount#. Otherwise, the product identifier
from the [.apiobject]#orders__ProductId__c# field is
used.
*[.apiobject]#productQuantityField# stores the field API name
from the[.object]#Order Line Item# object that stores the
product quantity.
*[.apiobject]#items# specifies list of products required to be
added to order cart.
**[.apiobject]#product# is the product identifier from the
[.apiobject]#orders_ProductId__c# or
[.apiobject]#ExternalId__c# (if specified) field.
**[.apiobject]#minQuantity# specifies the product minimum
quantity.
** $.deliveryOrder specifies certain index of the delivery in the order
(0, 1, 2 etc.) or _max_ as the last delivery. You can use the following
operators:
*** less
*** greater
*** lessOrEqual
*** greaterOrEqual
*** equal
*** notEqual

Example:








