= About CT Sign

Available only in Salesforce Lightning Experience interface.

CT Sign solution provides the ability to create documents, such as
contracts, emails, and any forms, and sign them by one or more users
with a handwritten signature or using the DocuSign electronic signature
(e-signature) as a legal way to get consent or approval. Flexible
customization allows sharing with users only the required documents and
libraries and facilitating document preparation by using pre-configured
templates with the dynamic populating of the customer data. It is
possible to work online in your Salesforce organization, or add the CT
Sign module to the CT Mobile app for offline document signing.



The managed CT Sign package is compatible with other CT family products
and Salesforce updates, such as API version changes, metadata types, and
updates for Lightning Experience users.



For your convenience, we prepared the CT Sign guides with the following
sections:

* In this section, you can find:
*
* the functional
link:ct-sign-description-and-deployment#h2_1478584389[description]
of the solution;
*
* an link:ct-sign-description-and-deployment[overview of the
components] of the CT Sign package;
*
* link:ct-sign-description-and-deployment#h2_463801188[required
third-party services];
*
* link:ct-sign-description-and-deployment#h2__426184834[deployment
steps];
*
* link:ct-sign-f-a-q[F.A.Q.]
* The link:news/index[News] section provides the latest CT Sign
release notes, Salesforce updates that affect our CT Sign solution.
* link:admin-guide/ct-sign-administrator-guide[Administrator Guide] is a set of
articles with detailed information on how to set up functionalities in
the managed CT Sign package.
* link:ref-guide/index[Reference Guide] describes CT Sign
components, such as custom objects and fields, custom settings, and
interfaces for customizations.
