= Activity Report Tab Settings

According to the activity type and your business purposes, customize
related tabs of the Activity Report:

* xref:company-product-tab-settings[*Company Product* tab]: track
your company products or assortments within a visit.
* xref:competitor-product-tab-settings[*Competitor Product*
tab]: track competitor products within a visit.
* xref:pos-material-tab-settings[*POS Material* tab]: track the
marketing materials distributed during a visit.
* xref:special-trackings-tab-settings[*Special Tracing* tab]: track
the tasks and objectives for the active marketing cycle within a visit.
* xref:event-member-tab-settings[*Event Member* tab]: add attendees
and allot roles to them within an event.
* xref:expenses-tab-settings[*Expenses* tab]: track spending
within an event.
* xref:inventory-tab-settings[*Inventory* tab]: track the rental
medical equipment.

[.aui-icon .aui-icon-small .aui-iconfont-approve .confluence-information-macro-icon]##

Also, you can customize these tabs for each Profile on
the *xref:ct-pharma-control-panel-activity-report[CT Pharma Control
Panel: Activity Report]* tab.
