= Vision Photo Tag Field Reference

The [.object]#Vision Photo Tag# object is intended for the connection between link:tag-field-reference-ir-2-9.html[Tag] and link:vision-photo-field-reference-ir-2-9.html[Vision Photo] objectshttps://help.customertimes.com/smart/project-ct-vision-lite-en/adding-photo-tags-2-9[]. ''''' Object API Name: [.apiobject]#ctv__VisionPhotoTag__c# ''''' The following fields must be created on the [.object]#Vision Photo Tag#object:

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|[.ui-provider .a .b .c .d .e .f .g .h .i .j .k .l .m .n .o .p .q .r .s .t .u .v .w .x .y .z .ab .ac .ae .af .ag .ah .ai .aj .ak]#Vision
Photo# |[.apiobject]#ctv__VisionPhoto#__c |[.ui-provider .a .b .c .d .e .f .g .h .i .j .k .l .m .n .o .p .q .r .s .t .u .v .w .x .y .z .ab .ac .ae .af .ag .ah .ai .aj .ak]#Master-Detail(Vision
Photo)# |Specify the
link:vision-photo-field-reference-ir-2-9.html[Vision Photo]  record.

|Tag |[.apiobject]#ctv__Tag__c# |[.ui-provider .a .b .c .d .e .f .g .h .i .j .k .l .m .n .o .p .q .r .s .t .u .v .w .x .y .z .ab .ac .ae .af .ag .ah .ai .aj .ak]#Master-Detail(Tag)#
|Specify the link:tag-field-reference-ir-2-9.html[Tag]  record.
|===
