= JS Libraries
:toc:

JS libraries are responsible for displaying CLM presentations. Also, you can use JS Bridge methods to manage CRM data, access an external functionality, or control interactions on slides. For more information, refer to xref:ios/ct-presenter/js-bridge-api/js-bridge-methods-availability.adoc[JS Bridge Methods Availability].

[[h3_1625537617]]
== Required JS Library

The system JS library must be specified in the [.apiobject]#<head># tag of each slide:

[source,html]
----
<!DOCTYPE html>
<html>
  <head>

    <script type="text/javascript" src="../JSLibrary/js/app.js">
    </script>

  </head>
  <body>

    <!-- content -->

  </body>
</html>
----

[[h3_844538281]]
== Additional JS Libraries for Using Widgets

In the case of using widgets supplied with the solution, add the following resources in the [.apiobject]#<head># tag of a slide:

[source,html]
----
<!DOCTYPE html>
<html>
  <head>

    <script type="text/javascript" src="../JSLibrary/js/app.js">
    </script> <!—the required JS library for each slide -->
    <script type="text/javascript" src="../JSLibrary/js/jquery-1.8.2.min.js">
    </script>
    <script type="text/javascript" src="../JSLibrary/js/jquery.jqChart.min.js">
    </script>
    <script type="text/javascript" src="../JSLibrary/js/jquery.jqRangeSlider.min.js">
    </script>
    <script type="text/javascript" src="../JSLibrary/js/jquery-ui-1.9.1.min.js">
    </script>
    <script type="text/javascript" src="../JSLibrary/js/jquery.ui.touch-punch.min.js">
    </script>
    <script type="text/javascript" src="../JSLibrary/js/app.js">
    </script>
    <link rel="stylesheet" type="text/css" href="../JSLibrary/css/jquery.jqChart.css"/>
    <link rel="stylesheet" type="text/css"  href="../JSLibrary/css/jquery.jqRangeSlider.css"/>
    <link rel="stylesheet" type="text/css" href="../JSLibrary/themes/redmond/jquery-ui.css"/>
    <link rel="stylesheet" type="text/css" href="../JSLibrary/css/jquery-ui-1.9.1.min.css"/>

  </head>
  <body>
    <!-- content -->
  </body>
</html>
----

For more information about available widgets, refer to xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-application-record-type/creating-a-widget.adoc[Creating a Widget].
