= Testing Interactive CLM Presentations

CT Presenter contains a set of CLM presentations to get you examples of
ZIP archives, slide markups, and interactions within CLM presentations.
For more information, refer to xref:test-clm-presentations[Test CLM
Presentations].

[[h3_1283836803]]
==== Slide Markup

Usually, a slide is a single HTML page with the following structure:



When each slide is a single HTML page, you can use CT Presenter tools to
collect statistics per slide. For more information about tracked
parameters, refer to xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-applicationstats.adoc[Application Stats].

[[h3_2014592999]]
==== 

[[h3_2014592999]]
==== Large Slides

If you do not need to track slide statistics, you can create a CLM
presentation as indivisible content. The peculiarity of such CLM
presentations is:

* CLM presentation will be uploaded as one slide
* HTML size on that slide may exceed the allowed limit—the number of
characters in a slide markup, which is _131,072_ characters.

To upload such a slide:

. Create a JS file with the HTML code of a slide, for example, with the
_addMarkup.js_ name in the following format:

. Add _addMarkup.js_ to _sources.zip_ and upload it to Salesforce.
. {blank}

Create a _slide-name.html_ with the following markup and upload it to
Salesforce:




Also, follow these recommendations for large slides:

* If the slide has several videos, and they are configured to play
immediately, configure them to play only when they appear in the visible
part of their slide, when the user can actually see them.
* Configure sectional loading for the slide: while opening the slide,
only one section is loading, which user is opening currently.
* To avoid freezing and crash of presentations with large slides, it is
highly recommended to use the slide loader to make sure that all the
content and scripts have been fully loaded and ready to use.

See also:

* xref:clm-presentation-components[CLM Presentation Components].


