= Transferring Settings from the Production Environment to Sandboxes

During the sandbox upgrade, all data is copied from the production
environment, including critical data for CT Mobile functionalities, such
as a cloud token and user profile IDs. If the profile IDs used do not
match the sandbox profile IDs, the sandbox does not have the necessary
settings, and there are no objects in the *Selected* column on the
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-offline-objects.adoc#h2_1468985423[CT
Mobile Control Panel: Offline
Objects]/xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-offline-objects-new.adoc[CT Mobile
Control Panel 2.0: Offline Objects] tab.



This article helps you to make it easier to migrate settings from the
production environment to sandboxes.

Important notes:

* xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/index.adoc[CTM Settings] records with the *Menu*, *Offline
Objects*, and *Standard Related List* record types store settings for
the menu, offline objects, and standard related lists.
* xref:ios/admin-guide/ct-mobile-control-panel/index.adoc[CT Mobile Control
Panel]/xref:ios/admin-guide/ct-mobile-control-panel-new/index.adoc[CT Mobile Control Panel
2.0] displays settings for the menu, offline objects, and standard
related lists given the *CTM Settings* records and others
given xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/index.adoc[custom settings].
* CT Mobile app downloads settings from CTM Settings records and custom
settings records.

[[h2_1090338631]]
=== 1. Verify Remote Site Settings

Go to *Setup → Security → Remote Site Settings* and verify that the
specified URL contains the instance name of the sandbox, not the
production environment.

For more information, refer to xref:ios/admin-guide/remote-site-settings.adoc[Remote
Site Settings].

[[h2_204191995]]
=== 2. Update Cloud Token

Go to *CT Mobile Control Panel: Tools* and click *Refresh* next to
*Cloud Token*.

For more information, refer
to xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-tools/index.adoc[CT Mobile Control Panel:
Tools]/xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-tools-new.adoc[CT Mobile Control
Panel 2.0:
Tools] and xref:ios/getting-started/installing-ct-mobile-package/ct-mobile-managed-package-update-to-v-3-54.adoc[CT
Mobile Managed Package Update to v. 3.54].

//tag::ios[]

If you use CT Mobile package v. 3.54 and higher with the CT Mobile app
below v. 2.4, contact the Customertimes team to perform the required
actions.

//tag::win[]

If you use CT Mobile package v. 3.54 and higher with the CT Mobile app
below v. 1.3, contact the Customertimes team to perform the required
actions.

[[h2_1934422811]]
=== 3. Update Profile IDs and Load Settings

First, define the profiles used and convert the profile IDs to an
18-digit format.

. Go to *Setup → Custom Settings*.
. Click *Manage* next to *Mobile Application Setup*.
. Click the profile and copy the 15-digit profile ID.
. https://www.adminbooster.com/tool/15to18[Follow the link] and convert
the profile ID to an 18-digit format.

Perform steps 1-2 for all specified profiles.



Next, using https://workbench.developerforce.com/login.php[Workbench] or
https://dataloader.io/[Data Loader]:

. From the production environment, download the
[.apiobject]#.csv# file with the *CTM Settings* records and
records of the following custom settings:
* *Related List Filters*
* *Mobile Custom Details Settings*
* *Mobile Mini Layout Settings*
. Replace the value in the *Org ID/Profile ID* field in the records from
step 1 with the converted profile IDs in an 18-digit format.
[NOTE] ==== If the *Org ID/Profile ID* field is empty on the
**Mobile Custom Details Setting**s and *Mobile Mini Layout Settings*
records, do not enter any value—the settings are the same for all
profiles. ====
. Upload the updated[.apiobject]#.csv# file to the sandbox.

The setup is complete.

[[h2_76823137]]
=== 4. Check CLM Presentations

For the correct display of CLM presentations:

. Go to *Applications* → select the required CLM presentation → click
*Renew slides* and select the delay → click *OK*.
. Repeat step 1 for all active CLM presentations.

For more information, refer
to xref:publishing-clm-presentations#h3_1098755975[Publishing CLM
presentations].

[[h2_822727760]]
=== 5. Perform a Full Synchronization

The setup is complete. After completing all the steps, perform a
xref:ios/mobile-application/synchronization/full-synchronization.adoc[full synchronization] in the CT Mobile
app.
