= Quiz Completion Field Reference

the [.object]#Quiz Completion# object is intended to store the
completed questionnaire linked to the
corresponding _xref:quiz-partaker-field-reference.html[Quiz
Partaker]_ record.

'''''

API name in Salesforce: QuizCompletion__c

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Activity |ActivityId__c |Lookup(Activity) |The related _CT Pharma
Activity_ record if the questionnaire has the *External* record type and
was completed by a customer during a visit.

|Attempts |AttemptCount__c |Number(18,0) |The unlimited by
default number of the partaker's attempts to complete a quiz.

|Completed |IsCompleted__c |Checkbox |If selected, the quiz is
complete.

|Completion Time |ComletionTime__c |Number(18,0) |Total time
spent completing the quiz.

|Correct Answer |correctAnswerPercent__c  |Percent(18,0) |The
percent of the correct answers.

|Description  |Description__c |Long Text Area (32768) |Specify
information about the quiz completion.

|IsUserEndedQuiz |IsUserEndedQuiz__c  |Checkbox  |If selected,
the quiz is complete or interrupted by a quiz partaker.

|Mobile Id |MobileId__c  |Text(255) a|
[NOTE] ==== Is used in case of integration with the CT Mobile
app.  ====

If filled out, the quiz was passed on the mobile device.

The Mobile ID is a unique identifier to identify the record that was
created or edited in the CT Mobile app.

|Quiz |QuizId__c |Master-Detail(Quiz)      |The parent _Quiz_
record.

|Quiz Partaker |QuizPartaker__c |Lookup(Quiz Partaker) |The
related _Quiz Partaker_ record.

|Start Date |StartDate__c |Date/Time a|
The date and time when the partaker starts the quiz.

|User |UserId__c  |Lookup(User) |The related _User_ record.
|===
