= Salesforce Winter '21 Release

Due to link:https://help.salesforce.com/articleView?id=release-notes.getstart_browsers_sfx.htm&type=5&release=228[Salesforce does not support] the Private Browsing mode (Incognito) in Lightning Experience, do not use this mode in any browser when working with the following:

* Joint Visit Template Editor
* Joint Visit Report
* xref:admin-guide/calendar-management/legacy-calendar-management/index.adoc[Calendar]
* Change Request pages
* xref:admin-guide/pharma-activity-report/index.adoc[Activity Report]
* xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-marketing-cycle/marketing-detail-tracking/index.adoc[Marketing Detail Tracking]
* Personal Marketing Cycle
* Buttons
** xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/creating-a-targeting-list.adoc[Mass Managing (Account or Contact) Targets]
** Add Selected to Event

Otherwise, set up third-party cookies to use the CT Mobile package features in Lightning Experience via the incognito mode. For example, if you are using Google Chrome, follow the instructions link:https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Callow-or-block-cookies[here].
