= Vision Account Object Field Reference

The _Vision Account Object_ record type is used to define an [.object]#Account# object different from the standard _Account_, for example, to support the integration of CT Vision with https://help.customertimes.com/articles/ct-mobile-ios-en/cg-cloud[the CG Cloud solution]. If the setting exists, the specified [.object]#Account# object is added to the *Account Name*  picklist of the *Advanced Filters* section on the xref:2.8/admin-guide/working-in-salesforce/index.adoc[Feedback Loop] page and may be used as a filter.

'''''

Record Type API Name: [.apiobject]#Vision Account Object#

'''''

The following fields must be created on the [.object]#Vision Settings# object for this record type:

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name*                    |*Type*    |*Description*
|Object  |[.apiobject]#clm\__Object__c# |Text(255) |Specify the API name of the object that is used as an [.object]#Account# object, for example, RetailStore.
|===
