= Objectives Management

xref:/articles/project-ct-cpg/objectives-management[Objectives] are used
as representative's notes and goals within the visit or as regular notes
for the client linked to the corresponding _Account_ or _Contact_
record. Objectives could be tracked during the time period before
completion or repeated per each visit.



Follow the guidelines to create objectives.

. Think about the objectives and tasks you need to track and audit
during a visit.
* Create regular objectives for the _Account_ and/or _Contact_
records.
* Add objective to the _CT CPG Activity_ record to transfer it for the
related _Account_ and/or _Contact_ record.
* Create an objective based on the value in the finished _CT CPG
Activity_ via the *Next Call Objective* field or the _Next Activity_
functionality.
* xref:admin-guide/targeting-and-marketing-cycles-management/create-a-new-record-of-marketing-detail-tracking#h2_726145408[create the _Marketing
Detail Tracking_ record] of the *Special Tracking* record type to track
objectives xref:admin-guide/targeting-and-marketing-cycles-management/ref-guide/index[within the
active marketing cycle].
. Specify objectives tracking on
the _xref:enable-objectives-tracking.html[Application Settings]_ record.


