= Creating an Objective
:toc:

Objectives can be specified in different ways according to business purpose. xref:admin-guide/objectives-management/enable-objectives-tracking.adoc[Track objectives] for up-to-date reports.

We recommend link:https://help.salesforce.com/articleView?id=admin_files_related_list_setup.htm&type=5[adding the _Objectives_ related list] on the _Account_ and _Contact_ page layout to have an ability to manage objectives for an _Account_ or _Contact_ record and xref:admin-guide/activity-report-management/manage-field-sets-for-activity-report-pages.adoc[add to the corresponding _CT CPG Activity_ field set(s)] the [.apiobject]#CTCPG\__Objective__c# and [.apiobject]#CTCPG\__NextCallObjective__c# fields.

[[h2_1347415082]]
== Create a regular Objective for the Account or Contact

Create an Objective on the _Objectives_ related list for the particular _Account_ and/or _Contact_ record to automatically set it to the related _CT CPG Activity_ record.

To create an objective for the particular _Account_ or _Contact_ record:

. Go to the *Accounts* tab and click the required _Account_ record.
. On the *Related* tab, click *New* under the *Objectives* related list.
. Specify the following:
+
TIP: Read the description of each parameter xref:admin-guide/objectives-management/objective-field-reference.adoc[here].

* Add *Contact* if needed.
* Set *Active*.
* Add** Objective**.
. Click *Save*.
. Repeat steps 1–4 for the _Contact_ records.

The objective is set.

When a representative creates a _CT CPG Activity_ record related to the _Account_ or _Contact_ record with the specified _Objective_ record, the _Objective_ value will be automatically set in the [.apiobject]#CTCPG\__Objective__c# field of this _CT CPG Activity_ record.

NOTE: If the related _Account_ record has a relative _Objective_ record, the objective will be added to the _Objective_ related list for all _Contact_ records of
that _Account_. Specify another _Objective_ record for the particular _Contact_ record to overwrite the _Account_ objective.

[[h2_280478342]]
== Create an Objective for Activity

Set an objective for the particular _CT CPG Activity_, and it will be automatically assigned to the related _Account_ and/or _Contact_ record. Manage activities via a Standard layout or by using a pre-configured xref:admin-guide/activity-report-management/index.adoc[Activity Report] page.

To create an objective for the particular _CT CPG Activity_ record:

. Go to the CT CPG Calendar and create a new _CT CPG Activity_ record with the _Visit_ record type.
. Open the created _CT CPG Activity_ record.
+
TIP: Also, you can open the required _CT CPG Activity_ from the *Calendar* or *Activity Reports* tab.
. In the [.apiobject]#CTCPG\__Objective__c# field, specify the required notes and/or goals.
. Click *Save*.

The objective is set.

When a representative creates a _CT CPG Activity_ record with the specific _Objective_ record and related to the _Account_ or _Contact_ record, the _Objective_ record will be added to the__ Objectives__ related list of the related _Account_ and/or _Contact_ record.

[[h2_2098968334]]
== Create an Objective using Next Call Objective

Copy the objective from the finished _CT CPG Activity_ record to the next _CT CPG Activity_ record that is related to the same _Account_ and/or _Contact_ record. Manage activities via a Standard layout or by using a pre-configured xref:admin-guide/activity-report-management/index.adoc[Activity Report] page.

To set up an objective for the next _CT CPG Activity_ record:

. Go to the CT CPG Calendar and create a new _CT CPG Activity_ record with the _Visit_ record type.
. Open the created _CT CPG Activity_ record.
+
TIP: Also, you can open the required _CT CPG Activity_ from the *Calendar* or *Activity Reports* tab.
. In the [.apiobject]#CTCPG\__NextCallObjective__c# field, specify the required notes and/or goals.
. Click *Save*.

The objective is set.

When a representative finishes the created _CT CPG Activity_ record and creates a next _CT CPG Activity_ record for the same _Account_ and/or _Contact_ record, a value from the [.apiobject]#CTCPG\__NextCallObjective__c# field of the finished _CT CPG Activity_ record is copied to the [.apiobject]#CTCPG\__Objective__c# field of
the next _CT CPG Activity_ record.

[[h2_1099816968]]
== Create an Objective using the Next Activity functionality

Use the xref:admin-guide/next-activity-management/index.adoc[Next Activity] functionality to copy an objective from the specified field of the finished _CT CPG
Activity_ record to the next _CT CPG Activity_ record that is related to the same _Account_ and/or __Contact __record. Manage activities via a Standard layout or by using a pre-configured xref:admin-guide/activity-report-management/index.adoc[Activity Report] page.

To create an objective using the _Next Activity_ functionality:

. Go to the CT CPG Calendar and create a new _CT CPG Activity_ record with the _Visit_ record type.
. Open the created _CT CPG Activity_ record.
+
TIP: Also, you can open the required _CT CPG Activity_ from the *Calendar* or *Activity Reports* tab.
. In the field that is selected for the _Next Activity_ functionality, specify the required notes and/or goals.
. Click *Save*.

The objective is set.

When a representative finishes the created _CT CPG Activity_ record and creates a next _CT CPG Activity_ record for the same _Account_ and/or __Contact __record, a value from the field that is selected for the _Next Activity_ functionality of the finished _CT CPG Activity_ record is copied to the [.apiobject]#CTCPG\__Objective__c# field of
the next _CT CPG Activity_ record.

[[h2_97080500]]
== Objectives in the Marketing Cycle

xref:admin-guide/targeting-and-marketing-cycles-management/create-a-new-record-of-marketing-detail-tracking.adoc#h2_726145408[Create the _Marketing Detail Tracking_ record] of the _Special Tracking_ record type to track objectives xref:admin-guide/targeting-and-marketing-cycles-management/ref-guide/index.adoc[within the active marketing cycle].
