= CPG Groups Management

CPG Groups are intended to store objects' records in alignment with SOQL filters applied to these objects and their child objects. Use CPG groups to assign tasks per clients' segment, run promotions for not popular products, or set up an onboarding procedure for new users.

Follow the guidelines to configure _CPG Groups:_

* If needed, xref:./specify-a-custom-object-for-a-cpg-group.adoc[specify a custom object] to use in groups.
* xref:./create-a-static-cpg-group.adoc[Create static groups] for ad hoc tasks, such as e-mail newsletters.
* xref:./create-and-update-a-dynamic-cpg-group.adoc[Create and update dynamic groups] for scheduled procedures, such as a group of users for the onboarding process.

include::ROOT:partial$soql-query-notes-apostrophe.adoc[]

WARNING: We do not recommend to use different fields with the same names in the SOQL queries. The reason is that Dynamic SOQL in the Managed Package uses the default package field and ignores the field with the same name, but with the package prefix.