= Custom Scenario

The[.object]#Custom Scenario# object is intended to store
custom CLM presentation scenarios. A scenario may include slides from
different CLM presentations.

During the first full synchronization, the application requests the list
of users and shared scenarios for all the
xref:android/knowledge-base/ct-presenter/clm-scheme/clm-application.adoc[Applications] available to the user.

[NOTE] ==== The availability of functionality depends on the
platform of the mobile device. For more information, refer to
xref:android/ct-mobile-solution/ct-mobile-os-comparison.adoc[CT Mobile OS Comparison]. ====

'''''

Object API Name:[.apiobject]#clm__CustomScenario__c#

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Active |[.apiobject]#clm__isActive__c# |Checkbox |If
enabled, the custom scenario will be downloaded on the mobile device.

|Application |[.apiobject]#clm__ApplicationId__c#
|Master-Detail(Application) |The CLM presentation to which the custom
scenario is related.

|Combined |[.apiobject]#clm__isCombined__c# |Checkbox a|
If enabled, slides from various CLM presentations are used in a custom
scenario. Slides will be displayed according to the
[.apiobject]#clm__SlideId__c# field of a custom
scenario.



If disabled, slides only from one CLM presentation are used in a custom
scenario. Slides will be displayed according to the
[.apiobject]#clm__Branch__c# field of a slide.

|Description |[.apiobject]#clm__Description__c#
|Text(255) |The description of the custom scenario.

|Favorite |[.apiobject]#clm__isFavorite__c# |Checkbox
|If enabled, the custom scenario is a favorite and will be displayed in
xref:android/home-screen[the Carousel of CLM presentations on the Home
Screen] or xref:android/mobile-layouts-applications[in the widget on the
record's mobile layout].

|Scenario Editor |[.apiobject]#clm__ScenarioEditor__c#
|Formula(Text) |Used for the Scenario Editor launch.

|Scenario Name |[.apiobject]#clm__ScenarioName__c#
|Text(255) |The custom scenario name. It may be used
https://help.customertimes.com/smart/project-ct-mobile-en/changing-slides[in
the navigation].

|Slides |[.apiobject]#clm__SlideId__c# |Long
Text(131072) |Slide IDs (separated by a comma, without blank space).

|User |[.apiobject]#clm__UserId__c# |Lookup(User) |The
ID of the user who created the custom scenario.
|===
