= Layout Settings Field Reference

The *Layout Settings* object is a custom object for storing all the
basic display settings for the selected object's record screen.

The record screen display can be configured for an object, object with
the desired record type, user profile, and their combinations. For
example, you can configure the display of the _Activity_ object with the
*Visit* record type for a sales rep's profile.

'''''

API name in Salesforce: ctlayout__LayoutSettings__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|External Id |ctlayouts__ExternalId__c |Text(255) (External Id)
(Unique Case Insensetive) |Automatically completion case of mass record
migration, for example, via Data Loader or integration with ERP system.

|Layout JSON |ctlayouts__Layout__c |Long Text Area(131072)
|link:json-specifications-and-examples.html[A formed JSON file] that
stores settings specified in the
link:ct-layouts-editor-customize-tabs.html[CT Layouts Editor] for
the ctlayouts__Object__c.

|Layout Settings Label |ctlayouts__Label__c |Text(255) |The
label is to display in the CT Mobile app. Available values:

|Layout Settings Name |Name |Text(80) |Name for the corresponding
record.

|Object API Name |ctlayouts__Object__c |Text(255) |Specify the
API name of the object to customize its screens.

|Record Type |ctlayouts__RecordType__c |Text(255) a|
The record type of ctlayouts__Object__c for which the settings
will be applied. Available values:

* --Master-- is used when there is no custom record types or custom
record types are not available for the desired user profile
* any custom record type name

|Unique Id |ctlayouts__UniqueId__c |Text(255) External Id)
(Unique Case Insensetive) a|
Automatically completion by concatenation of values
from ctlayouts__Object__c,
ctlayouts__RecordType__c, and ctlayouts__Profile__c.

The value must be unique within the ctlayouts__LayoutSettings__c
records.

|User Profile |ctlayouts__Profile__c |Text(255) a|
The profile name of the user profile.

If you update a profile name, the setting will be disabled. Please do
not use standard profiles to avoid setting disabling due to the
translation of the profile name into the user's language.

|===
