= CT Vision IR Administrator Guide

To configure CT Vision IR:

. link:Getting-Started/1-installing-the-ct-vision-package-2-9.adoc[Install the CT Vision
managed package] to your Salesforce organization.     
. link:2-creating-vision-settings-records-2-9.html[Create the Vision
Settings records] for working with the CT Mobile app.
. link:3-specifying-product-objects-and-fields-2-9.html[Perform general
configuration] on the Salesforce side.
. link:4-setting-up-integration-with-the-image-recognition-providers-2-9.html[Add
the desired providers] and set up a connection.
. link:5-configuring-ct-mobile-to-work-with-ct-vision-ir-2-9.html[Add CT
Vision to the CT Mobile app].
. link:6-adding-information-for-products-to-be-recognized-2-9.html[Add
marketing photos] and additional information for products to be
recognized, configure uploading them to the CT Vision server, and
customize the layout for the required [.object]#Product# object.
. link:7-specifying-photo-tags-2-9.html[Specify photo tags].

When the CT Vision IR is configured, work with it in
link:working-with-ct-vision-ir-in-salesforce-2-9.html[Salesforce] and
link:working-with-ct-vision-ir-in-the-ct-mobile-app-2-9.html[the CT
Mobile app].

Integration with
https://help.customertimes.com/articles/ct-mobile-ios-en/cg-cloud[the CG
Cloud solution] is currently not supported.
