= Workshop 2.4 Objectives

This master class describes the steps for setting up a total discount based on the total price of products in a single delivery.

So, if you have multiple deliveries, and you set a 10% discount on the total price of products over $100, this discount will only apply to those deliveries with a total price over $100 for added products. Also, you can specify several discounts.

Prior to the setup process, please check on the following list of the prerequisites that should be carried out first:

* The account you are working with must xref:admin-guide/workshops/workshop-1-0-creating-basic-order/configuring-an-account-1-0.adoc[be able to make orders].
* Create a custom *Total For Discount* field with the API name [.apiobject]#TotalForDiscount__c# and the _Currency (16, 2)_ type on the xref:admin-guide/managing-ct-orders/delivery-management/delivery-line-item-field-reference.adoc[Delivery Line Item] object.
* Create one or more discounts to be automatically applied to the cart, xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-1/example-mixed.adoc[for example, structural, season, or contract].
+
NOTE: You need to specify the *External Id* of each Calculation Type that you want to apply in the order cart in the xref:admin-guide/workshops/workshop-2-0-setting-up-discounts/workshop-2-3-setting-up-a-manual-discount/setting-up-a-pricing-procedure-2-3.adoc[Pricing Procedure].
* Additionally, you can set up the xref:admin-guide/workshops/workshop-5-0-implementing-additional-features/5-3-displaying-price-tags.adoc[price tags] to display the information about the applied discounts.
