= Standard Related List

The *Standard Related List* record type is intended to store settings  for a standard related list of a specific xref:ios/admin-guide/managing-offline-objects/index.adoc[offline object,] as well as permissions and available actions with records of the standard related list for a specific profile.

TIP: To create or update the settings for the standard related lists, go to xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-offline-objects.adoc[CT Mobile Control Panel: Offline Objects]/xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-offline-objects-new.adoc[CT Mobile Control Panel 2.0: Offline Objects].

The following system variables can be used as a criterion:

* [.apiobject]#$User#
* [.apiobject]#$UserRole#
* [.apiobject]#$Profile#

For example, the [.apiobject]#{$User.Id}# criterion specified in parameters will automatically be set to a current user ID. Using such system variables will dynamically query the data relevant to the current user.

'''''

Record Type API name: [.apiobject]#StandardRelatedList#

'''''

[width="100%",cols="~,~,~,~",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Component |[.apiobject]#clm\__Component__c#
|Text(255) |List of menu items available in the CT Mobile menu.

|Conflict Manager
|[.apiobject]#clm\__IsConflictManagerEnabled__c#
|Checkbox |The xref:ios/admin-guide/managing-offline-objects/conflict-manager-control.adoc[Conflict Manager] is used to track the changes made in a single record in the mobile application and on the Salesforce side.

|Creating Allowed
|[.apiobject]#clm\__IsCreatingAllowed__c# |Checkbox a|
Enable to create records:

* Of the offline object, if the API Name of this object is set in the [.apiobject]#clm\__sObjectRelated__c# field.
* Of the related list's object, if the API Name of the related list's object is set in
the [.apiobject]#clm_sObjectRelated__c# field.

The permission to create a record cannot overcome the same profile permission.

|Criteria |[.apiobject]#clm\__Criteria__c# |Long Text Area(32768) a|
Stores xref:ios/admin-guide/related-lists/filters-in-related-lists.adoc[a SOQL query] to filter related objects' records in the standard related list to display. Tap
the switch button on the *Related* tab in the mobile application to display all records or only records that are eligible for criteria.

The criteria line should start with the [.apiobject]#WHERE# keyword.

|Default View |[.apiobject]#clm\__View__c# |Text(255)
|Stores the *Timeline* value to display records in xref:ios/admin-guide/related-lists/timeline-view.adoc[Timeline] view. In other cases, left blank.

|Deleting Allowed
|[.apiobject]#clm\__IsDeletingAllowed__c# |Checkbox a|
Enable to delete records:

* Of the offline object, if the API Name of this object is set in the [.apiobject]#clm\__sObjectRelated__c# field.
* Of the related list's object, if the API Name of the related list's object is set in the [.apiobject]#clm_sObjectRelated__c# field.

The permission to delete a record cannot overcome the same profile permission.

The records which have not been synchronized may always be deleted, no matter what access the profile is granted.

|External Id |[.apiobject]#clm\__ExternalId__c#
|Text(255) |Contains the ID of the corresponding record of custom settings.

|Grouping Field |[.apiobject]#clm\__GroupingField__c#
|Text(255) |The API name of the field by which the entries will be grouped in the lists.

|Object |[.apiobject]#clm\__Object__c# |Text(255) |The
API name of the offline object, if the API Name of the related list's object is set in the [.apiobject]#clm_sObjectRelated__c# field.

|Object Record Type
|[.apiobject]#clm\__ObjectRecordType__c# |Text(255)
|Stores an API Name of a record type of the offline object that is specified in the [.apiobject]#clm\__Object__c# field.

|Online Fetching
|[.apiobject]#clm\__IsOnlineFetchingEnabled__c#
|Checkbox |The setting defines if the xref:ios/admin-guide/managing-offline-objects/online-records-fetching.adoc[Load more records] button is available in the application.

|Order |[.apiobject]#clm\__Order__c# |Number(18, 0) |The parameter defines the loading order of an offline object during synchronization.

|Org ID/Profile ID |[.apiobject]#clm\__OrgProfileId__c#
|Text(255) a| xref:ios/getting-started/application-permission-settings.adoc[Organization ID/Profile ID] to which this setting is applicable:

* if Profile ID is set, the setting is applied only to the profile;
* if Organization ID is set, the setting is applied to all non-configured profiles.
* if Profile ID and Organization ID are not set, the setting is applied to all non-configured profiles.

|Quick Sync |[.apiobject]#clm\__IsQuickSyncEnabled__c#
|Checkbox |Enable xref:ios/mobile-application/synchronization/synchronization-launch/index.adoc[Quick Record Synchronization] for records of the offline object.

|Reference Field |[.apiobject]#clm\__ReferenceField__c#
|Text(255) |Stores an API Name of the field of the related object with a reference to the record of the parent object specified in the [.apiobject]#clm\__Object__c# field.

|Related Object |[.apiobject]#clm\__RelatedObject__c#
|Text(255) a|
* the API Name of the offline object, if the setting is applicable for this object;
* the API Name of the related list's object, if the setting is applicable for the records of the related list.

|Sorting Criteria |[.apiobject]#clm\__SortingCriteria__c#
|Text(255) |Stores a field to sort records in Timeline view if the *Timeline* value is set in the [.apiobject]#clm\__View__c# field.

|Sorting Order |[.apiobject]#clm\__SortingOrder__c#
|Text(255) a| Stores an ascendant (ASC) or descendant (DESC) sorting order for records of a standard related list.

Do not specify the field if the *Timeline* value is set in the [.apiobject]#clm\__View__c# field.

|Sync Recovery |[.apiobject]#clm\__SyncRecovery__c#
|Text(255) a| Enable xref:ios/mobile-application/synchronization/sync-recovery.adoc[Sync Recovery] to deliver records that could not be synchronized to Salesforce anyway. Available values:

* An empty value means that the web service is not involved.
* *Direct access* means the pushing of the record changes directly to an object via the additional web service.
* *Proxy object* means the pushing of the record change as a modifiable JSON file in the [.object]#Sync Log# object attachments.

|===
