= Menu

The _Menu_ record type is intended to store settings for the main menu  for a specific profile, such as the order of menu items, offline objects, and modules, the order of modules.

TIP: To create or update the main menu settings, go to xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-app-menu.adoc[CT Mobile Control Panel: App Menu] / xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-app-menu-new.adoc[CT Mobile Control Panel 2.0: App Menu].

'''''

Record Type API Name: [.apiobject]#Menu#

'''''

[width="100%",cols="~,~,~,~"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Component |[.apiobject]#clm\__Component__c# |Text(255)
a|
Stores an API Name of xref:ios/admin-guide/managing-offline-objects/index.adoc[an offline object], xref:ios/mobile-application/mobile-application-modules/index.adoc[module's name], or name of a menu item, e.g., xref:ios/mobile-application/ui/home-screen/index.adoc[Home] and xref:ios/mobile-application/application-settings/index.adoc[Settings], that will be available in xref:ios/admin-guide/app-menu/index.adoc[the main menu].

A record of the _Menu_ record type should be created per each component.

|External Id |[.apiobject]#clm\__ExternalId__c# |Text(255) |Contains the ID of the corresponding record of custom settings.

|Fields |[.apiobject]#clm\__Fields__c# |Long Text Area(32768) a| List of fields displayed in criteria setting and *Records preview* section while creating a new xref:ios/mobile-application/ui/list-views.adoc#h2_380480215[mobile list view], comma separated. If the list is not set, then all existing fields will be available for creating a new mobile list view.

|Files Download Enabled
|[.apiobject]#clm\__IsFilesDownloadEnabled__c# |Checkbox a|
NOTE: Applies if the *Component* field has _Content_ value.

Defines the way how xref:ios/mobile-application/mobile-application-modules/libraries.adoc[Library] object must be downloaded during synchronization, as full content or as a preview.
Interacts with the xref:ios/mobile-application/application-settings/index.adoc#h3_1768799377[Background content loading] parameter in the *Application Settings*. Available values:

* _true_: the attached file will be downloaded as full content:
** *Background content loading* is enabled: the full content of the [.object]#Library# object will be downloaded after xref:ios/mobile-application/synchronization/index.adoc[synchronization] with displaying a loader.
** *Background content loading* is disabled: the full content of the Library object will be downloaded after xref:ios/mobile-application/synchronization/index.adoc[synchronization].
* _false_ (default):  the attached file will be downloaded as preview. Tap on the preview to download the full content:
** *Background content loading* is enabled: tap on the preview to download the full content. You can tap on several objects, they will be downloaded in a row.
** *Background content loading* is disabled: tap on the preview to download the full content. Tapping on several objects will not work, each object will be downloaded separately.

|Grouping field |[.apiobject]#clm\__GroupingField__c#
|Text(255) a| Stores an API Name of a field for xref:ios/admin-guide/app-menu/grouping-records.adoc[grouping records] in xref:ios/admin-guide/app-menu/index.adoc[the main menu].

Specify only if an offline object is set in the [.apiobject]#clm\__Component__c# field.

|Order |[.apiobject]#clm\__Order__c# |Number(18,0) a| Stores the position of a component in the main menu.

The order of menu items should be specified in the [.apiobject]#clm\__MenuSettings__c# field of xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/menu-settings-and-offline-objects.adoc[Menu Settings and Offline Objects]. А menu item should be listed in the [.apiobject]#clm\__Component__c# field, and its position should be set in the [.apiobject]#clm\__Order__c# field, for the mobile application on iOS devices.

|Org ID/Profile ID |[.apiobject]#clm\__OrgProfileId__c# |Text(255) a| Stores the profile's ID. Left blank or specify an Organization ID to apply for all non-configured profiles.

NOTE: The [.apiobject]#SetupOwnerId# field is no longer used.

|Sorting Order |[.apiobject]#clm\__SortingOrder__c# |Text(255) a| Stores an ascendant (ASC) or descendant (DESC) sorting order for menu item records.

Specify only if an offline object is set in the [.apiobject]#clm\__Component__c# field.

|===
