= CTM Settings
:toc:

[.object]#CTM Settings# is intended to store settings defined in the xref:ios/admin-guide/ct-mobile-control-panel/index.adoc[CT Mobile Control Panel].
[.object]#CTM Settings# has record types that correspond to specific xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/index.adoc[custom settings].

'''''

Object API name: [.apiobject]#clm\__CTMSettings__c#

'''''

[[h2_1375710402]]
== Permissions

Assign xref:ios/getting-started/application-permission-settings.adoc#h3_2115044027[the
preconfigured permission sets]: _CT Mobile Administrator_ and _CT Mobile User_.

Depending on their type, all users should have required access to [.object]#CTM Settings#. There is no need to specify sharing rules for records of the [.object]#CTM Settings# object. During synchronization, only settings related to the current user will be downloaded.

[[h2_687217078]]
== Current limitations

WARNING: Any changes to the settings must be made using the *CT Mobile Control Panel*. Manually changing the custom settings or [.object]#CTM Settings records can cause data
inconsistencies between Salesforce and the CT Mobile app.

Due to link:https://help.salesforce.com/articleView?id=cs_limits.htm&type=5[the limitations of custom settings] and since CT Mobile 2.2:

* Settings for the xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/menu-settings-and-offline-objects.adoc[menu], xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/related-list-filters.adoc[offline objects, and standard related lists] will b saved both in custom settings and [.object]#CTM Settings#.
* To support consistency of applied settings, the ID of the record of the corresponding custom settings will be specified in the [.apiobject]#clm\__ExternaId__c# field of the
[.object]#CTM Settings# record with the corresponding record type.
* Settings for the menu offline objects and standard related lists will be downloaded to the CT Mobile app from the records of *CTM Settings* with the following record types.
** xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/ctm-settings-menu.adoc[Menu]
** xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/ctm-settings-offline-objects.adoc[Offline Objects]
** xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/ctm-settings-standard-related-list.adoc[Standard Related List]
* Other settings will still be downloaded from custom settings.
* The *CT Mobile Control Panel* displays settings of the menu, offline objects, and standard related lists given the *CTM Settings* records and other settings given custom settings.

For devices with installed CT Mobile below 2.2, all settings for the CT Mobile app are still synchronized from custom settings.

[[h2_1914523927]]
== Migration to the CTM Settings Records

The table below contains all _CTM Settings_ record types, corresponding custom settings to them, the *CT Mobile Control Panel* tabs for setup, and the CT Mobile version, since which the logic of working with the [.object]#CTM Settings# object is supported. All _CTM Settings_ record types have already been added to the CT Mobile package.

NOTE: The table below is incomplete and is filled out based on the supported _CTM Settings_ record types.

[.hightlighted-table]
[width="100%",cols="^~,^~,^~,^~,^~,^~,^~,^~"]
|===
.2+|*CTM Settings Record Type* .2+|*Custom Setting* .2+|*CT Mobile Control Panel Tab* 5+^.^|*CT Mobile Release* |*CT Mobile Package* |*CT Mobile iOS* |*CT Mobile Windows* |*CT Mobile Android* |*CT Mobile Android 2.0*
|Activity  |Mobile Application Setup |Calendar  | |  |  .12+|No .7+|Future
|Calendar |Mobile Application Setup |Calendar |  |  |
|Color Settings |Mobile Customization |Color Settings |  |  |
|Credentials |API Key / Mobile Credential Data |Tools |  |  |
|Link List |Mobile Link Lists |App Menu |  |  |
|Main Settings |Mobile Application Setup |General |  |  |
|Mapping |Mobile Application Setup |General |  |  |
|Menu |Menu Settings and Offline Objects |App Menu |Since 3.34.7 |Since 2.2 |Since 1.3  |No
|Mini Layouts |Mobile Mini Layout Settings |Mini Layouts |  |  |   |Future
|Offline Objects |Menu Settings and Offline Objects |Offline Objects |Since 3.34.7 |No |Since 1.3  |No
|Remote Detailing |CLM Settings |Presenter |  |  |   |Future
|Standard Related Lists |Related List Filters |Offline Objects, Custom Details |Since 3.34.7 |Since 2.2 |Since 1.3 | Since 2.1
|===

