= CT Mobile Workflow Step Field Reference

CT Mobile Workflow Step is a custom metadata type that is intended to
store actions after triggering CT Mobile Workflows (refer to
xref:ctmobile:main/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-workflows.adoc[CT Mobile Control Panel:
Workflows]/xref:ctmobile:main/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-workflows-new.adoc[CT Mobile
Control Panel 2.0: Workflows]). Conditions for triggering CT Mobile
Workflow are stored in the xref:ct-mobile-workflow[CT Mobile
Workflow] object.

Some deprecated fields are displayed on the page layout. Hide these
fields and add the required ones.

'''''

API-name in Salesforce:
[.apiobject]#clm__WorkflowStep__mdt#

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Action |[.apiobject]#clm__Action__c# |Picklist a|
Action to be taken on the *CT Mobile Workflow Step*. Available actions:

* Create record
* Update record
* Delete record
* Sync record
* Capture geoposition

Proposed values:

* Lock record
* Unlock record

If you use two steps with updating geoposition in a raw (1. *Action* =
_Capture geoposition_ and 2. *Action* = _Update record_, *Field Values*
= _Geoposition_), then only the last step will work, and geoposition may
not be updated.

|API names (deprecated)
|[.apiobject]#clm__FieldAPINames__c# |Text(255) |Not in
use.

|Calculate formulas
|[.apiobject]#clm__IsCalculateEnabled__c# |Checkbox |If
selected, formulas will be recalculated on the record of the *CT Mobile
Workflow Step*.

|CT Mobile Workflow |[.apiobject]#clm__WorkflowId__c#
|Lookup(CT Mobile Workflow) |The related *CT Mobile Workflow*.

|Fields API names |[.apiobject]#clm__FieldAPIName__c#
|Text Area(131072) |API names of fields that are to be changed on the
*CT Mobile Workflow Step* (separated by a comma, without a blank space).

|Field Values |[.apiobject]#clm__FieldValue__c# |Text
Area(131072) a|
Values that populate fields in the
[.apiobject]#clm__FieldAPINames__c# field on the CT
Mobile Workflow Step (separated by a comma, without a blank space).



Available values:

* a specific value, e.g., "New Value"
*[.apiobject]#$Label#
*[.apiobject]#$query#

The supported format:
[.apiobject]#$query.a_field_API_Name#.

The value is the specific value in the field of the record found
according to[.apiobject]#clm__SOQLQuery__c#.

The Salesforce operators, for example, PRIORVALUE, are not supported.

|Order |[.apiobject]#clm__Order__c# |Number(18, 0) |A
number of the *CT Mobile Workflow Step* in case of several steps in the
*CT Mobile Workflow*.

|Parent Object (deprecated)
|[.apiobject]#clm__ParentObject__c# |Text(255) |Not in
use.

|Parent Object API Name
|[.apiobject]#clm__ParentObjectAPIName__c# |Text(255) a|
If the *Parent Record* value in the
[.apiobject]#clm__Scope__c# field:

* the API name of the parent object for the object in the
[.apiobject]#clm__ObjectAPIName__c# field of the
corresponding *CT Mobile Workflow* record.



If the *Related Records* value in the
[.apiobject]#clm__Scope__c# field:

* the API name of the object in the
[.apiobject]#clm__ObjectAPIName__c# field of the
corresponding *CT Mobile Workflow* record.

|Record Criteria (deprecated)
|[.apiobject]#clm__RecordCriteria__c# |Text(255) |Not
in use.

|Related Object |[.apiobject]#clm__sObjectRelated__c#
|Text(255) a|
If the *This Record* value in the
[.apiobject]#clm__Scope__c# field:

* the API name of the object in the
[.apiobject]#clm__ObjectAPIName__c# field of the
corresponding *CT Mobile Workflow* record.



If the *Parent Record* value in the
[.apiobject]#clm__Scope__c# field:

* the API name of the object in the
[.apiobject]#clm__ObjectAPIName__c# field of the
corresponding *CT Mobile Workflow* record.



If the *Related Records* value in the
[.apiobject]#clm__Scope__c# field:

* the API name of the object that is a child for the object in the
[.apiobject]#clm__ObjectAPIName__c# field of the
corresponding *CT Mobile Workflow* record.

|Relationship Name
|[.apiobject]#clm__RelationshipName__c# |Text(255) a|
The API name of the field with the *Lookup* type that connects the
objects of the[.apiobject]#clm__ParentObjectAPIName__c#
and[.apiobject]#clm__sObjectRelated__c# fields.

* It is used with the *Related Records* or *Parent Record* value in
the [.apiobject]#clm__Scope__c# field.
* The [.apiobject]#__r# postfix is used,
e.g., [.apiobject]#CTPHARMA__AccountId__r#.

|Scope |[.apiobject]#clm__Scope__c# |Picklist a|
Records to be changed on the CT Mobile Workflow Step. Available values:

* *This Record*

For records of the object in the
[.apiobject]#clm__sObjectRelated__c# field (the
[.apiobject]#clm__ParentObjectAPIName__c# and
[.apiobject]#clm__RelationshipName__c# fields are
empty);
* *Parent Record*

For records of the object in the
[.apiobject]#clm__ParentObjectAPIName__c# field (the
[.apiobject]#clm__sObjectRelated__c# and
[.apiobject]#clm__RelationshipName__c# fields are
populated);
* *Related Records*

For records of the object in the
[.apiobject]#clm__sObjectRelated__c# field (the
[.apiobject]#clm__ParentObjectAPIName__c# and
[.apiobject]#clm__RelationshipName__c# fields are
populated).

|SOQL Object (deprecated)
|[.apiobject]#clm__SQOLObjectAPIName__c# |Text(255) |Not
in use.

|SOQL Object API Name
|[.apiobject]#clm__SOQLObjectAPIname__c# |Text(255) |The
API name of an object that is used as filter for generating new records
of an object in the[.apiobject]#clm__sObjectRelated__c#
or[.apiobject]#clm__ParentObjectAPIName__c# field.

|SOQL Query |[.apiobject]#clm__SOQLQuery__c# |Text(255)
a|
SOQL criteria is used to define records selection from external sources
to predefine new records generated by the action. In SOQL query, fields
of the filtered records can be compared with:

* a specific value, e.g.,[.apiobject]#New Value#;
* with a value in the field which triggers a Workflow.

The supported format:
[.apiobject]#$sObject.a_field_API_Name
#[NOTE] ==== Use field names with the
[.apiobject]#__c ====  postfix instead of __r#.
* the optional
https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_limit.htm#![LIMIT]
and
https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_orderby.htm[ORDER
BY] clauses are supported.

To check the null values, use the [.apiobject]#null# operator,
for example, [.apiobject]#WHERE ActivityDate != null#.

For example, filter *Activity Data* records to generate only records
with the *Product* record type that matched the SOQL-query.



The generated result is used for the clm__FieldValue__c field
with the $query value.

|SOQL Record Criteria
|[.apiobject]#clm__SOQLRecordCriteria__c# |Text(255) a|
SOQL Record Criteria is used to restrict the selection of records which
should be triggered by the CT Mobile Workflow. For example, if
an _Account_ record has 5 related _Contact_ records of employees, and 4
of them are shop assistants and 1 is their supervisor. With the SOQL
Record Criteria, you can set up triggering the CT Mobile Workflow only
for shop assistants.


If the *Parent Record* value in the
[.apiobject]#clm__Scope__c# field:

* the SOQL filter for records of the object in the
[.apiobject]#clm__ParentObjectAPIName__c# field;



If the *Related Records* value in the
[.apiobject]#clm__Scope__c# field:

* the SOQL filter for records of the object in the
[.apiobject]#clm__ObjectAPIName__c# field.

To check the null values, use the [.apiobject]#null# operator,
for example, [.apiobject]#WHERE ActivityDate != null#.

|Target (deprecated) |[.apiobject]#clm__Target__c#
|Picklist |Not in use.

|Values (deprecated) |[.apiobject]#clm__FieldValues__c#
|Text(255) |Not in use.
|===
