= Workshop 3.1: Configuring Prioritized Freebie Type

In Workshop 3.1, you will learn how to distribute freebies based on one
condition because it has a higher priority than the others. In this
workshop:

. Create the[.object]#Freebie Type# to apply only the priority
condition.
. Create two[.object]#Freebie Conditions# for different
quantities:
.. For every 48 products added, distribute eight products of the chosen
brand as a freebie.
.. For every 12 products added, distribute only the same product (one)
as a freebie, but with a minimum and maximum distribution for each
order.
. Set up the *Delivery Control* option for each condition, which
determines the first or last delivery to give away freebies.



If certain conditions are met, in the Freebie window:

*[.object]#Freebies# will be automatically distributed (and
unmatched cells will be blocked), or you should manually add freebies up
to the minimum required number.
* The Freebie window interface will update depending on which condition
is triggered.
