= Salesforce Update: Enable Multi-Factor Authentication

Salesforce prepares an update concerning the security of the Salesforce products. _Since February 1, 2022_, Salesforce will begin requiring  customers to enable multifactor authorization (MFA) to access Salesforce products.

For more information, go to:

* https://help.salesforce.com/s/articleView?id=000356005&type=1[Announcement of the Future Requirements to Enable Multi-Factor Authentication (MFA)
(published 15 March 2021)]
* https://help.salesforce.com/s/articleView?id=000352937&type=1[Salesforce Multi-Factor Authentication F.A.Q.]
* https://www.salesforce.com/content/dam/web/en_us/www/documents/guides/mfa-quick-admin-guide.pdf[MFA Quick Guide for Admins (for all Salesforce Products) (PDF)]
* https://help.salesforce.com/s/articleView?id=sf.mfa_welcome_to_mfa.htm&type=5[How to Roll Out Multi-Factor Authentication]

[[h2_868831931]]
== Important Notes

NOTE: If you cannot meet the MFA requirement until February 1, 2022, _you would not be aligned with the terms of the Salesforce usage agreement_. If you have any questions regarding the MFA rollout, we recommend creating a case to Salesforce.

* Although the MFA requirement is contractual, and users should have the configured MFA when logging in through the user interface, starting February 1, 2022, _users will not be blocked from logging into Salesforce unless MFA is configured_.
* Salesforce will announce any features added in Salesforce Core for enforcement, and the enforcement will occur over several releases. We recommend
reading https://help.salesforce.com/s/articleView?id=000362737&type=1[Multi-Factor Authentication (MFA) Enforcement Roadmap].
* If you are planning a staged MFA rollout for different categories of users, Salesforce highly recommends starting with administrators because they control data and security within your Salesforce org.

[[h2_1535437264]]
== Prepare your CT Mobile to Salesforce Update

Since CT Mobile 2.1, all standard CT Mobile releases include xref:ios/getting-started/logging-in/oauth-2-0.adoc[the OAuth 2.0 protocol] to meet MFA.

* If you are using the standard CT Mobile app from the App Store, no additional action is required on your part.
* If you are using the custom CT Mobile 2.1 or higher with the enabled OAuth 2.0, no additional action is required on your part.

_We notify you to perform the following actions:_

* If you are using the custom CT Mobile 2.1 or higher and _have disabled OAuth 2.0_ by custom code, enable OAuth 2.0 to provide MFA.
* If you are using the standard CT Mobile 1.9.6 or custom CT Mobile below 2.1, do one of the following actions:
** Migrate to the latest version of the standard CT Mobile app.
** Enable OAuth 2.0 in your CT Mobile app by custom code.
