= Product Component Field Reference

The [.object]#Product Component# object is a junction object between a bundle and a product and used in link:https://help.customertimes.com/smart/project-order-module/product-management[product management] for CT Orders. One product can be a part of different bundles.

'''''

Object API name: [.apiobject]#CTPHARMA_ProductComponent__c#

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API name* |*Type* |*Description*

|Bundle |[.apiobject]#Bundle2Id__c# |Lookup(CT Product) |A bundle that includes the current Salesforce product.

The field must be manually created by the administrator.

|Bundle |[.apiobject]#CTPHARMA\__BundleId__c# |Lookup(Product2)
|A bundle that includes the current _Pharma Product_.

|Multiplier |[.apiobject]#CTPHARMA\__Multiplier__c# |Number(18,0) |A multiplying factor sets the ratio for multiplying the number of products in the bundle.

|Product |[.apiobject]#CTPHARMA\__ProductId__c# |Lookup(CT Product) |This is a lookup to store a _Pharma Product_ identifier.

|Product |[.apiobject]#Product2Id__c# |Lookup(Product2) |
This is a default lookup to the standard link:https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_product2.htm[Product] record in case of working with the CG Cloud solution.

The field must be manually created by the administrator.
|===
