= CTM User Settings

ifdef::kotlin[] ifdef::andr,win[][NOTE] ==== Not
available. ====[.object]#CTM User Settings# is an object to
store settings for xref:list-views#h2__380480215[custom list views]
created on the mobile device.

Available record types:[.apiobject]#ListView#

'''''

Object API name:
[.apiobject]#ListViewclm__CTMUserSettings__c#

'''''

[cols=",,,",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Criteria |[.apiobject]#clm__Criteria__c# |Long Text
Area(32768) |The SOQL query is used to filter records that should be
presented in a custom list view. The SOQL query is stored in the
[.apiobject]#base64# format.

|Fields |[.apiobject]#clm__Fields__c# |Long Text
Area(32768) |Columns of a custom list view. Fields are stored in the
[.apiobject]#base64# format.

|Label |[.apiobject]#clm__Label__c# |Text(255) |The
label of a custom list view.

|Object |[.apiobject]#clm__Object__c# |Text(255) |The
API Name of xref:managing-offline-objects[an offline object] for
which the custom list view was created.

|OwnerId |[.apiobject]#OwnerId# |Text(255) |The User Id of the
mobile user who created a custom list view.
|===
