= Target Frequency Field Reference

The[.object]#Target Frequency# object is intended to store the
number of planned and actual activities for the _Account_ or _Contact_
record.

'''''

API name in Salesforce: CTCPG\__TargetFrequency__c

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Account         |CTCPG\__AccountId__c |Lookup(Account)
|The related _xref:admin-guide/application-settings-management/account-field-reference.adoc.html[Account]_ record.

|Active |CTCPG\__IsActive__c |Checkbox |If selected,
the _Target Frequency_ record is active.

|Actual Calls         |CTCPG\__ActualCalls__c |Number(18,0)
a|
The number of finished activities of
the __Account __or _Contact_ record.

|Category |CTCPG\__Category__c |Text(255) |The category of
the related _Account_ or _Contact_ record.

|Contact |CTCPG\__ContactId__c |Lookup(Contact)         |The
related _xref:admin-guide/application-settings-management/contact-field-reference.adoc.html[Contact]_ record.

|Deactivation Date / Time |CTCPG\__DeactivationDateTime__c
|Date/Time |The date when the __Target Frequency __record will be
deactivated and the value in the CTCPG\__IsActive__c field will
be False.

|Description |CTCPG\__Description__c |Long Text Area(32768)
|If needed, specify the description.

|Last Call Date |CTCPG\__LastCallDate__c |Date |Specify the
last date when the user can create _Activity_ of the current _Target
Frequency_ record.

|Marketing Cycle |CTCPG\__MarketingCycleId__c |Lookup(Marketing
Cycle) |The related _xref:marketing-cycle-field-reference.html[Marketing
Cycle]_ record.

|Marketing Detail Tracking
|CTCPG\__MarketingDetailTrackingId__c |Lookup(Marketing Detail
Tracking) |The
related _xref:marketing-detail-tracking-field-reference.html[Marketing
Detail Tracking]_ record.

|Owner |CTCPG\__OwnerId__c |Lookup(User) |The related
_xref:admin-guide/application-settings-management/user-field-reference.adoc.html[User]_ record.

|Planned Calls |CTCPG\__PlannedCalls__c  |Number(18,0)  |The
number of planned activities of the _Account_ or _Contact_ record.

|Unique User Number |CTCPG\__UniqUserNumber__c |Formula(Text)
|The unique number of the _User_ record.

|User Division |CTCPG\__UserDivision__c |Formula(Text) |The
assigned division on the _User_ record.
|===
