= Calendar Management

The new Calendar is available since the version 1.60 of the CT CPG
package.

In this section:

* Get familiar with
the xref:admin-guide/new-calendar-management/calendar-interface-and-activities[Calendar interface and
activities management].
* Learn about xref:admin-guide/new-calendar-management/calendar-settings-ct-cpg-settings-panel[Calendar
settings].
* xref:calendar-interface[]Learn
about xref:admin-guide/new-calendar-management/custom-labels-for-translating-the-calendar-interface[custom
labels for translating the Calendar interface].
* Check the xref:admin-guide/new-calendar-management/custom-permissions-for-using-calendar[required
permissions and field names rules] for using Calendar.
* Read field description for
the xref:admin-guide/new-calendar-management/new-calendar-settings-field-reference[Planning Calendar
Settings]xref:skill-mark-field-reference[ ]object.
* Learn about the xref:calendar-management[Legacy Calendar].

ifdef::hidden[] This section describes the new planning Calendar.
You still can use the xref:calendar-management[legacy Calendar],
however, it is not supported anymore.

[WARNING] ==== The calendar functionality is fully available for
the Google Chrome web browser. Other web browsers are not yet supported.
====

[WARNING] ==== For the stable work of the calendar, go
to *Setup* → *Session Setting* and select the *Lightning Web Security*
checkbox.  ====
