= ctm.openDataTableByQuery

The method of the xref:ios/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is
intended to open xref:ios/admin-guide/related-lists/custom-related-lists.adoc[a custom related list]
with records that meet the criteria. If set, records will be displayed
in the custom related list tabs.

[[h2_905713055]]
=== Query Format

[.apiobject]#SObject# is the JS object that indicates the API
name of the offline object with the following fields:

*[.apiobject]#Query# is SQL query to the database;
*[.apiobject]#SettingName# is a list of settings names of the
xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/mobile-custom-details-settings.adoc[Mobile Custom Details
Settings], such as permissions to create and/or delete a record in the
custom related list, a list of columns to display, filter, and sort
criteria, for the custom related list displaying;
*[.apiobject]#Reload# is responsible for the necessity of
reloading the current slide when closing the native window with the
records of the custom related list (optional attribute).

[[h2_442663712]]
=== Query Example


