= Changing Slides

Here are HTML code examples that can be used to navigate within CLM
presentations in CT Mobile app along with
xref:methods-for-clm-presentation-navigation[JS Bridge methods],
xref:ctmobile:main/mobile-application/mobile-application-modules/applications/gestures-in-clm-presentations.adoc[gestures], and
xref:ctmobile:main/mobile-application/mobile-application-modules/applications/clm-presentation-controls.adoc[button controls].



To jump from the current slide to the slide by its branch number in the
[.apiobject]#clm__Branch__c# field and the order number
in the[.apiobject]#clm__Order__c# field, add the
following code into the current slide markup:

//tag::ios,win[][TIP] ==== Available with the
xref:ctmobile:main/ct-presenter/the-remote-detailing-functionality/index.adoc[Remote Detailing]
functionality. ====



To switch from the current slide to a slide in another CLM presentation,
add a label to the[.apiobject]#clm__APPID__c# of
xref:ctmobile:main/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[the desired CLM presentation record] and add
the following code into the current slide markup, where
[.apiobject]#appID# is the label to the
[.apiobject]#clm__APPID__c# field:



To open the first slide of the scenario, add a label to the
[.apiobject]#clm__APPID__c# of the desired CLM
presentation record, specify the scenario label in the
[.apiobject]#clm__ScenarioName__c# of
xref:ctmobile:main/ct-presenter/about-ct-presenter/clm-scheme/clm-customscenario.adoc[the desired Scenario record], and add the
following code into the current slide markup, where
the [.apiobject]#appID# is the label to the
[.apiobject]#clm__APPID__c# field and
[.apiobject]#scenario_name# is the label from the
[.apiobject]#clm__ScenarioName__c# field:



For more information about slide navigation, refer
to xref:ctmobile:main/ct-presenter/clm-navigation-in-clm-presentations.adoc[Navigation in CLM
Presentations].
