= Activating JS Bridge

The *JS Bridge* functionality is intended for managing CRM data on a CLM
presentation by generating pre-configured JavaScript methods on a slide.

To activate JS Bridge, enable the JS Bridge library in the
[.apiobject]#<head># tag of a slide:



[width="100%",cols="100%",]
|===
a|
link:javascript:void(0)[Copy Code]

HTML

a|
....
<script type="text/javascript" src="../JSLibrary/js/app.js"></script>
....

|===



The source code of the JS Bridge library can be downloaded from the
static resource of Salesforce. The file name is
[.apiobject]#JsLibrary.zip#.

[[h2__1614277225]]
=== Event of functional readiness of JS Bridge: 

To check JS Bridge availability for use it is recommended to perform the
entire logic of interaction through addEventListener.



[width="100%",cols="100%",]
|===
a|
link:javascript:void(0)[Copy Code]

HTML

a|
....
document.addEventListener('WebViewJavascriptBridgeReady', function(event){
    console.log('JS Bridge is ready');
});
....

|===

[[h2__1136353801]]
=== Available JS Bridge Methods 

The following methods are outdated:[.apiobject]#getUSValues#,
[.apiobject]#playVideo#,[.apiobject]#skipTenPercent#,
[.apiobject]#CTAPPNewRecord#.

* link:android/methods-for-interaction-with-crm-data[Methods for
Interaction with CRM data]
* link:android/methods-for-accessing-external-functionality[Methods for
Accessing External Functionality]
* link:android/methods-for-clm-presentation-control[Methods for CLM
Presentation Control]
