= CLM Settings

ifdef::kotlin[] *CLM Settings* is the custom setting that stores
preferences to display xref:clm-application[CLM presentations] via
the Remote Detailing functionality.[TIP] ==== For easy setup,
go to xref:ct-mobile-control-panel-presenter[CT Mobile Control
Panel:
Presenter]/xref:ct-mobile-control-panel-remote-detailing-new[CT
Mobile Control Panel 2.0: Remote Detailing]. ====

'''''

Custom setting API name:
[.apiobject]#clm__CLMSettings__c#

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API-name* |*Type* |*Description*

|Application List Field
|[.apiobject]#clm__ApplicationsListField__c# |Text(255)
a|
The field API name of the xref:clm-activity[Activity] object for
the Application IDs storing, for example,
[.apiobject]#ApplicationIds__c#.

The field to store Application IDs should have the same API name on
any [.object]#Activity# object for the Remote Detailing or Self
Detailing session.

|Audio Record Enabled
|[.apiobject]#clm__IsAudioRecordEnabled__c# |Checkbox
|If enabled, the audio of the Remote Detailing session will be recorded
and saved as the _Attachment_ record with the audio file and linked to
the[.object]#Activity# object.

|Call Repeat Allowed
|[.apiobject]#clm__IsCallRepeatAllowed__c# |Checkbox a|
If enabled, the presenter can resume the finished Remote Detailing
session.

* The statistics will be collected after resuming the Remote Detailing
session;
* If specified, the same value will be assigned for all profiles.

|CRM Data Sharing Enabled
|[.apiobject]#clm__IsRDJSAPIEnabled__c# |Checkbox |If
enabled, xref:js-bridge-methods-availability[certain JS Bridge
methods] will be available on the CLM presentation during the Remote
Detailing or Self Detailing session.

|Delete After (days)
|[.apiobject]#clm_AudioCleanupAfter__c# |Number a|
The expiration date, after which the audio record should be deleted from
the *Activity* record.

* It is used when the
[.apiobject]#clm__IsAudioRecordEnabled__c# checkbox is
active.
* The default value is 30.

|Detailed Stats Enabled
|[.apiobject]#clm__IsRDDetailedStatsEnabled__c#
|Checkbox |If enabled, xref:remote-detailing-statistics[the
statistics] per slide will be gathered for each participant at the
meeting.

|Email Required Field
|[.apiobject]#clm__EmailRequiredField__c# |Text(255)
|The field API name of the *xref:clm-activity[Activity]* object,
for example,[.apiobject]#IsEmailRequired__c#. It indicates
if the user is required to provide an email on
xref:remote-detailing-2-0-ui-for-participants#h2__555694282[the
Welcome screen] to access the Remote Detailing meeting.

|Endpoint URL |[.apiobject]#clm__RestServicePrefix__c#
|Text(255) a|
[NOTE] ==== Not applied since CT Mobile package v. 3.63. ====

For the Self Detailing mode,
xref:self-detailing-1-0-sites-settings[the URL of a site] is used
for collecting statistics.

|Link Field |[.apiobject]#clm__LinkField__c# |Text(255)
a|
The field API name of the xref:clm-activity[Activity] object for
the invite link storing, for example,
[.apiobject]#RDLink__c#.

If specified, the same value will be used for all profiles.

The field to store an invitation link should have the same API name on
any [.object]#Activity# object for the *Remote
Detailing* or *Self Detailing* session.

|Login URL |[.apiobject]#clm__LoginURL__c# |Text |The
URL of the current Salesforce instance and
https://help.salesforce.com/articleView?id=networks_enable.htm&type=5[unique
URL(s) for a community], e.g.,
[.apiobject]#https://COMMUNITY_URL.cs129.force.com/#
(separated by a comma, without blank spaces).

|Remote Detailing Enabled
|[.apiobject]#clm__IsRDEnabled__c# |Checkbox |If
enabled, the Remote Detailing functionality is allowed, and an
invitation link will be generated on the *Activity* record.

|Session timeout (in seconds)
|[.apiobject]#clm__SessionTimeout__c# |Number(18, 0)
|The time interval during which a participant does not perform any
action. When the time interval is reached, the session expires. The
participant will be logged out, and their statistics will be sent to
Salesforce.

|Subdomain Name |[.apiobject]#clm_SubdomainName_c#
|Text(255) |Stores the subdomain name, if the
xref:ct-mobile-control-panel-presenter#h3_298754890[Custom
Subdomain
Enabled]/xref:ct-mobile-control-panel-remote-detailing-new#h3_1243606343[Custom
Domain] option is enabled.

|Text Chat Enabled
|[.apiobject]#clm__IsRDChatEnabled__c# |Checkbox |If
enabled, the participants of the Remote Detailing session can interact
in the chat on the CLM-presentation screen.

|Text Chat History Enabled
|[.apiobject]#clm__IsRDChatLogEnabled__c# |Checkbox |If
enabled, the chat history will be saved as the *Attachment* record with
the[.apiobject]#.html# file and linked to the selected
*Activity* record.

|Video Streaming
|[.apiobject]#clm__IsRDVideoStreamingEnabled__c#
|Checkbox |If enabled, the participants of the Remote Detailing session
can stream video and audio. The presenter has the ability to
enable/disable audio and video streaming per participant.
|===
