= Next Activity Management

The representative can transfer data, for example,
link:admin-guide/objectives-management/objective-creating#h2__1099816968[goals and notes], from the
finished _CT CPG Activity_ record to the next _CT CPG Activity_ record
related to the same _Account_ and/or _Contact_ record.



Follow the guidelines to use the _Next Activity_ functionality:

. Think about the data you need to transfer to the next _CT CPG
Activity_:
* transfer data on the regular basis;
* transfer data once.
. link:enable-the-next-activity-functionality[Enable the Next
Activity functionality].
. link:create-a-new-record-of-next-call-settings[Create the _Next
Call Settings_ record] with the fields and values,
and link:creating-the-next-activity#h2__1206305986[a new _CT CPG
Activity_ record] to transfer if you need to transfer data on the
regular basis.[#ebm]##
. link:creating-the-next-activity#ActivityReport:Visit-NextCallDate[Create
a new CT CPG Activity record] with the populated *Next Call Date* field
with the required data to transfer data once.
