= Order Change Manager: JSON Examples and Keys

During synchronization, the CT Mobile app sends package(s) with a JSON
file that stores information about the particular order that the user
was working with on the mobile device to the Salesforce database.

Check out the JSON keys and examples.

:toc: :toclevels: 3

[[h2_1406500097]]
=== Examples

Depending on whether an[.object]#Order# was created, edited, or
deleted on a mobile device, JSON can store the temporary ID or the
Salesforce record ID for this *Order* record or its related records,
such as[.object]#Order Line Item#,[.object]#Delivery
Line Item#, or[.object]#Delivery#.



In this JSON file, the *Order* and *Order Line Item* records have the
mobile temporary ID in the [.apiobject]#referenceOrderId# and
[.apiobject]#referenceId# keys, which means that these records
were created on the mobile device and will be inserted into the
Salesforce database after synchronization. The
xref:admin-guide/managing-ct-orders/order-change-manager/order-change-manager-field-reference[Order Change Manager]
record will be created for this[.object]#Order#.





In this example, the *Order* record already has the Salesforce record ID
in both[.apiobject]#referenceOrderId# and
[.apiobject]#referenceId# keys, which means that the Order has
been created before in Salesforce or CT Mobile app and was updated on
the mobile device.

Also, the Order Line Item record has the mobile temporary ID, which
means that it was created on the mobile device. The *Order Change
Manager* record will be created for this [.object]#Order#, and
the previously created *Order Change Manager* record for this Order will
be deleted.



[[h2_469009993]]
=== JSON Key Description

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#isLastPackage# |Boolean |Yes a|
Available values:

*[.apiobject]#true#, if all data for the order is stored in
that package or if this package is the last one for the order.
* false

|[.apiobject]#referenceOrderId# |String |No |A key stores
the mobile temporary Id or Salesforce Id of the current *Order*
record. For the *Order* record, the same value is stored in
the [.apiobject]#referenceOrderId# and [.apiobject]#referenceId# keys.

|[.apiobject]#records# |Array |Yes |A key stores the
collection of the *Order* record and all related records.

|[.apiobject]#attributes# |Array |Yes |A key contains data
of a particular record, such as[.object]#Order#,
[.object]#Order Line Item#,[.object]#Delivery Line
Item#,[.object]#Delivery#, or[.object]#Calculated
Discount#.

|[.apiobject]#type# |Enum |Yes |A key stores the object
API name, which data must be transferred.

|[.apiobject]#referenceId# |String |Yes |A key stores the
mobile temporary Id or Salesforce Id of the record of the object
specified in the [.apiobject]#type# key.

|[.apiobject]#Id# |String |Yes |A key stores Salesforce
ID for the record. The key is not specified for a new record.

|[.apiobject]#orders__AccounId__c#,
[.apiobject]#orders__OrderType__c#, etc. |String
|No a|
The key is the API name of the field of the current record. The current
record is defined by the values in the [.apiobject]#type#,
[.apiobject]#referenceId#, and[.apiobject]#Id# keys.

* In case of a new record (the [.apiobject]#Id# key is empty),
all fields with the [.apiobject]#creatable = true# attribute.
* In case of a modified record (the [.apiobject]#Id# key is
set), all fields with the [.apiobject]#creatable = true# and
[.apiobject]#editable = true# attributes, including the empty
fields.

|===


