With additional configuration, CT Vision IR can work with a custom
object that will have a *CT Vision* button to take photos, and the
photos taken will be linked to that object to work on the *Feedback
Loop* page. Visit records are still created for the selected Activity
object.

* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h2__335662800[CT
Mobile Customization]
* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h3_395000743[System
Label]
* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h3__601076877[Activity
Lookup]
* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h2_1769605814[CT
Vision Setup]
* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h3__1047703678[CTM
Settings: Visit Vision]
* link:configuring-ct-vision-to-work-with-a-custom-activity-object.html#h3__706735509[Feedback
Loop: Custom Filters]

[[h2__335662800]]
== CT Mobile Customization 

Check that the Activity object is specified on the
https://help.customertimes.com/articles/ct-mobile-ios-en/ct-mobile-control-panel-calendar/a/h3_1397263211[CT
Mobile Control Panel: Calendar] tab.

[[h3_395000743]]
=== System Label 

Create the MobileId__c field on the desired object, for
example, CustomMeeting__c, in order to identify whether a record has
been created on a mobile device or in Salesforce. The photo taken on a
mobile device will be attached only to the records with the specified
Mobile Id.



For more information, go to
the https://help.customertimes.com/articles/ct-mobile-ios-en/system-label[System
Label] article.

[[h3__601076877]]
=== Activity Lookup 

Create a field with the *Lookup* type, for example, ActivityId__c, on
the CustomMeeting__c object to link it with the _Activity_ specified on
the https://help.customertimes.com/articles/ct-mobile-ios-en/ct-mobile-control-panel-calendar/a/h3_1397263211[CT
Mobile Control Panel: Calendar] tab. 

[[h2_1769605814]]
== CT Vision Setup 

[[h3__1047703678]]
=== CTM Settings: Visit Vision 

Specify the desired object as the Activity object to display the *CT
Vision* button and take photos for recognition:

1.  Go to the *CTM Settings* tab and click *New*.
2.  Select the __Vision Visit __record type and click *Next*. 
3.  Fill out all fields and add the API name of the desired object, for
example, CustomMeeting__c, in the *Vision Object* field.
The full description of the fields is
available link:vision-visit-field-reference.html[here].
4.  Click *Save*.

The setup is complete.

[[h3__706735509]]
=== Feedback Loop: Custom Filters 

To have the ability to filter records of the custom object on the
*Feedback Loop* page and set up the order of its records:

1.  Go to the *CT Vision Setup* tab → *Feedback Loop* → *Custom
Filters*.
2.  Select the custom object, for example, CustomMeeting__c.
3.  In the SOQL builder, specify the desired criteria.
You can set up filters based on field of the parent and child objects.
4.  Click *Save*.

The setup is complete. Photos on the *Feedback Loop* page will be
automatically sorted according to the specified criteria.
