= Manage Currencies

Use one or more currencies in the CT Mobile app.

[[h2_1313381761]]
=== Single Currency 

By default, Salesforce organizations use a single currency. To set a
currency:

. Go to *Setup → Company Settings → Company Information*.
. Click *Edit*.
. Select the required currency in the *Currency Locale* picklist.
. Click *Save*.

The setup Is complete. After setting the currency locale all currency
values are displayed in the selected currency on the records of the
custom related lists, layouts, and mini-layouts.

[[h2_440549015]]
=== Multi-Currency 

https://help.salesforce.com/articleView?id=sf.admin_enable_multicurrency.htm&type=5[Enable
multiple currencies] to have the ability to manage the record currency:

[NOTE] ==== Get familiar with
https://help.salesforce.com/articleView?id=sf.admin_enable_multicurrency_implications.htm&type=5[the
Salesforce considerations]. ====

. Go to *Setup → Company Settings → Company Information*.
. Click *Edit*.
. Select the *Activate Multiple Currencies* checkbox.
. Click *Save*.

The setup is complete.

* The selected currency is displayed in the
https://developer.salesforce.com/docs/atlas.en-us.object_reference.meta/object_reference/sforce_api_objects_currencytype.htm[Currency
ISO Code] field as a three-letter code.
* After typing in the value, the currency selected as default will be
displayed.



If there are several active and available currencies for the mobile
user, add the *Currency ISO Code* field on the mini-layout to have the
ability to select the desired currency. Otherwise, the default currency
from the *Currency ISO Code* field of a *User* record will be added.



The currency code will be displayed on the layout, mini-layout, and in
the custom related list.

* When currencies differ in the *Currency ISO Code* field of an open
record and the _User_ record:
** The value will be displayed according to the *Currency ISO Code*
field of the record;
** The value from the *Currency ISO Code field* of the *User* record
will be displayed in the parentheses according to the rate from
https://help.salesforce.com/articleView?id=sf.editing_conversion_rates.htm&type=5[Conversion
Rates].
* Otherwise, the value will be displayed only according to the *Currency
ISO Code* field of the record.
