= Reference Object

In the CT Mobile package, administrators can specify the
[.object]#Reference# object according to the business goals.



To set up the[.object]#Reference# object:

. Go to the link:android/ct-mobile-control-panel-general#h3_494016929[CT
Mobile Control Panel: General] tab.
. In the *Reference Object API Name* field, select the desired object.
. Click *Save*.

The setup is complete. After the full synchronization, the setting is
applied.



As the[.object]#Reference# object, use the junction object
between the[.object]#Account# and[.object]#Contact#
objects.
[NOTE] ==== In the case of the incorrect object in the
*Reference Object API Name* field, the field is considered empty. ====

* the standard[.object]#Account Contact Relationship# object

[TIP] ==== To use this object, users should have the ability to
relate a contact to multiple records. For more information, refer to
https://help.salesforce.com/s/articleView?id=sf.shared_contacts_set_up.htm&type=5[Set
Up Contacts to Multiple Accounts]. ====
* When using the CT Pharma solution as the target system,
[.apiobject]#CTPHARMA__Reference__c#
* Any custom object with the field of the lookup type to the
[.object]#Account# and[.object]#Contact# objects


