= About CT Presenter

The *CT Presenter* is intended to create CLM presentations for
demonstrating them offline and online on the PC, tablets, and mobile
phones.

:toc: :toclevels: 3

[[h2_1251281241]]
=== Required Permissions

To use the CT Presenter functionality:

. Go to *Setup → Security → Remote Site Settings* and make sure that the
*CTCLM* and *CTCLMEditor* remote sites are active.

//tag::ios,win[]

If you want to use xref:migration-to-remote-detailing-2-0[Remote
Detailing 2.0], install the
xref:ios/news/ct-mobile-package-release-notes/index.adoc#h2_1028401963[CT Mobile
package v. 3.63] or higher and make sure that the *CTCLMRD* remote site
is active.
. Go to *Setup → Custom Code → Custom Settings → Trigger Settings* →
make sure that the following records are created and active:
*[.apiobject]#ApplicationProcess#
*[.apiobject]#AttachmentProcess#
*[.apiobject]#SlideProcess#
*[.apiobject]#TemplateProcess#
*[.apiobject]#WidgetProcess#
. Go to xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-tools/index.adoc#h3_2011978[CT Mobile
Control Panel:
Tools]/xref:ct-mobile-control-panel-tools-new#h2_2011978[CT Mobile
Control Panel 2.0: Tools] and check the cloud token is specified.
. Assign xref:ios/getting-started/application-permission-settings.adoc#h3_2115044027[the
preconfigured permission set] to a user according to their role.
. Check xref:user-permissions[user permissions] to CLM objects.
. Get familiar with xref:requirements-and-media-file-formats[the
requirements for CLM presentations].

[[h2_2019207216]]
=== CLM Presentation Creation

//tag::ios[]

Look through
xref:../Storage/project-ct-mobile-en/PDF/Creating-Interactive-CLM-Presentations-for-iOS-(en).pdf[our
guide] for creating interactive CLM Presentations to know how to add
content, such as media and specific interactions, on slides and properly
upload ready CLM presentations to Salesforce.

//tag::win[]

Look through
xref:../Storage/project-ct-mobile-en/PDF/Creating-Interactive-CLM-Presentations-for-Windows-(en).pdf[our
guide] for creating interactive CLM Presentations to know how to add
content, such as media and specific interactions, on slides and properly
upload ready CLM presentations to Salesforce.

CT Presenter provides the xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-application-record-type/index.adoc[Application
Editor]:

* Manually create CLM presentations using one of the options:
** Add slides based on templates with placeholders and widgets;
** Add slides with the specified markup.
* Add xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-application-record-type/automatic-creating-clm-presentation.adoc[PowerPoint],
xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-application-record-type/automatic-creating-clm-presentation.adoc[PDF], or
xref:creating-clm-presentation-from-jpeg-jpg[JPEG/JPG] files to
convert into a CLM presentation.



CT Presenter provides the xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-plain-application-record-type/index.adoc[Plain
Application Editor]:

* Create and edit CLM presentations
xref:ios/ct-presenter/creating-clm-presentation/creating-clm-presentation-with-the-plain-application-record-type/creating-plain-clm-presentation.adoc[using the web interface].
* xref:creating-plain-clm-presentation-using-templates[Create your
templates], and slides with images, texts, videos, etc.
* xref:creating-plain-clm-presentation-from-powerpoint[Import
PowerPoint] into an existing template and convert it to a CLM
presentation.



Use xref:custom-scenario-editor[the custom scenario editor] to
create, edit and delete custom scenarios.

//tag::ios,win[]

In the CT Mobile app, you can
specify xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-customscenario.adoc[custom scenarios] with the help of
the xref:ios/mobile-application/mobile-application-modules/applications/index.adoc#h3_1236408094[Mobile Scenario Editor] in the
Application module.

[[h2_1250107167]]
=== Publication of CLM Presentations

To use a CLM presentation, it is necessary to publish it:

* xref:publishing-clm-presentations#h3_1098755975[Renew slides] of
the current CLM presentation to view slides in the navigation feed
during the display of the CLM presentation.
* Publish a CLM presentation by selecting it
xref:publishing-clm-presentations#h2_1149854286[on the Applications
tab].
* Publish a CLM presentation by using
xref:publishing-clm-presentations#h2_104022594[the Application
Editor].

[[h2_1781171346]]
=== Displaying and Management of CLM Presentations

//tag::ios[]It is possible
to xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/mobile-application-setup.adoc#CLMDisplayMode[specify the CLM
presentation display mode] in the case of using Аngular and other JS
frameworks, where there are difficulties with the display of connected
templates and parts of the HTML code.

[[h3_1603252651]]
==== CT Mobile app (offline mode)

During the synchronization process, CLM presentations will be downloaded
on the mobile device and available for use:

* The xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[CLM presentation] should be active and
available offline.
[NOTE] ==== The *Available Offline* attribute is available since
the CT Mobile managed package v. 3.54. The administrator should activate
this checkbox for the required CLM presentations. ====
* xref:ios/mobile-application/mobile-application-modules/applications/index.adoc[The Application module] allows reviewing CLM
presentations uploaded from Salesforce.
* You can configure xref:ios/admin-guide/mobile-layouts/index.adoc-applications[the mobile
layout] of the __[.object]#Activity# object to launch a CLM
presentation from the carousel of CLM presentations on the activity
record.
* Also, you can launch a CLM presentation from the
xref:ios/mobile-application/ui/home-screen/index.adoc[Home Screen].



For each CLM presentation:

* Use pre-configured xref:ios/mobile-application/mobile-application-modules/applications/gestures-in-clm-presentations.adoc[gestures].
* Double-tap the left or right side of the screen to view the
xref:ios/mobile-application/mobile-application-modules/applications/clm-presentation-controls.adoc[control buttons].
* Double-tap the bottom of the screen to display the selected scenario
and slide in xref:ios/ct-presenter/clm-navigation-in-clm-presentations.adoc[a branch] for
rapid switching between the slides.
* xref:ios/ct-presenter/js-bridge-api/index.adoc[JS Bridge methods] are available from within
the CLM presentation if specified on the slide markup.
* During the CLM presentation, specific user actions are captured and
collected in the xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-applicationstats.adoc[Application Stats]
record. Tracking button clicks, likes, dislikes, slide duration, and
slide navigation are specified for each CLM presentation. The statistics
will be linked to the activity record from which it was started. The CT
Mobile app asks a user to link the statistics to the activity record if
the CLM presentation was launched from the Application module or Home
screen.

//tag::ios,win[]

[[h3_1972006392]]
==== The Remote Detailing Functionality (online mode)

[TIP] ==== We recommend reading
xref:ios/ct-presenter/the-remote-detailing-functionality/remote-detailing-f-a-q.adoc[Remote Detailing: F.A.Q]. ====

The xref:ios/ct-presenter/the-remote-detailing-functionality/index.adoc[Remote Detailing]
functionality allows the presenter and participants to simultaneously
view CLM presentations on their PC, tablet, or mobile phone. The *Self
Detailing* mode is intended for the participant's remote control of the
CLM presentation on a PC, tablet, or mobile phone without presenter
participation.

* The xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[CLM presentation] should be active and
available for *Remote Detailing*.
* The presenter can launch a CLM presentation
xref:remote-detailing-launch-the-ct-mobile-app[for Remote Detailing
on the Activity record in the CT Mobile app].
* The presenter can launch a CLM presentation
xref:remote-detailing-launch-salesforce-side[for Remote Detailing
on the Activity record or the Application record in Salesforce].
* The presenter can launch a CLM presentation
xref:remote-detailing-launch-microsoft-teams[via Microsoft Teams].
* Participant(s) join the *Remote Detailing* meeting by the invite link.



For each CLM presentation:

* The separates UI for the presenter and participant.
* In the case of using on-the-slide markup,
xref:ios/ct-presenter/the-remote-detailing-functionality/remote-detailing-f-a-q.adoc[]JS methods and links are available
from within the CLM presentation.
* Performed on the CLM presentation, specific user actions can be
captured and collected in the *Application Stats* record. These actions
can include capturing button clicks, certain gestures (clickstream
data), or generic data and should be specified for each CLM
presentation.
** When the presenter clicks the *Finish session* button or closes the
browser tab, a record of the [.object]#Application Stats# object
is created for each participant and presenter.
** For the *Self Detailing* mode, the statistics will be collected
according to xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/clm-settings.adoc[the Session timeout (in seconds)
field].
