= Activity Report Management

link:activity-report-management[Activity Reports] display all
information about the particular _CT CPG Activity_ record in one place.



Follow the guidelines to customize an _Activity Report_ page for each
_CT CPG Activity_ record type
link:work-with-the-activity-report-page[for further work].



[width="100%",cols="20%,20%,20%,20%,20%",]
|===
|*New Record Type* |*Visit* |*Event* |*Time Off* |*Joint Visit*

a|
Specify the record type according to your needs:

* link:manage-field-sets-for-activity-report-pages#h2_2045948811[create
a new record type] for the[.object]#CT CPG Activity# object;
* link:manage-field-sets-for-activity-report-pages#h2__1946781807[create
a new field set] to manage the activity details;
* edit the *Activities List* field set to view the representative's
activities;
* create and
verify link:manage-field-sets-for-activity-report-pages#h2_1877288261[corresponding _Activity
Layout Settings_ records] to add the field set to the _Activity Report_
page;
* create and
manage link:create-a-new-filter-for-the-activities-list[filters] to
display only matched representative's activities;
* define related tabs on the Activity Report page, for example,
link:configure-ct-product-tabs[CT Product tabs];
* link:override-basic-actions-for-activity[override basic actions
behavior] to manage activities on the configured _Activity Report_ page.

a|
This type is intended for the representative's visits to point-of-sales:

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit]
the *Visit* field set;
* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Activities
List* field set to view the representative's activities;
* verify link:manage-field-sets-for-activity-report-pages#h2_1877288261[corresponding _Activity
Layout Settings_ records];

* create and
manage link:create-a-new-filter-for-the-activities-list[filters] to
display only matched representative's activities;
* configure the link:configure-ct-product-tabs[CT Product tabs] to
track products;
* configure the link:configure-an-inventory-tab[Inventory tab] to
monitor the rental equipment status for the client;
* configure the link:configure-a-special-trackings-tab[Special
Tracking tab] to track the company goals;
* link:override-basic-actions-for-activity[override basic actions
behavior] to manage activities on the configured _Activity Report_ page.

a|
This type is intended for hosting and participating in events:

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Event* field
set;

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit]  the *Activities
List* field set to view the representative's activities;
* verify link:manage-field-sets-for-activity-report-pages#h2_1877288261[corresponding _Activity
Layout Settings_ records];
* Create and
manage link:create-a-new-filter-for-the-activities-list[filters] to
display only matched representative's activities;
* configure the link:configure-an-event-member-tab[Event
Member__ __tab] to add or remove event participants;
* configure the link:configure-an-expenses-tab[Expenses tab] to
track the promo materials and other required event items;
* link:override-basic-actions-for-activity[override basic actions
behavior] to manage activities on the configured _Activity Report_ page.

a|
This type is intended to manage the representative's vacations and
holidays:

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Time
Off* field set;

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Activities
List* field set to view the representative's activities;
* verify link:manage-field-sets-for-activity-report-pages#h2_1877288261[corresponding _Activity
Layout Settings_ records];
* create and
manage link:create-a-new-filter-for-the-activities-list[filters] to
display only matched representative's activities;
* link:override-basic-actions-for-activity[override basic actions
behavior] to manage activities on the configured _Activity Report_ page.

a|
This type is intended for managers who can estimate the representative's
skills within a joint visit to point of sales:

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Joint
Visit* field set;

* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit]  the *Activities
List* field set to view the representative's activities;
* link:manage-field-sets-for-activity-report-pages#h2_1639795417[edit] the *Joint
User Activities* field set to view the representative's activities that
can be related to the _Joint Visit_ record; 
* verify link:manage-field-sets-for-activity-report-pages#h2_1877288261[corresponding _Activity
Layout Settings_ records];

* create and
manage link:create-a-new-filter-for-the-activities-list[filters] to
display only matched representative's activities;
* configure link:configure-a-report-template[the _Report
Template_ records] to estimate the representative's skills by selecting
the required _Report_ during the _Joint Visit_;
* link:override-basic-actions-for-activity[override basic actions
behavior] to manage activities on the configured _Activity Report_ page.

|===


