= Pharma Calendar Management

In this section:

* Get familiar with
the xref:calendar-interface-and-activities[Pharma Calendar
interface and activities management].
* Learn about xref:pharma-calendar-settings[Pharma Calendar
settings].
* Check the xref:custom-permissions-for-using-calendar[required
permissions and field names rules] for using Pharma Calendar.
* Learn
about xref:custom-labels-for-translating-the-calendar-interface[custom
labels for translating the Pharma Calendar interface].
* Read field description for
the xref:new-calendar-settings-field-reference[Planning Calendar
Settings]https://help.customertimes.com/articles/project-ct-cpg/skill-mark-field-reference[ ]object.
* Learn about the xref:calendar-management[Legacy Calendar].

[WARNING] ==== The Pharma Calendar functionality is fully
available for the Google Chrome web browser. Other web browsers are not
yet supported. ====

[WARNING] ==== For the stable work of the Pharma Calendar, go
to *Setup* → *Session Setting* and select the *Lightning Web
Security* checkbox.  ====
