= Managing CT Mobile Licenses

The administrator can grant or restrict access to users who can use the CT Mobile package functionality by managing licenses.

[[h2_1491098279]]
== Grant Access to Users

To select users who can use the CT Mobile package functionality:

. Go to *Setup → Apps → Installed Packages*.
. Click *Manage Licenses* next to *CT Mobile*.
. Click the *Add Users* button.
+
The *Add Users* page opens.
. Select users from the *Available Users* list.
. Click *Add*.
+
Also, you can click *Add All Users* if you want to grant access to all users.

Selected users appear in the list of users who have access to the CT Mobile package.

[[h2_1361513113]]
== Restrict Access to Users

To restrict access to the user(s):

. Go to *Setup → Apps → Installed Packages*.
. Click *Manage Licenses* next to *CT Mobile*.
. Click *Remove Multiple Users*.
+
Also, you can remove a single user by clicking *Remove* next to the user's *Full Name*.
. Select users from the *Available Users* list.
. Click *Remove*.
Also, you can click *Remove All Users* if you want to restrict access to the package for all users.

The user(s) are removed from the list of users who have access to the CT Mobile package.
