= Create a new Record of the Marketing Detail Tracking

With the help of the [.object]#Marketing Detail Tracking# object:

TIP: Read the description of the available record types xref:admin-guide/targeting-and-marketing-cycles-management/index.adoc[here].

* Track the number of planned calls for the target _Account_ and _Contact_ records.
* xref:admin-guide/ct-products-and-assortments-management/index.adoc[Track specific products and assortments] for the target _Account_ and _Contact_ records:
** the _CT Product_ and _Assortment_ records should be active;
** the *Start Date* of the _Assortment_ should be within the _Marketing Cycle_ period.
* Track tasks and objectives for the target _Account_ and _Contact_ records.

[[h2_726145408]]
== Create a Marketing Detail Tracking record

Create a new _Marketing Detail Tracking_ record:

. Go to the *Marketing Cycles* tab and click the required marketing cycle.
. On the *Marketing Detail Tracking* related list, click *New*.
. Select the record type:
* Call Rate;
* Company Product Tracking;
* Competitor Product Tracking;
* POS Material;
* Special Tracking.
. Click *Next*.
. According to the selected record type, fill the required fields up.
+
TIP: Read the description of each parameter xref:./ref-guide/marketing-detail-tracking-field-reference.adoc[here].

* Specify *the division category*;
* Specify *the type*.
* Specify the related *Assortment* or *CT Product*.
. Click *Save*.

The new *Marketing Detail Tracking* is created for the selected _Marketing Cycle_ record.
