= Creating Target Frequency Records

The[.object]#Target Frequency# object is intended to store and
track the number of activities to the target _Account_ or _Contact_
record within xref:admin-guide/configuring-targeting-and-marketing-cycles/create-a-marketing-cycle[the active and given
marketing cycle].

The xref:target-frequency-process[TargetFrequencyProcess] trigger
automatically creates active _Target Frequency_ records when
the _Account_ or Contact records xref:admin-guide/configuring-targeting-and-marketing-cycles/create-targeting-lists[are
added to the targeting list].

The _Target Frequency_ record contains the following information:

* *Planned Calls* is the number of how many _Activities_ with
the _Visit_** **record type should be done for the
target _Account_ or _Contact_ record within the marketing cycle.

The planned calls and category of the _Target Frequency_ record can be
automatically filled out with the *Planned Calls* and *Category* values
from the xref:marketing-detail-tracking-field-reference[Marketing
Detail Tracking] record of
the xref:targeting-and-marketing-cycle-management#h3_2015528788[Call
Rate] record type if:
** ​the _Account_ or _Contact_ record is in the targeting list;
** the _Call_ __Rate __record is assigned for the same division category
that is specified for the _Account_ or __Contact __record.

If the matched _Call Rate_ record is not created, the *Planned Calls*
and *Category* fields of the _Target Frequency_ record left blank.
* *Actual Calls* is the number of activities already done.
* *Last Call Date* will be automatically filled out with the date of the
last _Activity_ record for the corresponding _Account_ and _Contact_.
* *Deactivation Date/Time* will be automatically filled out when the
current marketing cycle will be deactivated for the
corresponding _Account_ and _Contact_.
* The *Marketing Cycle* field will be automatically filled out with the
corresponding _Marketing Cycle_ record.
