= Salesforce Winter '21 Release

Due to link:https://help.salesforce.com/articleView?id=release-notes.getstart_browsers_sfx.htm&type=5&release=228[Salesforce does not support] the Private Browsing mode (Incognito) in Lightning Experience, do not use this mode in any browser when working with the following:

* xref:admin-guide/activity-report-management/index.adoc[Activity Report]
* xref:admin-guide/calendar-management/legacy-calendar-management/index.adoc[Calendar]
* xref:admin-guide/change-request-management/index.adoc[Change Request]
* xref:admin-guide/quizzes-management/index.adoc[Quizzes]
* xref:admin-guide/activity-report-management/ref-guide/report-template-field-reference.adoc[Template Editor]
* Related Lists
* Buttons
** xref:admin-guide/targeting-and-marketing-cycles-management/add-the-manage-targets-button.adoc[Mass Managing (Account or Contact) Targets]
** xref:admin-guide/activity-report-management/work-with-the-activity-report-page.adoc#h3_1878806894[Add Selected to Event]

Otherwise, set up third-party cookies to use the CT Mobile package features in Lightning Experience via the incognito mode. For example, if you are using Google Chrome, follow the instructions link:https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Callow-or-block-cookies[here].


