= Salesforce Winter&#39; 21 Release

Due
to https://help.salesforce.com/articleView?id=release-notes.getstart_browsers_sfx.htm&type=5&release=228[Salesforce
does not support] the Private Browsing mode (Incognito) in Lightning
Experience, do not use this mode in any browser when working with the
following:

* link:activity-report-management[Activity Report]
* link:calendar-management[Calendar]
* link:/articles/project-ct-cpg/change-requests-management[Change
Request]
* link:ct-cpg-quizzes-management[Quizzes]
* link:report-template-field-reference[Template Editor]
* Related Lists

* Buttons
** link:add-the-manage-targets-button[Mass Managing (Account or
Contact) Targets]
** link:work-with-the-activity-report-page#h3_1878806894[Add
Selected to Event]



Otherwise, set up third-party cookies to use the CT Mobile package
features in Lightning Experience via the incognito mode. For example, if
you are using Google Chrome, follow the
instructions https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Callow-or-block-cookies[here].


