= Salesforce Winter '21 Release

Due
to https://help.salesforce.com/articleView?id=release-notes.getstart_browsers_sfx.htm&type=5&release=228[Salesforce
does not support] the Private Browsing mode (Incognito) in Lightning
Experience, do not use this mode in any browser when working with the
following:

* xref:admin-guide/activity-report-management/index.adoc[Activity Report]
* xref:calendar-management[Calendar]
* xref:admin-guide/change-request-management/index.adoc[Change
Request]
* xref:admin-guide/quizzes-management/index.adoc[Quizzes]
* xref:report-template-field-reference[Template Editor]
* Related Lists

* Buttons
** xref:add-the-manage-targets-button[Mass Managing (Account or
Contact) Targets]
** xref:work-with-the-activity-report-page#h3_1878806894[Add
Selected to Event]



Otherwise, set up third-party cookies to use the CT Mobile package
features in Lightning Experience via the incognito mode. For example, if
you are using Google Chrome, follow the
instructions https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Callow-or-block-cookies[here].


