= AccountProcess

_AccountProcess_ is intended to display the _Account_ hierarchy
xref:admin-guide/calendar-management/legacy-calendar-management/calendar-interface#h2__1884555900[on the _Calendar_ tab] and
xref:admin-guide/targeting-and-marketing-cycles-management/create-targeting-lists[manage target _Account_ records].

'''''

API name in Salesforce: AccountProcess

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Context* |*Method* |*Codename* |*Description*

|after insert[ai]  |manageHierarchy() |manageHr |Analyze
if the _Account_ record has child _Account_ records and, if so, update
the CTCPG__HasChildAccounts__c field on this _Account_ record.

|after update[au]  |manageTargetFrequency()  |manageTF a|
In case of changes in
the xref:division-target-frequency-settings[Division Target
Frequency Settings] record for the__ User__ division:

* create a new _Target Frequency_ record related to the
specific _Account_ record for the current user;
** if the __Target Frequency __record already exists, this record will
be deactivated and its CTCPG__DeactivationDateTime__c field will
be populated with the deactivation date;
* update the CTCPG__TargetUserIds__c field on
this _Account_ record.

| |manageHierarchy()  |managehR a|
Analyze if the _Account_ record has child __Account __records and, if
so, update the CTCPG__HasChildAccounts__c field on
this __Account __record.

|before insert[bi] | | |Reserved.

|before update[bu] | | |Reserved.
|===


