= ProductProcess

The _ProductProcess_ trigger is responsible for recalculating xref:admin-guide/cpg-groups-management/ref-guide/index.adoc[CPG Groups] of xref:admin-guide/ct-products-and-assortments-management/index.adoc[CT Products].

'''''

API name: [.apiobject]#ProductProcess#

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Context* |*Method* |*Codename* |*Description*

|[.apiobject]#after insert[au]#  |[.apiobject]#calculateGroupMembers()# |[.apiobject]#gm# a|
Verify that the created record of the [.apiobject]#CTCPG\__Product__с# object is matched the conditions of the existing _CPG Group_ records.

If found, a _CPG Group Member_ record is created for this particular record and the corresponding _CPG Group_.

|[.apiobject]#after update[au]#  |[.apiobject]#calculateGroupMembers()# |gm a|
Verify that the updated record of the  [.apiobject]#CTCPG\__Product__с# object is matched the conditions of the existing _CPG Group_ records.

If found, a _CPG Group Member_ record is created for this particular record and the corresponding _CPG Group_.

|[.apiobject]#after undelete [aud]#
|[.apiobject]#calculateGroupMembers()# |[.apiobject]#gm# a|
Verify that the restored record of the [.apiobject]#CTCPG\__Product__с# object is matched the conditions of the existing _CPG Group_ records.



If found, a _CPG Group Member_ record is created for this particular record and the corresponding _CPG Group_.

|[.apiobject]#before delete[bd]#  |[.apiobject]#deleteteGroupMembers()# |[.apiobject]#gm# |Search and delete the _CPG Group Members_ records of [.apiobject]#CTCPG\__Product__с# object that are being deleted.
|===


