= TargetFrequencyProcess

*TargetFrequencyProcess* is intended to
 xref:admin-guide/targeting-and-marketing-cycles-management/index[manage _Target
Frequency_ records].

'''''

API name in Salesforce: TargetFrequencyProcess

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Context* |*Method* |*Codename* |*Description*

|after insert[ai]  |concatenateUsersOnTarget() |conTarget
|If the CTCPG__EnableAdvancedTFLogic__c checkbox enabled on the
_ xref:application-settings.html[Application Settings]_ record,
 xref:admin-guide/targeting-and-marketing-cycles-management/add-a-new-division[the fields with division values] will be
updated on the related _Account_ and _Contact_ records.

| a|
cloneTargetFrequencyBySegment()



|cloneTF a|
If there is a _Marketing Cycle_ record that has no _Target Frequency_
record which met the following conditions:

* the _Target Frequency_ record is related to an _Account_ and/or
_Contact_ record;
* the _Target Frequency_ record is related to a _User_ record;
* the division value in the CTCPG__UserDivision__c field of the
_Target Frequency_ record is the same as for the related _User_ record.



Create the cloned _Target Frequency_ record linked to the _Marketing
Cycle_ record.

|after update[au]  |concatenateUsersOnTarget() |conTarget
|If the CTCPG__EnableAdvancedTFLogic__c checkbox enabled on
the _Application Settings_ record, the fields with division values will
be updated on the related _Account_ and _Contact_ records.

|after undelete[aud]   |concatenateUsersOnTarget()
|conTarget |If the CTCPG__EnableAdvancedTFLogic__c checkbox
enabled on the _ xref:application-settings.html[Application
Settings]_ record,  xref:admin-guide/targeting-and-marketing-cycles-management/add-a-new-division[the fields with division
values] will be updated on the related _Account_ and _Contact_ records. 

| | | |

|before insert[bi] |fillOwnerField()  |fillOwner |On
the _Target Frequency_ record, update
the CTCPG__OwnerId__c field if the owner of the record is
changed. 

| |fillDetailsField() |fillDetails a|
* Define the active _Marketing Cycle_ record to link the _Target
Frequency_ record. 

* Based on the found _Marketing Cycle_ record and the division category
of the _Account_ and _Contact_ records, define the related _Marketing
Detail Tracking_ record with the *Call Rate* record type to link
the _Target Frequency_ record.

* Based on the value in the found _Marketing Detail Tracking_ record,
update the CTCPG__PlannedCalls__c field on the linked _Target
Frequency_ record.

|before update[bd]  |fillOwnerField() |fillOwner |On
the _Target Frequency_ record, update
the CTCPG__OwnerId__c field if the owner of the record is
changed. 

|before delete[bd]  |concatenateUsersOnTarget() |conTarget
|If the CTCPG__EnableAdvancedTFLogic__c checkbox enabled on
the _ xref:application-settings.html[Application
Settings]_ record,  xref:admin-guide/targeting-and-marketing-cycles-management/add-a-new-division[the fields with division
values] will be updated on the
related _Account_ and _Contact_ records.
|===


