= CRM Data Display

If the CLM presentation is launched on the *Activity* record, it is
possible to display values from the records related to the *Activity*
record. You can create, insert, update, or delete CRM data.



The common use cases:

* CLM presentation personalization.
* ​Create[.object]#Activity Data# for[.object]#Order
Taking# or[.object]#Stock-Taking#.
* Create contacts on a slide.
* Displaying of required data using markers in the
[.apiobject]#{!Object.Field}# format.



The label markups should be in the
[.apiobject]#{!CTPHARMA__Activity__c.Id}# format.

The following label must be placed in the slide markup, and the
JavaScript file connected to the slide had to refer to that variable.



For example, use the xref:android/knowledge-base/ct-presenter/js-bridge-api/methods-for-interaction-with-crm-data/ctm-query[ctm.query] method on the slide
markup to display the record of the parent object:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.query("SELECT id FROM Account WHERE id IN (SELECT AccountId__c FROM Activity__c WHERE id = '{!Activity__c.Id}'")
....

|===



Or you can display child records of the *Activity* record:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.query("SELECT id FROM CTPHARMA__ActivityData__c WHERE CTPHARMA__ActivityId__c = '{!CTPHARMA__Activity__c.Id}'")
....

|===


