= ctm.update

The method of xref:android/knowledge-base/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is
intended to bulk edit fields of offline objects if the current user has
permission to edit records of the appropriate object and access to
fields of that object.

[[h2_905713055]]
=== Query Format 

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.update([SObject], handler)
....

|===

[.apiobject]#SObject# is the JS object that indicates the API
name of the offline object, the ID of the record to update, and a list
of fields with values.

[[h2_441581376]]
=== Handler 

Use a handler function to describe the output format of the query
results, e.g., to display the results of operations or method errors for
debugging purposes.

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.update([{"SObject": "Account", "Id":"0011w00000VFNzC", "Name": "IBM"}])
....

|===



[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
var updateString = '[{"SObject":"Account", , "Id": "DSFS-2342-TYRE-ADSFBA374Q8RQ8", "Name":"Test Account"}]';

var updateObject = JSON.parse(updateString); 

ctm.update(updateObject, function(response){ 
    console.log('Update result', response); 
})
....

|===



The result:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
{
    "result": [
        {
            "Id": "0011w00000VFNzC",
            "Name": "IBM"
        }
    ],
    "success": true,
}
....

|===
