= ctm.query

The method of xref:android/knowledge-base/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is
intended to make requests to data tables and receive records by
criteria.

[[h2_905713055]]
=== Query Format 

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.query(string,handler)
....

|===



The [.apiobject]#string# is the required SOQL query.

[[h2_442663712]]
=== Handler 

Use a handler function to describe the output format of the query
results, e.g., to display the results of operations or method errors for
debugging purposes.

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.query('SELECT Id, Name FROM Account WHERE Name = "Google, Inc"')
....

|===



[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.query(query, function(response){ 
    console.log('Query result', response); 
})
....

|===



The result:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
{
    "result": [
        {
            "Id": "2233445566",
            "Name": "Sample Account"
        },
    ],
    "success": true,
    "rows": 1
}
....

|===
