= ctm.delete

The method of the xref:android/knowledge-base/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is
intended to bulk delete fields of records of offline objects:

* xref:android/quick-reference-guides/application-permission-settings.adoc[the user profile] should
have permission to delete records of the required object.
* xref:android/managing-offline-objects#h2_1534686659[permission to delete]
the required offline object is allowed.

[[h2_905713055]]
=== Query Format 

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.delete([SObject], handler)
....

|===



[.apiobject]#SObject# is the JS object that indicates the API
name of the offline object and the ID of the record to delete.

[[h2_442663712]]
=== Handler 

Use a handler function to describe the output format of the query
results, e.g., to display the results of operations or method errors for
debugging purposes.

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.delete([{"SObject": "Account", "Id":"a0y1w000000Ck4x"}])
....

|===



[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
var deleteString = '[{"SObject":"Account", "Id": "DSFS-2342-TYRE-ADSFBA374Q8RQ8"}]';

var deleteObject = JSON.parse(deleteString); 

ctm.delete(deleteObject, function(response){ 
    console.log('Delete result', response); 
})
....

|===



The result:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
{
    "result": [
        {
            "Id": "a0y1w000000Ck4x"
        }
    ],
    "success": true,
}
....

|===
