= Filters in Related Lists
:toc:

xref:ios/admin-guide/managing-offline-objects/index.adoc#h2_879469097[Set up a SOQL filter] for the related lists. The toggle in the CT Mobile allows a user to display all downloaded records or only records that matched the filter criteria.

[[h2_1316422583]]
== Standard Related Lists

[[h3_215298378]]
=== For users of CT Mobile iOS version 2.1 and earlier

The sorting order for link:https://help.salesforce.com/articleView?id=customizing_related_lists.htm&type=5[a standard related list] is stored in xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/related-list-filters.adoc[Related List Filters].

. If the *Order By* request is set in the [.apiobject]#clm\__SOQL__c# field:
* if the value is ASC or not set in the [.apiobject]#clm\__SortOrder__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__SortOrder__c# field, the sorting will be performed in descending order;
. If the *Order By* request is not set in the [.apiobject]#clm\__SOQL__c# field, the sorting will be performed according to the specified parameter in the *Sort by* field in the *Related List Properties* window on the layout of the corresponding record type of the parent object:
* if the value is ASC or not set in the [.apiobject]#clm\__SortOrder__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__SortOrder__c# field, the sorting will be performed in descending order;
. In other cases, the sorting is carried out by the first column.

[[h3_1827010273]]
=== For users of CT Mobile iOS version 2.2 and later

The sorting order for link:https://help.salesforce.com/articleView?id=customizing_related_lists.htm&type=5[a standard related list] is stored in the xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/ctm-settings-standard-related-list.adoc[Standard Related List] record type of the xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/index.adoc[CTM Settings] object.

. If the *Order By* request is set in the [.apiobject]#clm\__Criteria__c# field:
* if the value is ASC or not set in the [.apiobject]#clm\__SortingOrder__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__SortingOrder__c# field, the sorting will be performed in descending order;
. If the *Order By* request is not set in the [.apiobject]#clm\__Criteria__c# field, the sorting will be performed according to the specified parameter in the *Sort by* field in the *Related List Properties* window on the layout of the corresponding record type of the parent object:
* if the value is ASC or not set in the [.apiobject]#clm\__SortingOrder__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__SortingOrder__c# field, the sorting will be performed in descending order;
. In other cases, the sorting is carried out by the first column.

[[h2_1047667523]]
=== Custom Related Lists

The sorting order for xref:ios/admin-guide/related-lists/custom-related-lists.adoc[a custom related list] is stored in xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/mobile-custom-details-settings.adoc[Mobile Custom Details Settings].

. If the *Order By* request is set in the [.apiobject]#clm\__RecordCondition__c# field:
+
NOTE: If there is more than one field in the condition, the records are sorted by the first field. If the first field contains two identical values, the records are sorted by the second field, and so on.

* if the value is ASC or not set in the [.apiobject]#clm\__RecordCondition__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__RecordCondition__c# field, the sorting will be performed in descending order;
. If the *Order By* request is not set in the [.apiobject]#clm\__RecordCondition__c# field, the sorting will be performed according to the value in the [.apiobject]#clm\__SortingFieldName__c# field. Records are sorted in ascending order.
* if the value is ASC or not set in the [.apiobject]#clm\__RecordCondition__c# field, the sorting will be performed in ascending order;
* if the value is DESC in the [.apiobject]#clm\__RecordCondition__c# field, the sorting will be performed in descending order;
. In other cases, the sorting is carried out by the first column.

In the CT Mobile app, it is also possible to rearrange records in custom and standard related lists by tapping on the name of any displayed list column. On the second tap, the ascending and descending sorting order changes.
