= ctm.customStats

The method of xref:ios/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is intended to collect slide statistics after actions in native windows on a slide on various devices and CLM presentation components.

[[h2_905713055]]
== Query Format

[source,javascript]
----
ctm.customStats(slideName)
----

The [.apiobject]#slideName# line should be Latin, 40 characters max, and without blank spaces.

* Requesting this method, CT Mobile creates an _Application Stats_ record with the *Slide Stats* record type where it keeps records of view time, likes, displays, etc. until [.apiobject]#ctm.customStats# with a different [.apiobject]#slideName# is requested or the CLM presentation display mode is closed.
* The [.apiobject]#slideName# value will be stored xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-applicationstats.adoc[in the File Name field].
* If the method with the same [.apiobject]#slideName# is called again, CT Mobile must append the previously created _Application Stats_ record.

[[h2_442663712]]
== Handler

[source,javascript]
----
ctm.customStats(‘main_page’)
----

[source,javascript]
----
ctm.customStats('my_welcome_screen', function(response){
    console.log('Result', response);
})
----

The results:

[source,javascript]
----
{
    "success": true,
}
----