= System Label

A system label is a unique identifier of a record created on a mobile
device.

ifdef::ios[]

It helps to avoid duplicate records, or may be used as a criterion to
run additional client logic.

:toc: :toclevels: 3

[[h2_395000743]]
=== System Label

To write a unique identifier when a user creates or edits a record in
the CT Mobile app, create a custom[.apiobject]#MobileId__c#
field for the desired link:ios/managing-offline-objects[offline
objects].



The operation name:

* *update*: updating a record;
* *create*: creating a record.

The identifier name:

ifdef::ios[]

*uniqID*: a unique internal identifier of a record that remains
unchanged regardless of how many devices the record has been modified
on.

ifdef::win[]

*ObjectType-UUID*: a unique internal identifier of a record that remains
unchanged regardless of how many devices the record has been modified
on.



ifdef::ios[]

[cols="^,^",]
|===
|*CT Mobile Release* |*Value*
|*2.1 and higher* |
|*Below 2.1* |
|===

ifdef::win[]

The format:



ifdef::ios[]

[[h2__1445214913]]
=== Deduplication

Duplicate records may be created during the sync process. When the
internet connection is lost, the response may not receive on the mobile
device whether records were inserted into Salesforce. Therefore, when a
mobile user launches the synchronization again, the CT Mobile app sends
records for which no response has been received, and the duplicate
records may appear on the Salesforce side.



When there is the[.apiobject]#MobileId__c# field and a
mobile user launches the synchronization again, the CT Mobile app checks
the records on the Salesforce side and if there are records with the
same value in the[.apiobject]#MobileId__c# field, these
records are excluded and only those that have not yet been sent to
Salesforce are sent.
