= ctm.like

The method of the xref:android/knowledge-base/ct-presenter/js-bridge-api/index.adoc[JS Bridge] functionality is
intended to add a like to the current slide. Likes are stored in the
record of the xref:android/knowledge-base/ct-presenter/clm-scheme/clm-applicationstats.adoc[Application Stats] object.

[[h2_905713055]]
=== Query Format 

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.like()
....

|===

[[h2_442663712]]
=== Handler 

Use a handler function to describe the output format of the query
results, e.g., to display the results of operations or method errors for
debugging purposes.

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.like()
....

|===



[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
ctm.like( function(response){ 
    console.log('Result', response); 
})
....

|===



The results:

[width="100%",cols="100%",]
|===
a|
xref:javascript:void(0)[Copy Code]

JavaScript

a|
....
{
    "success": true"
}
....

|===
