= JSON Specifications and Examples

When creating a link:layout-settings-field-reference.html[Layout
Settings] record, the administrator leaves the *Layout JSON* field blank
or fills it with the preconfigured JSON.

* The JSON contains all settings for displayed tabs, sections, and
fields within the record screen in the CT Mobile app.
* The *Layout JSON* field will be automatically populated with the
generated JSON after the administrator specifies
link:ct-layouts-editor-customize-tabs.html[tab] and
link:ct-layouts-editor-add-sections-and-fields.html[section] settings in
the CT Layouts Editor.
* The *Layout JSON* field is automatically updated after the
administrator makes and saves changes for tabs and sections in the CT
Layouts Editor.
* Before saving, the settings in the JSON format will be validated.



Click to expand the JSON example for the *Tab* mode

.Click to hide[%collapsible] ==== ====

Click to expand the JSON example of the *Path* mode

.Click to hide[%collapsible] ====



====



In this article, we describe allowed JSON keys and values.

:toc: :toclevels: 3

[[h2__864423552]]
=== The Global Setup for Displaying Tab or Path Mode

[[h3_1857678454]]
==== Keys

Using the
link:ct-layouts-editor-customize-tabs.html#h3__1068114486[Settings] and
link:ct-layouts-editor-customize-tabs.html#h3_349797985[Navigation]
buttons, the administrator defines high-level settings, such as
displayed tab mode and allowed tab customization.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|globalActions |An array of
link:json-specifications-and-examples.html#h2__1835390962[Global
Actions] |Yes |An array of one or more global actions that are specified
for one or more navigation buttons.

|hasCustomColors |Boolean |No |true
if link:ct-layouts-editor-customize-tabs.html#h3__1068114486[the *Custom
Color Scheme* checkbox is active] to set up a color scheme.

|hasCustomIcons |Boolean |No |true
if link:ct-layouts-editor-customize-tabs.html#h3_633900184[the *Add
icons for steps* checkbox is active] to specify icons
from https://www.lightningdesignsystem.com/icons/#utility[the standard
Salesforce set] for each tab.

|isCloseInProgressStepsAllowed |Boolean |Yes |true
if link:ct-layouts-editor-customize-tabs.html#h3__1068114486[the *Allow
close the steps in Progress* checkbox is active] to allow mobile users
to close CT Layouts tabs in the *In Progress* status. 

|stepSettings
|link:json-specifications-and-examples.html#h3_1890880071[Step Settings]
|No |true if
link:ct-layouts-editor-customize-tabs.html#h3__1068114486[the *Path*
mode is set] and the *Status* field is selected.

|tabs |An array of
link:json-specifications-and-examples.html#h2_1948275861[Tabs] |Yes
|List of tabs to display on a record screen.

|version |Number |Yes a|
The JSON version. Allowed values:

* 1

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3_1890880071]]
==== Step Settings

Using the
*link:ct-layouts-editor-customize-tabs.html#h3__1068114486[Settings]*
button, the administrator distributes the status filed values of
link:layout-settings-field-reference.html[the selected object] in gropus
according to the tab status in the *Path* mode.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|completedTab
|link:json-specifications-and-examples.html#h3_1619757451[Path Tab
Settings] |Yes |The status field values that are added in
the *Completed* group of the tab statuses.

|isChangeDisplayedTabAllowed |Boolean |Yes |true if
link:ct-layouts-editor-customize-tabs.html#h3__1068114486[the *Allow
change the displayed tab* checkbox is active] to allow mobile users to
change the displayed tab.

|inProgressTab |Path Tab Settings |Yes |The status field values that are
added in the *In Progress* group of the tab statuses.

|newTab |Path Tab Settings |Yes |The status field values that are added
in the *New* group of the tab statuses.

|statusField |String |Yes |The API name of the *Status* field of the
selected object.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3_1619757451]]
==== Path Tab Settings

The administrator specifies user permissions for each tab, status, or
group of tab statuses.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|statuses |An array of String |Yes |The API names
of link:json-specifications-and-examples.html#h3_1890880071[stepSettings.statusField]
values.

|updatable |Enum |Yes a|
link:ct-layouts-editor-customize-tabs.html#h3__1068114486[User
permission on the tab] for the *Path* mode. Available values:

* *readOnly*
* *currentTab*
* *currentStatus*
* *groupStatuses*
* *allStatuses*

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h2__1835390962]]
=== Global Actions for Buttons in the Path Mode

[[h3_1652615080]]
==== Action Keys

link:ct-layouts-editor-customize-tabs.html#h4_951662406[On the General
tab of the Navigation button], the administrator sets high-level
settings for the selected navigation button, such as
link:ct-layouts-editor-customize-tabs.html#h4__921250684[conditions for
displaying the button] on the tab,
link:ct-layouts-editor-customize-tabs.html#h4_1406331569[actions] when a
mobile user taps the button, and if there are several actions, the
sequence of these actions.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|confirmationMessage |String |No |If
set, link:ct-layouts-editor-customize-tabs.html#h4_1406331569[a
confirmation message] will be shown when the mobile user taps the
button. Available values:

|showCondition
|link:json-specifications-and-examples.html#h3__1377913479[Action
Condition] |No a|
By default, a button is displayed on every tab. To hide a button:

* use the displayCondition to set criteria to display a button on the
tab
* use the hideCondition. 

The values in the alwaysDisplayedActions and alwaysHiddenActions keys of
link:json-specifications-and-examples.html#h2_1948275861[Tab Settings]
have priority over these conditions.

|hideCondition | | |

|icon |Enum |No a|
Icon name from https://www.lightningdesignsystem.com/icons/#utility[the
standard Salesforce set] to display the selected icon on the button. The
list of default values:

* *chevronleft*
* *chevronright*

|iconPosition |Enum |No a|
Icon position on the button. Available positions:

* *Leading* (by default) — display the icon on the left side of the
button.
* *Trailing* — display the icon on the right side of the button.

|label |String |Yes a|
Any button label to show it in the CT Mobile app. The list of default
values:

* *Previous* — go to the previous tab.
* *Next *— go to the next tab.
* *Return* — return to the current tab from the displayed tab that the
mobile user previously opened by tapping its header. 
[NOTE] ==== When a mobile user jumps to another tab by tapping
its header (if enabled), only the *Return* button will be available on
the opened tab. So, a mobile user can browse tabs but cannot violate the
preconfigured tab navigation. ====
* *Start* — start the action.
* *Finish* — finish the action.
* *Cancel *— cancel the action.
* *Create Record* — to create a record for a certain object.
* *Generate CG Cloud
tasks* — https://help.customertimes.com/articles/ct-mobile-ios-en/managing-visits-to-retail-stores/a/h2__1592083570[generate
assessment tasks] and visit KPIs.



The default value may be changed. Available custom values:

|name |String |Yes a|
The button name. Available values:

Names cannot be changed.

* *previousTab*
* *nextTab*
* *returnToCurrentTab*
* *start*
* *finish*
* *cancel*
* *createRecord*
* *CGCloudTasks*

|onClickActions |An array of
link:json-specifications-and-examples.html#h3__2124187468[Click Actions]
|Yes a|
Actions to perform when a mobile user taps the button.

[TIP] ==== For more information, refer to the
link:action-type-key-reference.html[Action Type Field Reference]
article. ====

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__2124187468]]
==== Click Action Keys

link:ct-layouts-editor-customize-tabs.html#h4_1406331569[On the Actions
tab of the Navigation button], the administrator specifies action that
triggered by a mobolie user's tap on the button.

[NOTE] ==== Some
link:action-type-key-reference.html#h2_333717541[actions are set for
buttons by default] but can be changed. ====

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|action |String |Yes a|
The action name.

Required when "type": "execute".

|destination |String |Yes a|
The required destination, for example, the previous or next tab.

Required when "type": "navigate".

|field |String |Yes a|
The API name of the current field.

Required when "type": "setValue".

|object |String |Yes a|
The API name of the object to create a record of.

Required when "type": "createRecord".

|recordType |String |Yes a|
The record type for the object to create a record of.

Required when "type": "createRecord".

|type |Enum |Yes a|
Available action types:

* *setValue*
* *navigate*
* *execute*
* *createRecord*
* *waitWorkflow*

|useMinilayout |Boolean |Yes a|
If set,
https://help.customertimes.com/articles/ct-mobile-ios-en/mini-layouts[the
mini layout] is used to create the record. 

Required when "type": "createRecord".

|value |Boolean |Yes a|
The value for the "field". 

Required when "type": "setValue".

| |Number | |

| |String | |
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__1377913479]]
==== Action Condition

link:ct-layouts-editor-customize-tabs.html#h4__921250684[On the
Conditions tab of the Navigation button&#44;] the administrator
specifies conditions to show or hide a button on the tab.



[[h4_74625817]]
===== Condition Level



Conditions can be set at different levels and combined into groups.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|operator |Enum |Yes a|
Available values:

* AND means that all conditions of the level must be matched.
* OR means that at least one condition of the level must be matched.

|items |Array |Yes a|
Each Item is a:

* Child condition level (parentheses in a logical expression).
* link:json-specifications-and-examples.html#h4__472370536[Field comparison
expression].

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].



[[h4__472370536]]
===== Condition Level Item



The specific condition for the level or group.

The value and values keys are used when the operator is not equal to in
and notIn.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|field |String |Yes |The API name of the current object field to check
value or link:context-key-reference.html[perform the specific context].

|operator |Enum |Yes
|link:json-specifications-and-examples.html#h4__748327130[Available
operators] depending on the field data type.

|value |Boolean |Yes |Target values for fields with the *Boolean* data
type.

| |Number | a|
Target values for fields with the *Currency* and *Number* data type.

* *Currency*
* *Number*
* *Percent*

| |String | a|
Target values for fields with the *Text* data type.

* *Lookup Relationship*
* *Master-Detail Relationship*
* *External Lookup Relationship*
* *Email*
* *Picklist*
* *Multi-Select Picklist*
* *Text*
* *Text Area*
* *Text Area (Rich)*
* *Text Area (Long)*
* *URL*

|values |Array |Yes |The specific values in the *Text* data type.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].



[[h4__748327130]]
===== Condition Operators



Check which operators can be used with the available field data types.



[width="100%",cols="^10%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%",]
|===
|*Field Data Type* |*Operator* | | | | | | | | |

| |*contain* |*notContain* |*in* |*notIn* |*equal* |*notEquel*
|*greater* |*greaterOrEqual* |*less* a|
*lessOrEqual*

|*Currency* |No |No |No |No |Yes |Yes |Yes |Yes |Yes
a|
Yes

|*Number* |No |No |No |No |Yes |Yes |Yes |Yes |Yes
a|
Yes

|*Text* a|
Yes

|Yes |Yes |Yes |Yes |Yes |No |No |No |No
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h2_1948275861]]
=== Tab Settings

Settings for
each link:ct-layouts-editor-customize-tabs.html#h3__449942769[displayed
tab] of the *Tab* and *Path* mode on the record screen.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|alwaysDisplayedActions |An array of String |No a|
An array of the values for the name key of
link:json-specifications-and-examples.html#h3_1652615080[the global
actions] to always display or hide the specified button on the tab. 

These conditions have priority over the values in the displayCondition
and hideCondition keys of
link:json-specifications-and-examples.html#h3_1652615080[Action Keys].

|alwaysHiddenActions | | |

|color |String |Yes a|
The custom color of the tab. The format (case insensitive): HSL(11, 100,
50).

Required when "hasCustomColor": true 
link:json-specifications-and-examples.html#h3_1857678454[for the tab].

|icon |Enum |Yes a|
The tab
icon from https://www.lightningdesignsystem.com/icons/#utility[the
standard Salesforce set].

[NOTE] ==== Required when "hasCustomIcons": true  ====
 link:json-specifications-and-examples.html#h3_1857678454[for the tab].

|label |String |Yes |The label of the tab. Available values:

|sections |Array of
link:json-specifications-and-examples.html#h2__903347826[Sections]
|Yes |The list of sections on the tab. 

|showSoqlCondition |String |No a|
The SOQL filter to display tab only when the criteria are met. 



For example:

|statusValue |String |Yes a|
The API name
of link:json-specifications-and-examples.html#h3_1890880071[stepSettings.statusField] value.

Required when
link:json-specifications-and-examples.html#h3_1890880071[Step Settings]
are defined.

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h2__903347826]]
=== Section Settings

link:ct-layouts-editor-add-sections-and-fields.html[In the CT Layouts
Editor], the administrator adds sections one after the other, starting
from the leftmost top corner of the grid. Sections cannot overlap each
other on the tab.

[[h3_1386155937]]
==== Section Keys

The general settings of the selected section.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|color |String |Yes a|
link:ct-layouts-editor-add-sections-and-fields.html#h3_1163797110[The
custom color] of the section.

* By default, a random color from the default color scheme is used.
* The format (case insensitive): HSL(11, 100, 50).

|extension |N/A |No |[NOTE] ==== Reserved.  ====

|icon |Enum |Yes a|
link:ct-layouts-editor-add-sections-and-fields.html#h3_1150885058[The
section icon] from the standard Salesforce set. 

* By default, a random icon is used.

|label |String |Yes |The label of the section. Available values:

|position
|link:json-specifications-and-examples.html#h3__1500637436[Section
Position] |Yes |Location of the section on the tab.

|properties |Object |Yes a|
Properties for each object depend on the value in the type key.

* link:json-specifications-and-examples.html#h3__2137120289[Current
Record: Properties]
* link:json-specifications-and-examples.html#h3__187296624[Parent
Record: Properties]
* link:json-specifications-and-examples.html#h3_674627754[Record List:
Properties]

|type |Enum |Yes a|
Type of section, which determines records of which object will be
presented in it. Available types:

* Record
* ParentRecord
* RecordList

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__1500637436]]
==== Section Position Keys

link:ct-layouts-editor-add-sections-and-fields.html[Indicated in grid
units], location of the section on the tab.  



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|height |Number |Yes |The section height in the grid units.

|width |Number |Yes |The section width in the grid units.

|x |Number |Yes |The X coordinate of the upper-left corner of the
section. 

|y |Number |Yes |The Y coordinate of the upper-left corner of the
section. 
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__2137120289]]
==== Current Record: Properties

Specific properties are available for the
link:ct-layouts-editor-add-sections-and-fields.html#h3__1171954608[Current
Record] section type.



[cols=",,,",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|fields |An array of
link:json-specifications-and-examples.html#h2__1352679225[Fields
Settings] |Yes |Fields to display.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__187296624]]
==== Parent Record: Properties

Specific properties are available for
the link:ct-layouts-editor-add-sections-and-fields.html#h3__1970634347[Parent
Record] section type.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|fields |An array of
link:json-specifications-and-examples.html#h2__1352679225[Field
Settings] |Yes |Fields to display.

|parentObject |String |Yes |The API name of the parent object.

|parentReference |String |Yes |The API name of the field with the
*Lookup* or *Master-Detail* type on the object specified in the *Layout
Settings* record.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3_674627754]]
==== Record List: Properties

Specific properties are available for
the link:ct-layouts-editor-add-sections-and-fields.html#h3_1996080511[Record
List] section type.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|fields |An array of
link:json-specifications-and-examples.html#h2__1352679225[Field
Settings] |Yes |Fields to display.

|object |String |Yes |The API name of any related object that has a
filed with the *Lookup* or *Master-Detail* type to the object in the
*Layout Settings* record.

|objectCondition |String |Yes |The SOQL filter is used to define
records of the related object to display within the section. Otherwise,
all records will be displayed.

|permission
|link:json-specifications-and-examples.html#h3__1706694265[Record
Permission Settings] |Yes |User permissions to work with fields in
the section.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h3__1706694265]]
==== Record Permission Settings

User permission to each displayed field within the section.

The https://help.salesforce.com/s/articleView?id=sf.users_fields_fls.htm&type=5[Field-Level
Security] settings for the field are higher than the field settings in
the CT Layouts.

* If the field is hidden from the mobile user, then the field will not
be presented in the section for the mobile user.
* If the field is *readOnly* for the mobile user, then the field should
not be editable in the section for the mobile user.
* If the field is *required* for the mobile user, then the field will be
required in the section for the mobile user.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|isCreatable |Boolean |Yes |Permission to create related records.

|isLocalDatabase |Boolean |Yes |Permission to delete unsynchronized
records from the mobile device.

|isSyncedDeletable |Boolean |Yes |Permission to delete
synchronized records.
|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].

[[h2__1352679225]]
=== Field Settings

[[h3__1865140130]]
==== Field Keys

The data and user permissions
link:ct-layouts-editor-add-sections-and-fields.html#h3_1652605430[for
each displayed field] in the sections.



[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|*Key* |*Type* |*Required* |*Comment*
|label |String |Yes |By default, the standard field label. To override
it use:

|name |String |Yes |The API name of the field.

|readOnly |Boolean |Yes |true if the field should be read-only. 

|required |Boolean |Yes |true if the field should be required to
fill in.

|width |int(1...100) |Yes a|
By default, the width of each column is the same. The administrator can
change the width of each column.

* The non-configured columns will be spread evenly across the section.
* If the total sum of the column widths is greater than 100, the surplus
is divided by the number of columns, and the resulting value is
subtracted from the width of each column.
* If the total sum of the column widths is less than 100, the lack is
divided by the number of columns, and the resulting value is added to
the width of each column.
* If the width is not set for all columns, and the total sum of column
widths is less than 100, the lack is evenly distributed among the unset
columns.

[NOTE] ==== Available when the section has "type": "RecordList"
==== . 

|===



Go back to link:json-specifications-and-examples.html#TOC[the table of
content].
