= Example: Mixed

Several types can be applied at once in a pricing procedure.

All rules for [.object]#Calculation Types# with a certain
combination of *Calculation Method* and *Unit of Measure* are inherited
for the nested (child) types. For example, if[.apiobject]#SUM#
is a parent type then the rules for[.apiobject]#SUM# must be
followed for all nested calculation types.

[[h2_1194847790]]
=== Type = MULT {plus} MAX

[width="100%",cols="34%,33%,33%",]
|===
|*Input Conditions* |*JSON* |*Discount Calculation Flow*
a|
Unit of Measure = Percent, Amount



Product List Price = 100$



6 Сaculation Types are created for the Pricing Procedure:

. Calculation Method = Decrease and Structural 10%
. Calculation Method = Decrease and Contract 10%
. Calculation Method = Decrease and Season 3%
. Calculation Method = Decrease and Promo Percent 0%
. Calculation Method = Decrease and Promo Amount 4$
. Calculation Method = Increase and Vat –10%

| a|
Calculating maximum discount according to the formula:

. Apply MULT:
.. 100* (1 – 0.1) = 90
.. 90* (1 – 0.1) = 81
. Apply MAX:
.. 81* (1 – 0.03) = 78,5
.. 81 – 4 = 77
. Apply Vat to the maximum discount:
.. 77 (1 – (–0.1)) = 84.7



Total price for an[.object]#Order Line Item# = 84,7$

|===

[[h2_918834409]]
=== Type = SUM {plus} MAX

[width="100%",cols="34%,33%,33%",]
|===
|*Input Conditions* |*JSON* |*Discount Calculation Flow*
a|
Unit of Measure = Percent, Amount



Product List Price = 100$



3 Сaculation Types are created for the Pricing Procedure:

. Calculation Method = Decrease and Structural 5$
. Calculation Method = Decrease and Contract 10%
. Calculation Method =Increase and Season 3%
. Calculation Method = Decrease and Promo Percent 0%
. Calculation Method = Decrease and Promo Amount 2%

| a|
Calculating the maximum discount according to the formula:

100* (1 – (0.05 {plus} 0.1 {plus} 0.03)) = 82



Total price for an[.object]#Order Line Item# = 82$

|===
