= Migration to Remote Detailing 2.0

[NOTE] ==== For users of CT Mobile package v. 3.66 or higher.
====

The new remote detailing UI is available both for the presenter and
participants. Consider the following to use the *Remote Detailing 2.0*.

[[h2_2023541197]]
=== If the Remote Detailing has not been yet configured in your Salesforce org

Follow the steps in the xref:remote-detailing-setup[Remote
Detailing Setup] article.

[[h2__1683593068]]
=== If the *Remote Detailing* has been configured and updated to 2.0

If the Remote Detailing functionality is already in use in your sandbox
and/or production environment, do the following:

. The CT Mobile package v. 3.63 or higher is installed in your
Salesforce org.
. Go to *Setup → Platform Tools → Apps → Connected Apps → Manage
Connected Apps →* click *Edit* next to *CT Presenter* → for *Refresh
Token Policy* select *Refresh token is valid until revoked*.
. Go to *Setup → Custom Code → Apex Triggers →* make sure that the
[.apiobject]#>ActivitySetLinkProcess# trigger is obtained
from
https://github.com/ctsf/CLM-RemoteDetailing-Public/blob/master/source/remoteDetailing/src/triggers/ActivitySetLinkProcess.trigger[this
source] and added to your Salesforce org. The API names of the desired
*Activity* record types
xref:remote-detailing-apex-trigger-classes-and-quick-action#h2_249047963[should
be specified] within the trigger code.
. Go to the xref:ct-mobile-control-panel-presenter[CT Mobile
Control Panel:
Presenter]/xref:ct-mobile-control-panel-remote-detailing-new[CT
Mobile Control Panel 2.0: Remote Detailing] tab and check that the
*Applications List Field* and *Link Field* are filled out with the API
names of the corresponding fields of the[.object]#Activity#
object.
. Check that the *Active* and *Available for Remote Detailing*
checkboxes are selected for desired xref:clm-application[CLM
presentations].
. For *Self Detailing* functionality, update the list of CLM
presentations using the
xref:ct-mobile-control-panel-presenter#h2__891805269[Refresh CLM
presentations] button.
. Update one of the existing *Activity* records or create a new one.

[[h2__589224069]]
=== If the sandbox has been created based on the production environment with the configured Remote Detailing functionality

When you create a new sandbox based on the production environment with
the configured Remote Detailing functionality:

. Refresh the cloud token (refer to
xref:ct-mobile-control-panel-tools#h3_2011978[CT Mobile Control
Panel: Tools]/xref:ct-mobile-control-panel-tools-new#h2_2011978[CT
Mobile Control Panel 2.0: Tools]).
. Check that the records per each trigger are active in
xref:trigger-settings[Trigger Settings].
. xref:publishing-clm-presentations#h3_1098755975[Renew slides] for
each desired CLM presentation or specify the *Organization ID* of the
production environment on the
xref:ct-mobile-control-panel-tools#h3__964087610[CT Mobile Control
Panel: Tools]. To obtain an *Organization ID*,
https://help.salesforce.com/articleView?id=000325251&mode=1&type=1[see
the Salesforce Help].
