= Targeting & Marketing Cycle

[[h3_2085602804]]
==== Purpose

Tailor your strategy for call frequency, products promoted for sell-in,
products audit for a sell-out, and objectives to address your customers’
needs.

[[h3_1519431236]]
==== Main Terms

* *Marketing Cycle*
A cycle is a wide term referring to trends or patterns that emerge
during different market or business environments. The system entity is
used as a hub for a particular time range and user division to set the
visits KPI, special tracking, assortments audit.
* *Marketing Detail Tracking*
A system entity designed to track different tasks/KPIs/objectives within
the Marketing Cycle. Currently, the following Detail Tracking options
are supported: Competitor tracking / Company tracking / Special Tracking
/ Call Rate / Assortments.
* *Activity Linking*
A cycle setting that can specify that Marketing Detail Tracking would be
tracked for the particular visit type only.
* *Target Frequency*
A system entity that tracks the actual results for the particular
objectives of the Marketing Cycle and flags clients that belong to your
targeted segment or group.
* **Call Rate
**A parameter for tracking the Marketing Cycle for the targeted clients
and execution of planned visits.
* ***Company Product Tracking
***An activity related tab that is designed to provide an audit of
companies' products.
* *Competitor Product Tracking
* An activity related tab that is designed to track the competitor
activity for the particular clients.
* *Special Tracking*
An activity related tab that is designed to set the objectives for the
specific clients within the Marketing Cycle.

[[h3_1671735587]]
==== Process Description

. Think about User divisions in your company that could be different
departments that have the same structure but works with different KPIs.
. Think about your Clients and segments/categories you want to use to
work with them and whether that would be cross-team segmentation or you
would target them differently for each user division.
. Prepare the system for the selected User division and Clients
Categories.
. Understand what is the time range in your company to track trends via
the Marketing Cycles.
. Set the Objectives/Company tracking/Product Tracking/Call Rate/POS
material tracking per each client's segment of the Marketing Cycle (that
is unique for user division).
. Track the Marketing Cycle execution via the Dashboards and Reports.

[[h3_78726740]]
==== Setup Steps

To use *Marketing Cycle* and *Targeting* options:

. Check Marketing Cycle & Target Management settings.
* xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/add-and-set-up-divisions.adoc[Create and set up divisions].
* Setup xref:setting-up-a-division-target-frequency[Division Target
Frequency].
* xref:marketing-detail-tracking-categories[Add customer
categories] to Marketing Detail Tracking.
* xref:marketing-detail-tracking[Add product record types] on
Marketing Detail Tracking.
* Create xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-marketing-cycle/linking-activity.adoc[Activity Link] for automatic linking
activity with a certain marketing cycle.
. xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-marketing-cycle/creating-a-marketing-cycle.adoc[Create Marketing Cycle].
. xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/creating-a-targeting-list.adoc[Target your potential
customers] to sell products.
. Use the xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/creating-a-targeting-list.adoc[Filter] to see targeting
Accounts and Contacts.
. Analyze the results via the Reports. Use these options to conduct
research to gain knowledge about your customers, products, and
competitors.
