= Address Setting Field Reference

The _Address Setting_ record type is intended to store the address field location and SOQL filter to search for available delivery addresses for an account.

'''''

Object record type API name: [.apiobject]#AddressSetting#

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Address Field
|[.apiobject]#orders\__AddressField__с# |Text(255) a|
Specify the field API name of the [.object]#Address# object that contains the delivery address of a selected *Sales Organization*.

* Account
* RetailStore
* the API name of the custom [.object]#Address# object
+
NOTE: The custom [.object]#Address# object should be created by the administrator.

|Sales Organization
|[.apiobject]#orders\__SalesOrganizationId__c#
|Lookup(Sales Organization) a|include::partial$sales-org-field.adoc[]

|SOQL Filter |[.apiobject]#orders\__SOQLFilter__c#
|Long Text Area(32768) a| Specifies the SOQL filter that will be used for searching the delivery addresses.

* use the [.apiobject]#WHERE# clause and following operators: [.apiobject]#OR#,[.apiobject]#AND#, [.apiobject]#LIKE#, [.apiobject]#ORDER BY#, [.apiobject]#LIMIT#, [.apiobject]#=#, [.apiobject]#!=#, [.apiobject]#>#, [.apiobject]#<#, [.apiobject]#>=#, [.apiobject]#\<=#
* To define the corresponding account, use [.apiobject]#{!Account.Id}# or [.apiobject]#{!RetailStore.Id}#

The result will be the ID list of the custom _Address_ records and values specified in the appropriate field of this object, for example, [.apiobject]#Address__с#.

|===
