= Activity Sync Default Configuration

By default, the following field values are copied via Activity Sync:


[cols="^,^,^",]
|===
2+|*Standard Calendar*  |*CT Pharma Calendar*

|*Field Label* |*Field Label* |*Field Name*

|[.apiobject]#Event# |[.apiobject]#Task# |[.apiobject]#CTPHARMA\__Activity__c#
|[.apiobject]#StartDateTime# |- |[.apiobject]#CTPHARMA\__StartDate__c#
|[.apiobject]#EndDateTime# |- |[.apiobject]#CTPHARMA\__EndDate__c#
|[.apiobject]#WhoId# |[.apiobject]#WhoId# |[.apiobject]#CTPHARMA\__ContactId__c#
|[.apiobject]#WhatId# |[.apiobject]#WhatId# |[.apiobject]#CTPHARMA\__AccountId__c#
|[.apiobject]#OwnerId# |[.apiobject]#OwnerId# |[.apiobject]#OwnerId#
|===


When the activity record is generated, the relationship field [.apiobject]#CTPHARMA\__ActivityId__c# on the standard [.object]#Activity# object record is filled-out. Due to this relationship, the changes are synchronized.

Only the field changes from the table above will be taken into Account during synchronization, if:

* the standard and custom activity records are already synced;
* the type of record on the custom Activity or the value of the *Type* field on the _Task_/_Event_ record is changed.
