= CT CPG Solution

CT CPG is a CRM-solution designed to organize the work process of trade
and company representatives. Besides standard CRM functions, the system
provides tools for solving specific tasks for company business. Using CT
CPG allows the company:

* to automate the work of employees working on-site;
* to flexibly manage the content of informational materials;
* to see feedback from customers on the results of each meeting,
allowing a significant decrease in budget and time for marketing
research.



The advantages of the managed package are:

* the delivery process of CT CPG;
* compatibility with other products of the CT family;
* support and adaptation to Salesforce updates (API versions, metadata
types, Lightning Experience);
* no counting for the package objects in the limits of your Salesforce
organization.



For your convenience, we prepared the CT CPG guides with the following
sections:

* The xref:ct-cpg-solution/index[CT CPG Solution] section describes the
CT CPG package, its place in the CT family, and some exceptional
settings for Salesforce organization.
* In the xref:news[News] section, we share with you the latest CT
CPG updates, release notes and Salesforce updates that affect our CT CPG
solution.
* xref:/articles/project-ct-cpg/reference-guide[Reference Guide]
provides a description of all CT CPG components, such as objects, custom
settings, and custom metadata types.
* xref:administrator-guide[Administrator Guide] is a set of
articles with detailed information about how to set up functionalities
in the managed CT CPG package.
