= Sales Organization User Field Reference

The[.object]#Sales Organization User# object is intended to
relate the CT Orders with the target system, e.g., CT CPG / CT Pharma.
Without this setting, a user cannot use the CT Orders features.

'''''

Object API name:
[.apiobject]#orders__SalesOrganizationUser__c#

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|External Id |[.apiobject]#orders__ExternalId__c#
|Text(255) (External ID) (Unique Case Sensitive) a|
Specify only in the case if there is a target ERP system that provides
data with accounts, delivery addresses, price books, etc. 

You can add all data using in one file with the .csv extension.

|Primary |[.apiobject]#orders__IsPrimary__c# |Checkbox
|If selected, the specified Sales Org is primary for a user.

|Sales Organization
|[.apiobject]#orders__SalesOrganizationId__c#
|Master-Detail(Sales Organization) |The business unit for which the
settings are configured.

|User |[.apiobject]#orders__UserId__c# |Lookup(User) |A
user account for which a Sales Org is selected.
|===
