= Quiz Answer Field Reference

The[.object]#Quiz Answer# object is intended to store the
partaker's answers to the xref:admin-guide/quizzes-management/ref-guide/quiz-field-reference[_Quiz_]
questions.

'''''

API name in Salesforce: CTCPG\__QuizAnswer__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Answer |CTCPG\__Answer__c |Text (255) |It is used to store the
partaker's answer to a quiz question.

|Correct Answer |CTCPG\__IsCorrectAnswer__c |Checkbox |If
selected, the partaker's answer is correct.

|Mobile ID |CTCPG\__MobileId__c |Text(255) a|
[NOTE] ==== In case of integration with the CT Mobile app.  ====

If filled out, the quiz was passed on the mobile device.

The Mobile ID is a unique identifier to identify the record that was
created or edited in the CT Mobile app.

|Quiz |CTCPG\__QuizId__c |Lookup(Quiz)      |The
linked _Quiz_ record.

|Quiz Completion |CTCPG\__QuizCompletionId__c
|Master-Detail(Quiz Completion) |The parent _Quiz Completion_ record.

|Quiz Question |CTCPG\__QuizQuestionId__c |Lookup(Question)
a|
The linked _Question_ record to which the answer was given.

|===
