= Quota Usage Field Reference

The [.object]#Quota Usage# object is a junction object that links xref:admin-guide/managing-ct-orders/product-validation-in-order/quotas/quota-field-reference.adoc[a quota] to xref:admin-guide/managing-ct-orders/delivery-management/delivery-line-item-field-reference.adoc[a certain delivery] and stores all information on the quota. A record is created after the quota has been applied in an order.

'''''

Object API name: [.apiobject]#orders\__QuotaUsage__c#

'''''

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Field* |*API Name* |*Type* |*Description*

|Amount |[.apiobject]#orders\__Amount__c#
|Currency(16,2) a| Amount of products booked or used in the order according to the quota.

It is used when the [.apiobject]#orders\__UnitOfMeasure__c# field of the quota is _Amount_.

|Delivery Line Item
|[.apiobject]#orders\__DeliveryLineItemId__c#
|Master-Detail(Delivery Line Item) |It is a required field to relate the corresponding [.object]#Delivery Line Item# record.

|Order |[.apiobject]#orders\__OrderId__c#
|Lookup(Order) |The parent _Order_ record for the [.apiobject]#orders\__DeliveryLineItem__c# field.

|Quota |[.apiobject]#orders\__QuotaId__c#
|Master-Detail(Quota) |The parent _Quota_ record.

|Quantity |[.apiobject]#orders\__Quantity__c#
|Number(18,0) a| Quantity of products booked or used in the order according to the quota.

It is used when the [.apiobject]#orders\__UnitOfMeasure__c# field of the quota is _Quantity_.

|Status |[.apiobject]#orders\__Status__c# |Picklist
a| It is a required field to define whether the products have been booked or used according to the quota. Available values:

* _Booked_
* _Used_

|===
