= 5. User Permission Settings

include::ROOT:partial$profile-settings-display.adoc[]

Configure users' profiles and permission sets to manage user access to  certain CT CPG functionality. We kindly ask you to perform all customization with a separate Administrator account.

[[h2_945551765]]
== Profiles and Permission Sets

Create or use the preliminary profiles to assign the minimum permissions and access settings for specific groups of users. To extend users' access by granting more permissions, create permission sets.

For more information, go to Salesforce Help: link:https://help.salesforce.com/articleView?id=admin_userprofiles.htm&type=5[Profiles], link:https://help.salesforce.com/articleView?id=perm_sets_overview.htm&type=5[Permission Sets].

xref:news/salesforce-updates/salesforce-winter-20-release-critical-updates.adoc[The Salesforce Critical Updates] that were introduced at the beginning of 2020 require
administrators to perform manual permissions configuration for all package users within their company.
