= Planning Calendar Settings Field Reference

The [.object]#Planning Calendar Settings# object is intended to
store xref:admin-guide/calendar-management/legacy-calendar-management/configure-settings-for-the-calendar/index.adoc[the Pharma Calendar
parameters specified per each user division].

'''''

API name in Salesforce: CTPHARMA\__CalendarSettings__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Account Block
|[.apiobject]#CTPHARMA\__AccountBlock__c# |Text(255)
a|
The API name of the *Account* field for the *Account* title in the
*xref:admin-guide/calendar-management/legacy-calendar-management/manage-activities-on-the-hierarchy-view-tab.adoc[Hierarchy
View]* tab.



Stored within the *Global* setting type.

|Active |[.apiobject]#CTPHARMA\__IsActive__c# |Checkbox
|If selected, the corresponding Calendar setting is active.

|Allow Holiday Events
|[.apiobject]#CTPHARMA\__AllowHolidayEvents__c#
|Checkbox a|
If enabled, the representative can create a _Pharma Activity_ record on
holidays and weekends.



Stored within the *Global* setting type.

|API |[.apiobject]#CTPHARMA\__API__c# |Text(255) |The
field API name to differentiate _Pharma Activity_ records by color, for
example,[.apiobject]#CTPHARMA\__Status__c#.

|Calendar Day Source Object
|[.apiobject]#CTPHARMA\__CalendarDaySourceObject__c#
|Text(50) a|
The API name of the custom
xref:add-the-custom-holidays-dictionary[Dictionary] object.

* Used if
the [.apiobject]#CTPHARMA\__UseCalendarObject__c# field
is selected.

* Stored within the *Global* setting type.

|Calendar Locale
|[.apiobject]#CTPHARMA\__CalendarLocale__c# |Text(10)
a|
The value of the
[.apiobject]#CTPHARMA\__CalendarLocale__c# on the _User_
record that is responsible for the current calendar language. Available
values:

* en (English);
* fr (French);
* ru (Russian);
* ar (Arabic);
* de (German);
* es (Spanish);
* it (Italian);
* zh-cn (Chinese);
* (Zhōngwén) (Mandarin);
* hi (Hindi).

|Color |[.apiobject]#CTPHARMA\__Color__c# |Long Text
Area(32768) a|
The specific color for the _Pharma Activity_ record with the
corresponding record type (separated by a comma, without a blank space).


Stored within the *Global* and *Color* setting type.

|ContextMenuPoints
|[.apiobject]#CTPHARMA\__ContextMenuPoints__c# |Long
Text Area(3000) |If true, the _Pharma Activity_ record type is available
to create on the
corresponding *xref:admin-guide/calendar-management/legacy-calendar-management/manage-activities-on-the-table-view-tab.adoc[Table]*,
*Hierarchy*, and
*xref:admin-guide/calendar-management/legacy-calendar-management/manage-activities-on-the-employees-calendar-tab.adoc[Employees]*
tabs (separated by a comma, without a blank space).

|Date field name
|[.apiobject]#CTPHARMA\__DateFieldName__c# |Text(50)
a|
The API name of the *Date* field of the
custom [.object]#Dictionary# object.

* Used if
the [.apiobject]#CTPHARMA\__UseCalendarObject__c# field
is selected.
* Stored within the *Global *setting type.

|Default View |[.apiobject]#CTPHARMA\__DefaultView__c#
|Text(255) a|
The default view of the calendar grid:

* month
* agendaDay
* agendaWeek

Stored within the *Global* setting type.

|Description field name
|[.apiobject]#CTPHARMA\__DescriptionApiName__c#
|Text(50) a|
The API name of the *Description* field of the
custom [.object]#Dictionary# object.

* Used if
the [.apiobject]#CTPHARMA\__UseCalendarObject__c# field
is selected.
* Stored within the *Global *setting type.

|Disable Left Click
|[.apiobject]#CTPHARMA\__DisableLEftClick__c# |Checkbox
| If enabled, the left-click action is restricted.

|Division |[.apiobject]#CTPHARMA\__Division__c#
|Picklist a|
xref:admin-guide/targeting-and-marketing-cycle/configuring-targeting-and-marketing-cycles/managing-targeting/add-and-set-up-divisions.adoc[The calendar division]. Available
values by default:

* Alpha
* Beta

The representative can create a _Pharma Activity_ record if _Account_,
_Contact_, and _User_ record have the same division.

|Duration |[.apiobject]#CTPHARMA\__Duration__c#
|Number(3,0)  |The default duration in minutes for the Pharma
Activity. Available values are from 30 to 480.

|Enable list calendar
|[.apiobject]#CTPHARMA\__EnableListCalendar__c#
|Checkbox |If enabled, a user can select the *List Day*, *List Week*,
and *List Month* calendar view.

|End |[.apiobject]#CTPHARMA\__End__c# |Number(2,0) a|
The end hour of the working day.



Stored within the *Global* setting type.

|Fields |[.apiobject]#CTPHARMA\__Fields__c# |Long Text
Area(131072) |The API names of the fields in one of the Calendar
settings, for example, for the popups (separated by a comma, without a
blank space).

|Holiday Flag
|[.apiobject]#CTPHARMA\__HolidayFlagApiName__c#
|Text(50) a|
The API name of the *Holiday* field of the
custom [.object]#Dictionary# object.

* Used if
the [.apiobject]#CTPHARMA\__UseCalendarObject__c# field
is selected.
* Stored within the *Global *setting type.

|ID |[.apiobject]#CTPHARMA\__ID__c# |Long Text
Area(32768) |Stored within the *Icon* setting type.

|Inverted Click Logic
|[.apiobject]#CTPHARMA\__IsClickLogicInverted__c#
|Checkbox a|
If enabled:

* single-click to open a _Pharma Activity_ record;
* double-click to delete a _Pharma Activity_ record.

|Labels |[.apiobject]#CTPHARMA\__Labels__c# |Long Text
Area(131072) |Labels of the fields in one of the Calendar settings,
for example, for the popups (separated by a comma, without a blank
space).

|Name |[.apiobject]#CTPHARMA\__Name__c# |Text(255) |It
is used to store different settings, such as the default mass action,
the Pharma Activity record type, etc.

|ProfileId |[.apiobject]#CTPHARMA\__ProfileId__c#
|Text(255) |The ID of the corresponding user profile.

|Real Time Saving
|[.apiobject]#CTPHARMA\__RelaTimeSaving__c# |Checkbox
|If selected, settings will be saved in the real-time.

|RecordType |[.apiobject]#CTPHARMA\__RecordTypeId__c#
|Text(255) |The ID of the corresponding _Pharma Activity_ record type
for the popup.

|Reference Block
|[.apiobject]#CTPHARMA\__ReferenceBlock__c#
|Text(255) a|
The API name of the *Contact* or *Reference* field for
the __Contact_ or _Reference__ title in the Hierarchy view.



Stored within the *Global* setting type.

|Relationships
|[.apiobject]#CTPHARMA\__Relationships__c# |Long Text
Area(32768) |The API name of the related fields, for example, lookup
fields.

|Required |[.apiobject]#CTPHARMA\__Required__c# |Long
Text Area(32768) |If enabled, the corresponding field in the _Pharma
Activity_ creation popup is required to fill out.

|Setting Type |[.apiobject]#CTPHARMA\__SettingType__c#
|Picklist a|
The setting type of the calendar setting:

* *Color* to store _Pharma Activity_ color settings;
* *Global* to store main settings;
* *Icon* to store icon images for the Pharma _Activities_;
* *Link* to store available links;
* *Popup* to store additional popup settings;
* *Setting* not in use;
* *Tip* to store tips parameters;
* *View* to store list view parameters;
* *Context Menu* to define available _Pharma Activity_ record types on
the *Tab* or *Hierarchy* tabs;
* *draganddropTrigger* to enable the drag-and-drop action
* *Mass Actions* to define the default mass action;
* *OldPopup* not in use.

|Show weekends
|[.apiobject]#CTPHARMA\__ShowWeekends__c# |Checkbox a|
If enabled, the weekends are displayed on the calendar grid.


Stored within the *Global* setting type.

|Start |[.apiobject]#CTPHARMA\__Start__c# |Number(2,0)
a|
The start hour of the working day.


Stored within the *Global* setting type.

|Time Format |[.apiobject]#CTPHARMA\__TimeFormat__c#
|Text(255) a|
The default time format. Available values:

* 24-hour
* AM/PM

|To Show Popup |[.apiobject]#CTPHARMA\__ToShowPopup__c#
|Long Text Area(32768) |If enabled, the _Pharma Activity_ creation
popup (if specified) will be displayed to fill out during the _Pharma
Activity_ record creation.

|Types |[.apiobject]#CTPHARMA\__Types__c# |Long Text
Area(131072) |The _Pharma Activity_ record type to select for the
popup displaying.

|URL |[.apiobject]#CTPHARMA\__URL__c# |URL(255) |It is
used to store the URL for the _Pharma Activity_ icon or for the useful
link.

|Use calendar object
|[.apiobject]#CTPHARMA\__UseCalendarObject__c#
|Checkbox |If enabled, the additional custom dictionary is in use.

|Use Frequency
|[.apiobject]#CTPHARMA\__UseFrequency__c# |Checkbox
a|
If enabled, when a representative creates a _Pharma Activity_ record for
the _Account_ by dragging and dropping, the _Pharma Activity_ records
will be automatically created with a 30-minute interval for the
associated target _Contacts_.


Stored within the *Global* setting type.

|Value |[.apiobject]#CTPHARMA\__Value__c# |Long Text
Area(131072) |The Standard Layout or any Visualforce page to view the
_Pharma Activity_ record.

|View Criteria Fields
|[.apiobject]#CTPHARMA\__CriteriaField__c# |Long Text
Area(131072) a|
The API names of xref:admin-guide/calendar-management/legacy-calendar-management/manage-list-views-for-the-calendar.adoc[the list
view] fields (separated by a comma, without a blank space).

Stored within the *View* setting type.

|View Criteria Operators
|[.apiobject]#CTPHARMA\__CriteriaOperator__c# |Long
Text Area(131072) a|
The API names of the list view operators (separated by a comma, without
a blank space).


Stored within the *View* setting type.

|View Criteria Types
|[.apiobject]#CTPHARMA\__CriteriaType__c# |Long Text
Area(131072) a|
The data types of the list view fields (separated by a comma, without a
blank space).


Stored within the *View* setting type.

|View Criteria Values
|[.apiobject]#CTPHARMA\__CriteriaValue__c# |Long Text
Area(131072) a|
The values of the list view fields (separated by a comma, without a
blank space).


Stored within the *View* setting type.

|View Name |[.apiobject]#CTPHARMA\__ViewName__c#
|Text(255) |​Not in use.

|View Roles |[.apiobject]#CTPHARMA\__Roles__c# |Long
Text Area(131072) a|
The IDs of the selected user roles to access a list view (separated by a
comma, without a blank space).

Stored within the *View* setting type.

|View SObject |[.apiobject]#CTPHARMA\__SObject__c#
|Text(255) a|
The API name of the object to sort its records in a list view.


Stored within the *View* setting type.

|View Sort |[.apiobject]#CTPHARMA\__Sort__c#
|Text(255) a|
The API name of the field to sort records in a list view.


Stored within the *View* setting type.

|View Sort Order |[.apiobject]#CTPHARMA\__SortOrder__c#
|Picklist a|
The ascending or descending order of the records in a list view.
Available values:

* asc
* desc

Stored within the *View* setting type.

|Week Start |[.apiobject]#CTPHARMA\__WeekStart__c#
|Number(18,0) a|
The first day of the week on the calendar grid.



Stored within the *Global* setting type.

|===
