= Change Request Management

[.confluence-information-macro-body .confluence-information-macro-information]#
Currently, only the _Change Request: Update_ process is described and
can be applied. #

Change Request functionality is intended to control the data quality
within an organization. Configure your company-specific approval process
to update the client's data.

[[h2_868357564]]
=== Change Request: Update

Follow the guidelines to use the _Change Request: Update_ functionality:

. Think about the data you might need to change, for example, phones,
addresses, contact email, etc.
. link:/articles/project-ct-cpg/change-requests-management/a/h2__1657289809[Clarify
roles and permissions] according to your company's _Change Request_
processes.
. link:configure-a-new-change-request-update#h2__315694290[Create
the related fields] on the[.object]#Change Request# object and
link:configure-a-new-change-request-update#h2__1624561601[map
fields] of the target and[.object]#Change Request# objects.
. Add the *Change Requests* related list to the target object tabs.



Next, the representative
link:work-with-change-request#h2_1798626951[creates a change
request] that will be sent to a supervisor
link:work-with-change-request#h2__690152387[for approval].
