= Remote Detailing 2.0 Release Notes

Here you could find a feature, the link to the corresponding article,
and the date since the feature became available.

* The comparison of the Remote Detailing versions is
available link:remote-detailing-versions-comparison[here].
* Remote Detailing 2.0 and Self Detailing 2.0 are parts of
the link:ct-presenter[CT Presenter] solution. The CT Presenter
features depend on the version of the CT Mobile package are
available link:ct-mobile-package-release-notes[here].



July 15, 2022

* With an active CT Mobile license for Salesforce, share CLM
presentations with Microsoft Teams meeting attendees
link:remote-detailing-launch-microsoft-teams[using the CT Presenter
app].



December 27, 2021

* When viewing a CLM presentation, participants' devices will not go to
sleep.



December 25, 2021

* Support for the secure link:ctm-securequery[ctm.secureQuery]
method during the Self-Detailing meeting.



November 16, 2021

* link:remote-detailing-2-0-ui-for-participants#h3__111154998[The
pointer icon next to a participant] will be highlighted when the
presenter grants the participant the appropriate permission.



November 12, 2021

* Participants can
link:remote-detailing-2-0-ui-for-participants#h4__1837856184[turn
on the video or share the screen] in a browser.
link:remote-detailing-2-0-ui-for-presenter#h4_1768762957[The
presenter can select] the participant's video or screen to show it on
the main screen instead of the CLM presentation.



October 13, 2021

* During the visit creation, Remote Detailing 2.0. notifies a user about
CLM presentations not found on the server.



October 8, 2021

* Display the warning that the current user has no permission to launch
the *Remote Detailing* session.



August 31, 2021

* The Remote Detailing 2.0 servers have moved to the new connected app.
Available for users of
link:ct-mobile-package-release-notes#h2_1028401963[CT Mobile
package v. 3.63] and higher.



August 27, 2021

* The ability to specify whether link:clm-settings[the participant
is required] to add the email to access the *Remote Detailing* meeting.
* Display all link:clm-application[active and available for Remote
Detailing meetings] CLM presentations during the *Remote Detailing*
meeting when CLM presentations are not set for the *Activity* record.
* The ability
https://help.customertimes.com/articles/ct-mobile-ios-en/changing-slides[to
open a scenario] from the launched CLM presentation.



August 9, 2021

* Participants will be automatically logged out from the *Remote
Detailing* meeting when the presenter is absent more than
link:ct-mobile-control-panel-presenter#h3__1123335710[the specified
time interval].



July 12, 2021

* It is forbidden to use
https://help.customertimes.com/articles/ct-mobile-ios-en/js-bridge-methods-availability[some
JS Bridge methods] in the CLM presentation during the *Self Detailing*
meeting.



July 7, 2021

* The connection is set to collect statistics via
link:ct-mobile-control-panel-presenter#h3__53846510[the integration
user] during the *Self Detailing* meeting.



June 29, 2021

* link:clm-settings[If enabled], the chat history will be saved and
linked to the corresponding *Activity* record.
