= Remote Detailing 2.0 Release Notes

Here you could find a feature, the link to the corresponding article,
and the date since the feature became available.

* The comparison of the Remote Detailing versions is
available xref:remote-detailing-versions-comparison[here].
* Remote Detailing 2.0 and Self Detailing 2.0 are parts of
the xref:ct-presenter[CT Presenter] solution. The CT Presenter
features depend on the version of the CT Mobile package are
available xref:ios/news/ct-mobile-package-release-notes/index.adoc[here].



July 15, 2022

* With an active CT Mobile license for Salesforce, share CLM
presentations with Microsoft Teams meeting attendees
xref:remote-detailing-launch-microsoft-teams[using the CT Presenter
app].



December 27, 2021

* When viewing a CLM presentation, participants' devices will not go to
sleep.



December 25, 2021

* Support for the secure xref:ios/ct-presenter/js-bridge-api/methods-for-remote-detailing-2-0/ctm-securequery.adoc[ctm.secureQuery]
method during the Self-Detailing meeting.



November 16, 2021

* xref:remote-detailing-2-0-ui-for-participants#h3_111154998[The
pointer icon next to a participant] will be highlighted when the
presenter grants the participant the appropriate permission.



November 12, 2021

* Participants can
xref:remote-detailing-2-0-ui-for-participants#h4_1837856184[turn
on the video or share the screen] in a browser.
xref:remote-detailing-2-0-ui-for-presenter#h4_1768762957[The
presenter can select] the participant's video or screen to show it on
the main screen instead of the CLM presentation.



October 13, 2021

* During the visit creation, Remote Detailing 2.0. notifies a user about
CLM presentations not found on the server.



October 8, 2021

* Display the warning that the current user has no permission to launch
the *Remote Detailing* session.



August 31, 2021

* The Remote Detailing 2.0 servers have moved to the new connected app.
Available for users of
xref:ios/news/ct-mobile-package-release-notes/index.adoc#h2_1028401963[CT Mobile
package v. 3.63] and higher.



August 27, 2021

* The ability to specify whether xref:clm-settings[the participant
is required] to add the email to access the *Remote Detailing* meeting.
* Display all xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[active and available for Remote
Detailing meetings] CLM presentations during the *Remote Detailing*
meeting when CLM presentations are not set for the *Activity* record.
* The ability
https://help.customertimes.com/articles/ct-mobile-ios-en/changing-slides[to
open a scenario] from the launched CLM presentation.



August 9, 2021

* Participants will be automatically logged out from the *Remote
Detailing* meeting when the presenter is absent more than
xref:ct-mobile-control-panel-presenter#h3_1123335710[the specified
time interval].



July 12, 2021

* It is forbidden to use
https://help.customertimes.com/articles/ct-mobile-ios-en/js-bridge-methods-availability[some
JS Bridge methods] in the CLM presentation during the *Self Detailing*
meeting.



July 7, 2021

* The connection is set to collect statistics via
xref:ct-mobile-control-panel-presenter#h3_53846510[the integration
user] during the *Self Detailing* meeting.



June 29, 2021

* xref:clm-settings[If enabled], the chat history will be saved and
linked to the corresponding *Activity* record.
