= Remote Detailing UI Basics

The *Remote Detailing* meeting has a different UI for the presenter and
participants and depends on the CT Mobile package version. Read the
articles to be fully aware of the available functionality.

* The homepage logo will be used
for link:the-remote-detailing-functionality[the Remote Detailing
screens], e.g., the *Waiting...* screen for participants.
* The display of the sidebar menu with participants and available
options during the *Remote Detailing* meeting depends on
the link:clm-settings[CLM Settings] record.

[width="100%",cols="50%,50%",]
|===
|*For users of the CT Mobile package below v. 3.63* |*For users of the
CT Mobile package v. 3.63 or higher*

a|
* link:remote-detailing-1-0-ui-for-presenter[Remote Detailing 1.0:
UI for Presenter]
* link:remote-detailing-1-0-ui-for-participants[Remote Detailing
1.0: UI for Participants]

a|
* link:remote-detailing-2-0-ui-for-presenter[Remote Detailing 2.0:
UI for Presenter]
* link:remote-detailing-2-0-ui-for-participants[Remote Detailing
2.0: UI for Participants]

|===
