= Activity Data

The following Apex classes are used to create a record of the custom [.object]#Activity# object ([.apiobject]#Activity\__c#) and a related record of the custom [.object]#ActivityData# object ([.apiobject]#ActivityData__c#):

* [.apiobject]#ActivityProcessHandler#
* [.apiobject]#GlobalActivityService#

The following trigger invokes the Apex classes:

* [.apiobject]#ActivityProcess#

NOTE: Before implementing, the system checks that the [.apiobject]#ActivityProcess# trigger is specified in the custom Trigger Settings.

A trigger is xref:admin-guide/configuring-triggers/trigger-events.adoc[invoked by operations on the recurring events].

The following trigger methods of the [.apiobject]#ActivityProcessHandler# class are implemented:

* [.apiobject]#onBeforeInsert#
* [.apiobject]#onBeforeUpdate#
* [.apiobject]#onBeforeDelete#
* [.apiobject]#onAfterInsert#
* [.apiobject]#onAfterUpdate#
* [.apiobject]#onAfterDelete#

In the *Setup* → *Custom Code* → *Custom Settings* → *Trigger Settings*, the system checks methods in the *Bypass Logic* field of the [.apiobject]#ActivityProcess# trigger.

[width="100%",cols="30%,70%",]
|===
|*ActivityProcessHandler Method* |*Execution*

|[.apiobject]#onBeforeInsert# |Create a record of the custom [.object]#Activity# object related to the [.object]#Contact# and [.object]#Account# objects, assign the related _Marketing Cycle_, set _Target Frequency_, and add _Objectives_.

|[.apiobject]#onBeforeUpdate# |Assign the related _Marketing Cycle_, set _Target Frequency_, and add _Objectives_ to the record of the custom [.object]#Activity# object.

|[.apiobject]#onBeforeDelete# |Search and delete the records of the standard [.object]#Event# and [.object]#Task# objects related to removed records of the custom [.object]#Activity# object.

|[.apiobject]#onAfterInsert# |Create data of the record of the custom [.object]#Activity Data# object, which is related to the record of the custom [.object]#Activity# object.

Calculate finished activities and fill in the *Actual Calls* field of the record of the [.object]#Target Frequency# object. According to the settings, add _Objectives_ and grant access to the record of the _Joint Visit_ for relevant users. According to the Activity Sync, create records of the standard [.object]#Event# and [.object]#Task# objects.

|[.apiobject]#onAfterUpdate# |Update data of the record of the custom [.object]#Activity Data# object, which is related to the record of the custom [.object]#Activity# object.

Recalculate finished activities and fill in the *Actual Calls* field of the record of the [.object]#Target Frequency# object. According to the value in the *Next Call Date* field and Next Call Settings, create children records of the custom [.object]#Activity# object. According to the settings, grant access to the record of the _Joint Visit_ for relevant users.

|[.apiobject]#onAfterDelete# |After removing related records of the custom [.object]#Activity# object, recalculate the finished activities in the *Actual Calls* field of the record of the [.object]#Target Frequency# object.
|===


