= CT Sign for CT Mobile Windows Release Notes

Here you could find a CT Sign feature, the link to the corresponding
article, and the version of CT Mobile in which the feature is available.
Add the CT Sign module to the CT Mobile Windows app to have the ability
to sign documents on the mobile device.

[[h2__523563194]]
=== CT Sign 2.0 for CT Mobile 1.3

[[h3_1642576463]]
==== New Features and Improvements

link:add-the-ct-sign-to-the-ct-mobile-app[Add CT Sign to the
menu] to sign documents in the CT Mobile app.

* Templates available for the mobile user are automatically
downloaded.
* The *Sign Document
* records available for the mobile user are
automatically downloaded.



The ability to create a document on the _Account_, _Contact_, or
_Activity_ record via
link:add-the-ct-sign-to-the-ct-mobile-app#h1_1946616521[the Sign
Document button].



The ability to sign documents
link:sign-a-document-the-ct-mobile-app#h2__1603366204[with a simple
signature].

* The document must be signed by all contacts, otherwise, it will not be
saved.
* Add the handwritten signature or select a photo with the signature
from the device gallery.
