= The Quiz Interface

[[h2_1569177101]]
=== The Start Quiz Page

Tap the *Start Quiz* button on the _Quiz_ page to open the quiz. Read
the _Quiz_ details and click *Start* to take the quiz. The *Start*
button is unavailable if the current _Quiz_ is not open yet or has
already been finished.



Click *Back to List of your Quizzes* to view assigned quizzes.

[[h2_1684132167]]
=== The Quiz Question Page

Depending on the
https://help.customertimes.com/articles/project-ct-pharma/quiz-field-reference[Quiz]
options, there can be a countdown timer.

* Click on the next or previous question or click the question number to
submit the answer to the current question. The question number will be
highlighted with green color;
* Click *Review* to highlight the question number with orange color to
not forget to verify an answer to the question;
* Click *Summary* to view quiz passing details. The green color is for
the questions with answers, the orange color for the questions in a
review, and the red color for unanswered questions;
* Click *Send* to send the quiz for approval and view results if
applied. The *Send* button appears on the last question page if all
answers are submitted.

[[h2__236293130]]
=== The Quiz Result Page

Depending on
the https://help.customertimes.com/articles/project-ct-pharma/quiz-field-reference[Quiz] options,
check the correct answer percentage, view the right answers, and the
number of attempts.
