= 2. Preparing the Salesforce instance

Prepare your Salesforce organization to enable easy configuration of CT
Vision IR and the ability to work with recognized images.

After customization, check permissions to make sure they are granted to
required user profiles.

link:preparing-the-salesforce-instance.html#h2__200909819[1. Create CTM
Settings Fields]

link:preparing-the-salesforce-instance.html#h2_1013205226[2. Create CTM
Settings Record Types]

link:preparing-the-salesforce-instance.html#h3_585696333[3. Add New
Values to the Type Field]

link:preparing-the-salesforce-instance.html#h2__242260294[4. Prepare
Layout for the Vision Setup]

link:preparing-the-salesforce-instance.html#h2__682569336[5. Assign
Permission Set for Administrators]

[[h2__200909819]]
== == 1. Create CTM Settings Fields 

Check that the following fields are created on the [.object]#CTM Settings# object that will be used in the CT Vision IR logic. If any of
these fields is missing, create it manually:

[width="100%",cols="34%,33%,33%",]
|=======================================================================
|*Field* |*API Name* |*Type*
|Colors |clm__Colors\__c |Text(255)
|Component |clm__Component\__c |Text(255)
|Default View |clm__View\__c |Text(255)
|Editable |[.apiobject]#IsEditable\__c# |Checkbox |Enable Gallery |IsGalleryEnabled\__c |Checkbox |Enable Simple View |[.apiobject]#Enable_simple_view\__c# |Checkbox
|Get Geolocation |clm__IsGetGeolocationEnabled\__c |Checkbox
|Icon |Icon\__c |Text(255)
|Field Key |[.apiobject]#FieldKey\__c# |​Text(255) |Fields To Display |[.apiobject]#FieldsToDisplay\__c# |Text(255)
|KPI |[.apiobject]#KPI\__c# |Text(255) |Label |clm__Label\__c |Text(255) |Object Record Type |clm__ObjectRecordType\__c |Text(255) |Order |clm__Order\__c |Number(18,0) |Plan |Plan\__c |Number(18,0) |Provider |[.apiobject]#Provider\__c# |​Text(255)
|Type |clm__Type\__c |Text(255)
|Vision Object |VisionObject\__c |Text(255)
|=======================================================================

[[h2_1013205226]]
== == 2. Create CTM Settings Record Types 

Create new record types for the [.object]#CTM Settings# object and set up layouts for each record type to set up CT Vision IR layouts and enable various CT Vision IR functionalities: * link:vision-account-object-field-reference.html[Vision Account] * link:vision-info-field-reference.html[Vision Info] * link:vision-hint-field-reference.html[Vision Hint] * link:vision-kpi-field-reference.html[Vision KPI] * link:vision-product-list-field-reference.html[Vision Product List] * link:vision-shelf-field-reference.html[Vision Shelf] * link:vision-visit-field-reference.html[Vision Visit] Click the link to view the required fields and their description for the corresponding record type. To create record types, https://help.salesforce.com/s/articleView?id=sf.creating_record_types.htm&type=5[refer to Salesforce Help]. [[h3_585696333]] 3. Add New Values to the Type Field link:preparing-the-salesforce-instance.html#h3_585696333[]

Specify new values for the clm__Type\__c picklist:

* For the *Vision Shelf* record type:
** Photo
** Collection
* For the *Vision KPI* record type:
** Percent
** Amount
* For the *Vision Product List* record type:
** Checkbox
** Double(16,2)
** Number(18,0)
** Text

[[h2__242260294]]
== == 4. Prepare Layout for the Vision Setup 

Add the *Product Synchronization Criteria* field to the layout of the
*Vision Setup* custom metadata type.

[[h2__682569336]]
== == 5. Assign Permission Set for Administrators

Assign the _CT Vision Administrator_ permission set to administrators.
The permission set contains all required permissions for the correct
operation of the CT Vision IR.
