= Vision Tag Field Reference

The _Vision Tag_ record type is responsible for the photo tags that
users can apply to the taken photos in
link:working-with-ct-vision-in-salesforce.html#h3_491461789[Salesforce]
and
link:working-with-ct-vision-in-the-ct-mobile-app.html#h2_491461789[the
CT Mobile app].

'''''

Record Type API Name: [.apiobject]#VisionTag# ''''' The following fields must be created on the [.object]#Vision Settings# object for this record type:

[width="100%",cols="25%,25%,25%,25%",]
|=======================================================================
|*Field* |*API Name* |*Type* |*Description*

|Colors |[.apiobject]#clm__Colors\__c# |Text(255) a| Specify the photo tag colors in the HEX format (separated by a comma, without a blank space), for example,#EB4034;28E04A.

Specify the color order according to the order of the photo tag labels
in the [.apiobject]#clm__Label\__c# field. The maximum number of listed values is 10. |Label |[.apiobject]#clm__Label\__c# |Text(255) a|
Specify photo tag names (separated by a comma, without a blank space) in
accordance with the colors in the [.apiobject]#clm__Colors\__c# field. The maximum number of listed values is 10. |Object |[.apiobject]#clm__Object\__c# |Text(255) |Specify the API name
of the object to apply the setting, for example, CTCPG__Activity\__c. 

|Object Record Type |[.apiobject]#clm__ObjectRecordType\__c# |Text(255) |If needed, specify the API name of the record type for the object in the [.apiobject]#clm__Object\__c# field to apply the setting for the
corresponding record type. 
|=======================================================================
