= Sync Log Object

The [.object]#Sync Log# object is intended to store the details
of the sync process and operations performed in the course of the
xref:ios/mobile-application/synchronization/index.adoc[synchronization] depending on the value in the
*Debug Level* option on the
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-general.adoc#h3_1226274811[CT Mobile
Control Panel:
General] / xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-general-new.adoc#h3_1226274811[CT
Mobile Control Panel 2.0: General] tab.

[WARNING] ==== The *Debug Level* option should be specified for
each profile separately. Each profile should have the *Edit* permission
for all fields of the [.object]#Sync Log ==== object. #

'''''

Salesforce API-name:[.apiobject]#clm__SyncLog__c#

'''''

[width="100%",cols="~,~,~,~",]
|===
|*Field* |*API* |*Type* |*Description*

|Date |[.apiobject]#clm__Date__c# |Date/Time |Date and
time of the operation or the synchronization completion/interruption.

|Description |[.apiobject]#clm__Description__c# |Long
Text(32768) a|
Description of the operation.

* for sending only sync logs:[.apiobject]#Part 1 from 1#
* for sending logs, data dump, and all/unsynchronized/no photos:
[.apiobject]#Part n from m#.

//tag::kotlin[]If a mobile user sends an application data dump, the
field contains [.apiobject]#Part n from m#, where *n* is the
number of an attachment and *m* is the total number of attachments.

//tag::andr,ios,win[]If a mobile
user xref:ios/mobile-application/application-settings/send-application-data-dump.adoc[sends an application data
dump], the field contains [.apiobject]#Part n from m#,
where *n* is the number of an attachment and *m* is the total number of
attachments. //tag::ios[]If the xref:ios/mobile-application/synchronization/sync-recovery.adoc[Sync
Recovery] functionality is enabled with the *Proxy Object* parameter
specified
on xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-offline-objects.adoc#h3_37043680[CT
Mobile Control Panel: Offline
Objects] / xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-offline-objects-new.adoc#h4_37043680[CT
Mobile Control Panel 2.0: Offline
Objects], the [.apiobject]#JSON created by web service# value is
set for a Sync Log record with a JSON file in the *Files* section.

|Duration |[.apiobject]#clm__Duration__c# |Number(18,0)
a|
Synchronization duration in seconds:

* If the application was stopped due to some issues, the value in this
field is zero.
* If the synchronization is interrupted due to the connection failure,
the value in this field is the actual time before the interruption.

|Errors count |[.apiobject]#clm__ErrorsCount__c#
|Number(18,0) |The number of records with errors when the
[.apiobject]#clm__Operation__c# contains *Create*,
*Update*, *Delete*, *Insert*.

|Failed IDs |[.apiobject]#clm__FailedIds__c# |Long Text
Area(131072) a|
The IDs of records containing errors when the
[.apiobject]#clm__Operation__c# contains *Create*,
*Update*, *Delete*, *Insert*.


The record IDs for the *Insert* value will not be written, as these
records only have temporary IDs.

|Failed Messages |[.apiobject]#clm__FailedMessages__c#
|Long Text Area(131072) |Error texts for each failed record when the
[.apiobject]#clm__Operation__c# contains *Create*,
*Update*, *Delete*, *Insert*.

|Geolocation |[.apiobject]#clm__Geolocation__c#
|Geolocation |The current user's geolocation if the type of operation is
Geolocation.

|Geo Timing |[.apiobject]#clm__GeoTiming__c# |Long Text
Area(131072) |The current user's local time if the type of operation is
Geo Tracing.

|Geo Tracing |[.apiobject]#clm__GeoTracing__c# |Long
Text(131072) a|
The user coordinates (separated by a semicolon, without blank spaces)
that will be captured if the user has moved 50 or more meters from the
previous location.



If xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-general.adoc#h3_1808523151[the tracking
interval] (refer to
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-general.adoc#h3_1808523151[CT Mobile
Control Panel:
General] / xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-general-new.adoc#h3_1808523151[CT
Mobile Control Panel 2.0: General]) is 0, the user's coordinates will
not be captured.

|Has Recovery Data
|[.apiobject]#clm__HasRecoveryData__c# |Checkbox a|
//tag::andr,kotlin,win[]

Not in use.

//tag::ios[] The field is checked for a Sync Log record with a JSON
file in the Attachments section if the xref:ios/mobile-application/synchronization/sync-recovery.adoc[Sync
Recovery] functionality has the *Proxy Object* parameter specified on
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-offline-objects.adoc[CT Mobile Control
Panel: Offline
Objects] / xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-offline-objects-new.adoc#h4_37043680[CT
Mobile Control Panel 2.0: Offline Objects].

|Object name |[.apiobject]#clm__ObjectName__c#
|Text(255) |Name of the operation object when the
[.apiobject]#clm__Operation__c# contains *Create*,
*Update*, *Delete*, *Insert*.

|Operation |[.apiobject]#clm__Operation__c# |Text(255)
a|
//tag::ios, andr, win[]

The type of synchronization:

* Full Sync
* Fast Sync
* Mixed Sync
* Quick Record Sync.



Or the type of operation:

* Create
* Update
* Delete
* Login
* Insert
* Geo Tracing
* Geolocation
* Sync Log
* Sync Log History (for sending only send logs to Salesforce)
* Export Data (for sending data from the CT Mobile app)

//tag::kotlin[]

The type of synchronization:

* Full Sync
* Fast Sync
* Mixed Sync
* Quick Record Sync.

|Records Count |[.apiobject]#clm__RecordsCount__c#
|Text(255) |The total number of records transmitted in the course of the
operation when the [.apiobject]#clm__Operation__c#
contains *Create*, *Update*, *Delete*, *Insert*.

|Status |[.apiobject]#clm__Status__c# |Picklist a|
Synchronization status:

* *Success*. The synchronization is completed.
* *Partially Success*. If some errors occur during the synchronization,
but the synchronization is completed.
* *Failed*. If any error occurred during the full synchronization. The
*Sync Log* record of the failed synchronization is sent to Salesforce
after the next synchronization is finished.

|===
