= User Permissions Required to Synchronize Objects to Offline Work with Functionalities

TIP: Launch xref:ios/mobile-application/synchronization/full-synchronization.adoc[the full synchronization] to download these objects to the mobile device.

Tap the header to open the corresponding table.

[tabs]
====
User permissions for objects that are always downloaded during synchronization::
+
--
[width="100%",cols="~,~,~,~",separator=!]
!===
^!*Object* ^!*Object API Name* ^!*User Permission* ^!*Comments*

!Account ![.apiobject]#Account# !Read !
!Assignment Rule ![.apiobject]#AssignmentRule# !Read !If active.
!CTM Settings ![.apiobject]#clm\__CTMSettings__c# !Read!
!Document ![.apiobject]#Document# !Read !It is required to display the CT Mobile logo (refer to xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-general.adoc#h3_1354766135[CT Mobile Control Panel: General] or xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-user-interface-new.adoc#h3_1354766135[CT Mobile Control Panel 2.0: User Interface]).
!Email Template ![.apiobject]#EmailTemplate# !Read !If active.
!Folder ![.apiobject]#Folder# !Read !To display correctly, [.apiobject]#Dashboard# and [.apiobject]#EmailTemplate# are required.
!Group ![.apiobject]#Group# !Read !
!Record Type ![.apiobject]#RecordType# !Read !
!Sync Log ![.apiobject]#clm\__SyncLog__c# !Read; Edit !
!User ![.apiobject]#User# !Read !If active.
!User Permission Access ![.apiobject]#UserPermissionAccess#!Read !
!User Role ![.apiobject]#UserRole# !Read !
!===

--
User permissions for objects that are required for the correct offline operation of the added functionalities and integrations::
+
--
[width="100%",cols="~,~,~,~,~",separator=!]
!===
^!*Functionality/Integration* ^!*Object* ^!*Object API Name* ^!*User Permission* ^!*Comments*

.4+!xref:ios/mobile-application/mobile-application-modules/applications/index.adoc[Applications] !Application ![.apiobject]#clm\__Application__c# !Read; Edit !
!Application Stats ![.apiobject]#clm\__ApplicationStats__c# !Read !
!Custom Scenario ![.apiobject]#clm\__CustomScenario__c#!Read; Edit !
!Slide ![.apiobject]#clm\__Slide__c# !Read !
!xref:ios/mobile-application/mobile-application-modules/cg-cloud/index.adoc[CG Cloud]
!xref:ios/mobile-application/mobile-application-modules/cg-cloud/setting-up-retail-execution/activating-cg-cloud-in-the-ct-mobile-app.adoc#h2_242799573[The list of CG Cloud objects] !— !— !
.2+!xref:ctsign:admin-guide/sign-a-document-the-ct-mobile-app/add-the-ct-sign-to-the-ct-mobile-app.adoc[CT Sign]
!Sign Document![.apiobject]#ctsign\__SignDocument__c# !Read !
!Sign Settings ![.apiobject]#ctsign\__SignSettings__c#!Read; Edit !
.2+!xref:ctorders:admin-guide/workshops/workshop-4-0-working-with-offline-orders/adding-ct-orders-to-the-ct-mobile-app-4-0.adoc[CT Orders] !Group ![.apiobject]#Group# !Read !
!xref:ctorders:admin-guide/managing-ct-orders/order-management/offline-order.adoc#h2_1850278800[The list of CT Orders objects] !— !— !
.3+!xref:ios/mobile-application/ui/home-screen/index.adoc#h3_1761919763[Dashboards] (online) !Dashboard ![.apiobject]#Dashboard# !Read !
!Report ![.apiobject]#Report# !Read !
!Report Type ![.apiobject]#ReportType# !Read ! !xref:ios/mobile-application/lead-convert.adoc[Lead] !Lead Status ![.apiobject]#LeadStatus# !Read !If the list of offline objects contains the _Lead_ object.
.2+!xref:ios/admin-guide/managing-offline-objects/index.adoc[Offline Objects] !The list of offline objects !— !Read; Edit; Delete (depend on the object) !It is based on data from xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/related-list-filters.adoc[clm\__RelatedListFillters__c], xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/menu-settings-and-offline-objects.adoc[clm\__TopLvlObjects__c] (will be deprecated in future), or xref:ios/admin-guide/ct-mobile-control-panel/ctm-settings/index.adoc[CTM Settings].
!Task Status ![.apiobject]#TaskStatus# !Read; Edit !If the list of offline objects contains the [.object]#Task# object.
.2+!xref:ios/mobile-application/mobile-application-modules/opportunities/index.adoc[Opportunity] !Opportunity ![.apiobject]#Opportunity# !Read !If the list of offline objects contains the [.object]#Order# and [.object]#Quote# objects.

!Opportunity Product ![.apiobject]#OpportunityLineItem# !Read !If the list of offline objects contains the [.object]#Opportunity# object.
.4+!xref:ctorders:admin-guide/managing-ct-orders/order-management/index.adoc[Order]
!Order Product ![.apiobject]#OrderItem# !Read !If the list of offline objects contains the [.object]#Order# object.
!Price Book ![.apiobject]#Pricebook2# !Read !If the list of offline objects contains the [.object]#Order# and [.object]#Opportunity# objects.
!Price Book Entry ![.apiobject]#PricebookEntry# !Read !If the list of offline objects contains the [.object]#Order# and [.object]#Opportunity# objects.
!Salesforce Product ![.apiobject]#Product2# !Read !If the list of offline objects contains the [.object]#Order# and [.object]#Opportunity# objects.
.2+!Quote !Quote ![.apiobject]#Quote# !Read !If the list of offline objects contains the [.object]#Quote# object.
!Quote Line Item ![.apiobject]#QuoteLineItem# !Read !If the list of offline objects contains the [.object]#Quote# object.
!===
--
User permissions to download custom settings and custom metadata types::
+
--
[cols="~,~,~",separator=!]
!===
^!*Custom Setting or Custom Metadata Type* ^!*API Name* ^!*User Permission*

!Menu Settings and Offline Objects![.apiobject]#clm\__TopLvlObjects__c# !Read
!Mobile Application Setup![.apiobject]#clm\__ApplicationSetup__c# !Read
!Mobile Custom Detail Settings![.apiobject]#clm\__MobileActivityDataCustomization__c#!Read
!Mobile Customization![.apiobject]#clm\__MobileCustomization__c# !Read
!Mobile Mini Layout Settings![.apiobject]#clm\__MobileLayoutSettings__c# !Read
!Related List Filters![.apiobject]#clm\__MobileRelatedListFilters__c# !Read
!CT Mobile Replication![.apiobject]#clm\__Replication__mdt# !Read
!CT Mobile Workflow ![.apiobject]#clm\__Workflow__mdt#!Read
!CT Mobile Workflow Step![.apiobject]#clm\__WorkflowStep__mdt# !Read
!===
--
====
