= Condition: AdvancedCriteria__c Field Specification

the [.apiobject]#orders__AdvancedCriteria__c# field is
used to specify the complex logic specified in JSON format for granting
discounts in an order.

The logic is applied when the *Calculation Method* on
the [.object]#Condition# object is *Advanced*.

:toc: :toclevels: 3

[[h2_1997029544]]
=== Advanced Criteria 1.0

The *Advanced Criteria* field is used to define the group discount for
the product. It means that the condition in *Condition Details* and
additionally the condition specified in this field must be satisfied.



For example, specify products that affect the discount or the presence
of which product can determine whether a discount will be granted. Also,
there are the products, whose quantity would determine whether a
suitable *Condition Level* record would be selected. The quantity is
counted for all products, that matched the condition in the *Advanced
Criteria* field. This syntax is also applied for parsing the *Criteria
Based* and *List Based* freebies. All [.object]#Order Line
Items# of the order will. be checked. See the example below:

[{plus}] xref:javascript:void(0)[Click to view an example]

.[-] Hide[%collapsible] ====

====

[[h2_1585895621]]
=== Advanced Criteria 2.0

Advanced Criteria 2.0 provides more flexibility when granting discounts
by setting multiple filters at the same time, as well as a minimum
number of products for different size discounts. The logic is also
affected by the value specified
in xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/calculation-types-field-reference/calculation-type-applyconditiontype-c-field-specification[the
Apply Condition Type field].

See the example below, where the discount will be applied when one of
the conditions is met.

* 4 SKUs from Brand1 and 2 SKUs from Brand2
* 6 SKUs from Brand3 and 4 SKUs from Brand4
* 4 SKUs from Brand4 and 2 SKUs from Brand5

[{plus}] xref:javascript:void(0)[Click to view an example]

.[-] Hide[%collapsible] ====

====

[[h2_469009993]]
=== JSON Key Description

[[h3_1317873265]]
==== Advanced Criteria

It is used to define the *Advanced Criteria* version and set up
conditions.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#version# |Number |No a|
The version of the advanced criteria to apply. Available values:

* 1 (optional for Advanced Criteria 1.0)
* 2 (required for Advanced Criteria 2.0)

|[.apiobject]#condition# |Object |No a|
Conditions on the number of unique products and mandatory products to
get a discount.

To use several conditions, apply[.apiobject]#AND# and
[.apiobject]#OR# operators.



Required
for xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h2_1585895621[Advanced
Criteria 2.0].

|[.apiobject]#levelConditions# |Object |No a|
Conditions on the number of unique products and mandatory products to
get a discount.



Required
for xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h2_1997029544[Advanced
Criteria 1.0].

|===

[[h3_1323252625]]
==== Condition

The applied condition.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#operator# |Enum |Yes a|
Available values:

* AND
* OR

|[.apiobject]#items# |Array |Yes a|
The required condition. Available values:

* filter
See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1623789156[Filter].
* minCount
Seexref:condition-advancedcriteria-c-field-specification.html#h3_290861277[Minimum
Quantity].
* requiredProducts
See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1542681245[Required
Products].



The condition must
contain [.apiobject]#minCount# or [.apiobject]#requiredProducts#.
If [.apiobject]#filter# is used,
the [.apiobject]#minCount# or [.apiobject]#requiredProducts# logic
will be applied to the products that match the filter criteria.

|===

[[h3_1623789156]]
==== Filter

A filter defines which[.object]#Order Line Items# can be used
for calculating a unique number of products or required products.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#operator# |Enum |Yes a|
Available values:

* AND
* OR

|[.apiobject]#items# |An array of Filter Items |Yes a|
See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_764213188[Filter
items].



At least one item must be provided.

|===

[[h3_764213188]]
==== Filter Items

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#field# |String |Yes |The field from the
[.object]#Order Line Item# or its parent object for which the
operator key is applied.

|[.apiobject]#operator# |Enum |Yes |See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1330481294[Items
Operators].

|[.apiobject]#value# |Boolean |No |A target value for
fields with the *Boolean* type.

| |Number | |A target value for fields with the *Currency* or *Number*
type.

| |String | a|
A target value for fields with the *Text* type.



The key is required when the [.apiobject]#operator# key is
not [.apiobject]#in# or [.apiobject]#notIn#.

|[.apiobject]#values# |Array of Values |No a|
the [.apiobject]#values# with the *Text* type, separated by a
comma, for example:[.apiobject]#["abc","123"]#

[.apiobject]#
#

[.apiobject]#At least one item must be provided. The key is
required when the #[.apiobject]#operator# key
is [.apiobject]#in# or [.apiobject]#notIn#.

|===

[[h3_290861277]]
==== Minimum Quantity

The minimum quantity of unique products that must be added to order to
get a discount.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#minCount# |Number |Yes |The number of
products. The discount will not be calculated if the actual number of
products is less than that specified for that key.
|===

[[h3_1542681245]]
==== Required Products

The required products to get a discount.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#productField# |String |Yes a|
The identification to search required products.

* Salesforce Id (by default)
* External Id (if it is set for all products in an instance)

|[.apiobject]#operator# |Enum |Yes a|
The operator defines how to apply the logic:

* AND
It is used when all products are required to get a discount
* OR
It is used when one of the products is required to get a discount

|[.apiobject]#items# |An array of Required Product Items
|Yes a|
The list of required products. See the
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_2075634919[Required
Products Items].



The condition may be satisfied if there are no specified values.

|===

[[h3_2075634919]]
==== Required Product Items

The list of required products to get a discount.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#product# |String |Yes a|
Available values:

* Salesforce Id
* External Id (if exist)

|[.apiobject]#minQuantity# |Number |Yes |The product minimum
quantity
|===

[[h3_626528442]]
==== Level Based on Filter

The list of products that affect the group discount. These products'
quantity is compared with the value in the
[.apiobject]#StartingFrom__c# field on the
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-level-field-reference[Condition Level] record.



Applied
after xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1317873265[levelConditions] and xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1542681245[requiredProducts] are
calculated. If those conditions were not met, the **Level Based on
Filte**r will not be calculated.

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#operator# |Enum |Yes a|
Available values:

* AND
* OR



|[.apiobject]#items# |An array of Level Based on Filter Items
|Yes a|
See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_287654427[Level
Based on Filter Items].



At least one item must be provided.

|===

[[h3_287654427]]
==== Level Based on Filter Items

Specify[.apiobject]#operator# and[.apiobject]#items#
values that are used to check if values on[.object]#Order Line
Items# are a match.



The format is the same as for
the xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-conditiondetails-c-field-specification[orders__ConditionDetails__c] field.

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#field# |String |Yes |The field from the
[.object]#Order Line Item# or its parent object for which the
[.apiobject]#operator# key is applied.

|[.apiobject]#operator# |Enum |Yes |See
xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/condition-advancedcriteria-c-field-specification#h3_1330481294[Items
Operators].

|[.apiobject]#value# |Boolean |No |A target value for fields
with the *Boolean* type.

| |Number | |A target value for fields with the *Currency* or *Number*
type.

| |String | a|
A target value for fields with the *Text* type.



The key is required when the [.apiobject]#operator# key is
not [.apiobject]#in# or [.apiobject]#notIn#.

|[.apiobject]#values# |Array of Values |No a|
the [.apiobject]#values# with the *Text* type, separated by a
comma, for example:[.apiobject]#["abc","123"]#

[.apiobject]#
#

[.apiobject]#At least one item must be provided. The key is
required when the #[.apiobject]#operator# key
is [.apiobject]#in# or [.apiobject]#notIn#.

|===

[[h3_1330481294]]
==== Item Operators

[width="100%",cols="10%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%",]
|===
|*Field Data Type* |*Operator* | | | | | | | | |

| |*contain* |*notContain* a|
*in*

|*notIn* |*equal* |*notEquel* a|
*greater*

|*greaterOrEqual* a|
*less*

a|
*lessOrEqual*

|*Currency* |No |No |No |No |Yes |Yes |Yes |Yes |Yes
a|
Yes

|*Number* |No |No |No |No |Yes |Yes |Yes |Yes |Yes
a|
Yes

|*Text* a|
Yes

|Yes |Yes |Yes |Yes |Yes |No |No |No |No
|===
