= Additional Permissions to Override the Standard Logic

In addition to the required permissions, administrators can assign
additional link:https://help.salesforce.com/s/articleView?id=sf.custom_perms_overview.htm&type=5[custom permissions] to certain users according to the desired business logic.

[[h2__1759465302]]
== Allow the same Calculation Types in the Pricing Procedure steps

This custom permission allows you to use the same xref:admin-guide/managing-ct-orders/discount-management/calculation-types.adoc[Calculation Type] in multiple steps of one xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-2/pricing-procedure-v-2-steps/index.adoc[pricing procedure].

NOTE: The xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/calculated-discount-field-reference.adoc[Calculation Discount] record will store the discount based on the last step of the pricing procedure. It is recommended to use xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-2/pricing-procedure-v-2-steps/step-conditions.adoc[conditions for pricing procedure steps] when assigning this permission to avoid double triggering the same Calculation Type.

[[h2_1283392283]]
== Allow Сhanging Condition Details of Promotion

This custom permission allows you to edit the *Condition Details* field of the xref:admin-guide/managing-ct-orders/freebies-management/freebie-data-model/freebie-condition-field-reference/index.adoc[Freebie Condition] object and the *Condition Details* and *Advanced Criteria* fields of the xref:admin-guide/managing-ct-orders/discount-management/discount-data-model/condition-field-reference/index.adoc[Condition] object if [.object]#Promotion# is defined.

NOTE: When assigning this permission, consider that it may affect promotions.
