= Creating CLM Presentation from PowerPoint

ifdef::ios[][NOTE] ==== Since CT Mobile 2.2, the CLM
presentation converting from the[.apiobject]#.ppt(x) ==== file
will be displayed against a black background, and slides, which size is
less than the screen area, will be aligned to the center of the screen.
#

The Application Editor allows the creation of CLM presentations from
PowerPoint files.

* Supported files:[.apiobject]#.ppt# with files,
[.apiobject]#.ppt(x)# with files.
* https://support.office.com/en-us/article/embed-fonts-in-word-or-powerpoint-cb3982aa-ea76-4323-b008-86670f222dbc?omkt=en-US&ui=en-US&rs=en-US&ad=US#OfficeVersion=macOS[Embed
fonts] in a CLM presentation to be sure that the fonts, special
characters, layout, and styling of the document won't change while
sharing.
* The size of the CLM presentation must not exceed 25 MB.
* If a[.apiobject]#.ppt(x)# file contains any interactive
elements, such as videos, gifs, and links, they will not be available in
the converted CLM presentation.
* ​Slides animation from converted[.apiobject]#.ppt# files is
not supported.
* Violation of converted slides' proportion is possible when other than
iPad format slides are used in the source document.



To convert a PowerPoint file into a CLM presentation:
