= Person Accounts

CT Mobile app allows working with
https://help.salesforce.com/articleView?id=account_person.htm&r=https%3A%2F%2Fwww.google.com%2F&type=5[Person
Accounts]. *Person Accounts* store information about individual people
by combining certain[.object]#Account# and
[.object]#Contact# fields into a single record.

[[h2_693098374]]
=== Enable Person Accounts

To enable *Person Accounts* functionality:

. https://help.salesforce.com/articleView?id=account_person_enable.htm&type=5[Enable
Person Accounts] for the Salesforce org.​
After Person Accounts are enabled, a *Person Account* record type is
created.
https://help.salesforce.com/articleView?id=users_profiles_record_types.htm&type=5&language=en_US[Assign
the person account record type to user profiles].
. Enable Person Accounts in
link:ct-mobile-control-panel-general.html#h3_471160840[CT Mobile Control
Panel:
General]/link:ct-mobile-control-panel-general-new.html#h3_471160840[CT
Mobile Control Panel 2.0: General] for the appropriate user profile.
. ​Go to link:ct-mobile-control-panel-app-menu.html[CT Mobile Control
Panel: App Menu]/link:ct-mobile-control-panel-app-menu-new.html[CT
Mobile Control Panel 2.0: App Menu] and add *Account* and *Contact* to
the *Selected* list in the required order.

The setup is complete.

To view only appropriate records on the *Related Accounts* tab in the CT
Mobile app, specify the [.topBar .object]#Account Contact Relation#
object in the
link:ct-mobile-control-panel-general.html#h3_494016929[Reference Object
API Name] field.

[[h2__1162752891]]
=== Using Person Accounts in the CT Mobile app

The *Person Accounts* records are listed in the *Contacts* menu item.

* Configure and assign link:mini-layouts.html[a mini-layout] for the
Person Account record type to create new records.
* Configure list views for *Person Accounts* by including the *Is Person
Account* field in the filter criteria.



ifdef::ios,andr,win[]

For activity management, correct operation of the
link:calendar.html[Calendar] module, the
link:applications.html[Applications] module, and the CT Mobile app in
general, the[.object]#Activity# objects must contain the
relationships with the[.object]#Contact# object, available to a
user.

ifdef::kotlin[]

For activity management, correct operation of the
link:calendar.html[Calendar] module and the CT Mobile app in general,
the[.object]#Activity# objects must contain the relationships
with the[.object]#Contact# object, available to a user.
