= Synchronization in the Background

https://docs.google.com/document/d/1_zscUv_Xu5_tE__eEK3DoX81xlU-S9RT61xcnYGpkhc/edit[Sync
Limits Whitepaper]



Статья с ограничениями по загрузке в бэкграунде

* best practice
** запускайте фулл синк в зависимости от ваших изменений раз в неделю в
пн или пт в начале/в конце рабочего дня при стабильном
интернет-соединении (например, вай-фай), нормальной проценте зарядки,
т.к. при фулл идёт большая передача данных
** для ускорения и уменьшения количества данных, используйте
сокл-фильтры, чтобы загружать только необходимые данные пользователю
** каждый день с утра/после работы проводите фаст синк, чтобы передать
все офлайн-данные в сейлсфорс 
** Релизы редко → фаст каждый день, миксд/фулл на определённый день 

* как релизиться с микс синхрой
** Вместо фулл → миксд → сокл фильтры 
** Фаст синх раз в день 
* cинхра на записи
** Релизы часто → Используйте синхронизацию по записи 
* что делать, если синхра прервалась из-за бэкграунда
* по всем вопросам → почта саппорта продукта?



Фулл синхра идёт сколько-то минимально/в среднем

Фаст синхра в среднем

Миксд синхра в среднем
