= User Permissions Required to Synchronize Objects to Offline Work with Functionalities

[TIP] ==== Launch link:full-synchronization.html[the full
synchronization] to download these objects to the mobile device. ====

Tap the header to open the corresponding table.

[width="100%",cols="50%,50%",]
|===
|User permissions for objects that are always downloaded during
synchronization a|
ifdef::ios[]

[width="100%",cols="^25%,^25%,^25%,^25%",]
!===
!*Object* !*Object API Name* !*User Permission* !*Comments*

!Account ![.apiobject]#Account# !Read !

!Assignment Rule ![.apiobject]#AssignmentRule# !Read !If active.

!CTM Settings ![.apiobject]#clm__CTMSettings__c# !Read
!

!Document ![.apiobject]#Document# !Read !It is required to
display the CT Mobile logo (refer to
link:ct-mobile-control-panel-general.html#h3_1354766135[CT Mobile
Control Panel: General] or
link:ct-mobile-control-panel-user-interface-new.html#h3_1354766135[CT
Mobile Control Panel 2.0: User Interface]).

!Email Template ![.apiobject]#EmailTemplate# !Read !If active.

!Folder ![.apiobject]#Folder# !Read !To display
correctly, [.apiobject]#Dashboard# and [.apiobject]#EmailTemplate# are
required.

!Group ![.apiobject]#Group# !Read !

!Record Type ![.apiobject]#RecordType# !Read !

!Sync Log ![.apiobject]#clm__SyncLog__c# !Read; Edit !

!User ![.apiobject]#User# !Read !If active.

!User Permission Access ![.apiobject]#UserPermissionAccess#
!Read !

!User Role ![.apiobject]#UserRole# !Read !
!===

ifdef::kotlin[]

[width="100%",cols="^25%,^25%,^25%,^25%",]
!===
!*Object* !*Object API Name* !*User Permission* !*Comments*

!Account ![.apiobject]#Account# !Read !

!Document ![.apiobject]#Document# !Read !

!Email Template ![.apiobject]#EmailTemplate# !Read !

!Folder ![.apiobject]#Folder# !Read !

!Group ![.apiobject]#Group# !Read !

!Record Type ![.apiobject]#RecordType# !Read !

!Sync Log ![.apiobject]#clm__SyncLog__c# !Read; Edit !

!User ![.apiobject]#User# !Read !If active.

!User Permission Access ![.apiobject]#UserPermissionAccess#
!Read !
!===

|User permissions for objects that are required for the correct offline
operation of the added functionalities and integrations a|
ifdef::ios[]

[width="100%",cols="^20%,^20%,^20%,^20%,^20%",]
!===
!*Functionality/Integration* !*Object* !*Object API Name* !*User
Permission* !*Comments*

!link:applications.html[Applications] !Application
![.apiobject]#clm__Application__c# !Read; Edit !

! !Application Stats
![.apiobject]#clm__ApplicationStats__c# !Read !

! !Custom Scenario ![.apiobject]#clm__CustomScenario__c#
!Read; Edit !

! !Slide ![.apiobject]#clm__Slide__c# !Read !

!link:cg-cloud.html[CG Cloud]
!link:activating-cg-cloud-in-the-ct-mobile-app.html#h2_242799573[The
list of CG Cloud objects] !— !— !

!https://help.customertimes.com/smart/project-ct-sign-en/add-the-ct-sign-to-the-ct-mobile-app[CT
Sign] !Sign Document
![.apiobject]#ctsign__SignDocument__c# !Read !

! !Sign Settings ![.apiobject]#ctsign__SignSettings__c#
!Read; Edit !

!https://help.customertimes.com/articles/ct-orders-4-0/adding-ct-orders-to-the-ct-mobile-app-4-0[CT
Orders] !Group ![.apiobject]#Group# !Read !

!
!https://help.customertimes.com/articles/ct-orders-4-0/offline-order/a/h2_1850278800[The
list of CT Orders objects] !— !— !

!link:home-screen.html#h3__1761919763[Dashboards] (online) !Dashboard
![.apiobject]#Dashboard# !Read !

! !Report ![.apiobject]#Report# !Read !

! !Report Type ![.apiobject]#ReportType# !Read ! !link:lead-convert.html[Lead] !Lead Status ![.apiobject]#LeadStatus# !Read !If the list of offline objects
contains the _Lead_ object.

!link:managing-offline-objects.html[Offline Objects] !The list of
offline objects !— !Read; Edit; Delete (depend on the object) !It is
based on data from
link:related-list-filters.html[clm__RelatedListFillters__c],
link:menu-settings-and-offline-objects.html[clm__TopLvlObjects__c]
(will be deprecated in future), or link:ctm-settings.html[CTM Settings].

! !Task Status ![.apiobject]#TaskStatus# !Read; Edit !If the
list of offline objects contains the _Task_ object.

!link:opportunities.html[Opportunity] !Opportunity
![.apiobject]#Opportunity# !Read !If the list of offline
objects contains the _Order_ and _Quote_ objects.

! !Opportunity Product ![.apiobject]#OpportunityLineItem# !Read
!If the list of offline objects contains the _Opportunity_ object.

!https://help.customertimes.com/smart/project-order-module/order-management[Order]
!Order Product ![.apiobject]#OrderItem# !Read !If the list of
offline objects contains the _Order_ object.

! !Price Book ![.apiobject]#Pricebook2# !Read !If the list of
offline objects contains the _Order_ and _Opportunity_ objects.

! !Price Book Entry ![.apiobject]#PricebookEntry# !Read !If the
list of offline objects contains the _Order_ and _Opportunity_ objects.

! !Salesforce Product ![.apiobject]#Product2# !Read !If the list
of offline objects contains the _Order_ and _Opportunity_ objects.

!Quote !Quote ![.apiobject]#Quote# !Read !If the list of
offline objects contains the _Quote_ object.

! !Quote Line Item ![.apiobject]#QuoteLineItem# !Read !If the
list of offline objects contains the _Quote_ object.
!===

ifdef::kotlin[]

[width="100%",cols="^20%,^20%,^20%,^20%,^20%",]
!===
!*Functionality/Integration* !*Object* !*Object API Name* !*User
Permission* !*Comments*

!link:home-screen.html#h3__1761919763[Dashboards] (online) !Dashboard
![.apiobject]#Dashboard# !Read !

!link:managing-offline-objects.html[Offline Objects] !The list of
offline objects !— !Read; Edit; Delete (depend on the object) !It is
based on data from
link:related-list-filters.html[clm__RelatedListFillters__c] and
link:menu-settings-and-offline-objects.html[clm__TopLvlObjects__c].

! !Task Status ![.apiobject]#TaskStatus# !Read; Edit !If the
list of offline objects contains the _Task_ object.

!link:opportunities.html[Opportunity] !Opportunity
![.apiobject]#Opportunity# !Read !If the list of offline
objects contains the _Opportunity_ object.

! !Opportunity Product ![.apiobject]#OpportunityLineItem# !Read
!If the list of offline objects contains the _Opportunity_ object.

! !Price Book ![.apiobject]#Pricebook2# !Read !If the list of
offline objects contains the _Opportunity_ object.

! !Price Book Entry ![.apiobject]#PricebookEntry# !Read !If the
list of offline objects contains the _Opportunity_ object.

! !Salesforce Product ![.apiobject]#Product2# !Read !If the list
of offline objects contains the _Opportunity_ object.
!===

|User permissions to download custom settings and custom metadata types
a|
ifdef::ios[]

[cols="^,^,^",]
!===
!*Custom Setting or Custom Metadata Type* !*API Name* !*User Permission*

!Menu Settings and Offline Objects
![.apiobject]#clm__TopLvlObjects__c# !Read

!Mobile Application Setup
![.apiobject]#clm__ApplicationSetup__c# !Read

!Mobile Custom Detail Settings
![.apiobject]#clm__MobileActivityDataCustomization__c#
!Read

!Mobile Customization
![.apiobject]#clm__MobileCustomization__c# !Read

!Mobile Mini Layout Settings
![.apiobject]#clm__MobileLayoutSettings__c# !Read

!Related List Filters
![.apiobject]#clm__MobileRelatedListFilters__c# !Read

!CT Mobile Replication
![.apiobject]#clm__Replication__mdt# !Read

!CT Mobile Workflow ![.apiobject]#clm__Workflow__mdt#
!Read

!CT Mobile Workflow Step
![.apiobject]#clm__WorkflowStep__mdt# !Read
!===

ifdef::kotlin[]

[cols="^,^,^",]
!===
!*Custom Setting or Custom Metadata Type* !*API Name* !*User Permission*

!Menu Settings and Offline Objects
![.apiobject]#clm__TopLvlObjects__c# !Read

!Mobile Application Setup
![.apiobject]#clm__ApplicationSetup__c# !Read

!Mobile Custom Detail Settings
![.apiobject]#clm__MobileActivityDataCustomization__c#
!Read

!Mobile Customization
![.apiobject]#clm__MobileCustomization__c# !Read

!Mobile Mini Layout Settings
![.apiobject]#clm__MobileLayoutSettings__c# !Read

!Related List Filters
![.apiobject]#clm__MobileRelatedListFilters__c# !Read

!CT Mobile Replication
![.apiobject]#clm__Replication__mdt# !Read
!===

|===
