= Visualizing Information with Emoji

CT Mobile allows you to use emoji in titles, subtitles, and layouts to
visualize record information. You can use emoji for better reading of
essential information. Divide records by any parameter you need—divide
_Leads_ by territories, calculate the rep's KPI, and more—and illustrate
it.  



Add emoji code in a field with the *Formula* type to display it with the
calculated value.

* use[.apiobject]#IF# or[.apiobject]#CASE# operator
* calculate either based on a specified value or using a complex formula
based on several fields. You can use a single formula to illustrate the
rep's KPI and, e.g.,[.object]#Account# rating.



For example, see the customized *Contact Priority* formula from
https://help.salesforce.com/s/articleView?id=sf.useful_advanced_formulas_contact_mgmt.htm&type=5[Sample
Contact Management Formulas]:



Or simply add emoji based on a value in the specified field:





The full list of emoji codes is
available https://unicode.org/emoji/charts/full-emoji-list.html[here].
