= CT Product Field Reference

The **[.object]#CT Product# object is intended to
store detailed information regarding company and competitor products,
including their physical parameters and quantity.

xref:admin-guide/configuring-ct-products-and-assortments/ref-guide/index#h2__160781133[The _CT
Product_ record types] are used to distinguish _CT Products_ by purpose.



For the
https://help.customertimes.com/articles/project-order-module/ct-orders-solution[CT
Orders] functionality, it also stores Quantity per delivery settings and
specific attributes that define the price calculation procedure. 

'''''

API name in Salesforce: `CTCPG__Product__c`

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Active |`CTCPG__IsActive__c` |Checkbox |If selected, the record
is active and applied in business logic.

|Brand |`CTCPG__Brand__c` |Picklist a|
Brand of a product. The available values:

* _First Brand_
* _Second Brand_
* _Third Brand_

|Bundle |​​`CTCPG__IsBundlee__c` |Checkbox |If selected,
xref:admin-guide/configuring-ct-products-and-assortments/ref-guide/product-component-field-reference[the product is a part of a
bundle].

|Calculate Price On a|
`CTCPG__CalculatePriceLevel__c`



|Picklist a|
Defines the source for a price in the order. The available values: 

* _Header_
* _Components_

|Category |`CTCPG__Category__c` |Picklist a|
Product category. The available values:

* _Dairy_
* _Nutrition_

|Default Availability Type |CTCPG__Default Availability
Type__c |Picklist a|
It
defines https://help.customertimes.com/articles/project-order-module/product-availability[whether
a product is available] by default. Available values:

* _Available_ 
The value will be set by default during the CT Orders package
installation or update.
* _Not Available_

|Description |`​​[.apiobject]#CTCPG__Description__c#`
|Long Text Area(32768) |Description of a product.

|External Id a|
`CTCPG__ExternalId__c`



|Text(255) (External ID) (Unique Case Sensitive) |Product external
identifier if integration is set up.

|Family |`CTCPG__Family__c` |Picklist a|
Product family. The available values:

* _First Family_
* _Second Family_
* _Third Family_

|Height(mm) |`CTCPG__Heigth__c` |Number (18, 0) |Product
physical parameter: height in millimeters. 

|Ignore Component Availability
|[.apiobject]#orders__isIgnoreComponentAvailability__c#
|Checkbox a|
Applied for bundle components only.

If _true_, the bundle component always available by *Product
Availability* and *Default Availability Type* fields.

Default value: _false_.

|Max Quantity Per Delivery
|`CTCPG__MaxQuantityPerDelivery__c` |Number(18, 0) |Max
limit of products for delivery. 
The quantity must correspond to the units in package value if
applied. Must be greater than *Min Quantity Per Delivery*.

|Min Quantity Per Delivery
|`CTCPG__MinQuantityPerDelivery__c` |Number(18, 0) 
|Min limit of products for delivery. 
The quantity must correspond to the units in package value if
applied. Must be less than *Max Quantity Per Delivery*.

|Parent |`CTCPG__ParentId__c` |Lookup(CT Product) |Parent
product from a bundle/catalog.

|Set Quantity On a|
`CTCPG__SetQuantityLevel__c`



|Picklist a|
Defines the source for product quantity in the order. The available
values: 

* _Header_
* _Components_

|Type |`CTCPG__Type__c`​​ |Picklist  a|
A product type. The available values:

* _Type 1_
* _Type 2_
* _Type 3_

|Units in Package |`CTCPG__UnitsInPackage__c` |Number(18,
0)  |The ratio of adding a product.
For example, if this number is 5, that means 5 units of this product
will be added when clicking the "plus"({plus}) button on
https://help.customertimes.com/articles/project-order-module/order-line-item-field-reference[the
order quantity field]. 

|Use Freebie Multiplier |CTCPG__IsUseFreebieMultiplier__c
|Checkbox |If selected, the freebies will be added with the specified
multiplicity to the product amount.

|Weight (gr) |`CTCPG__Weight__c` |Number(16,2) |Product
physical parameter: weight in grams.

|Width (mm) |`CTCPG__Width__c` |Number(16,2) |Product
physical parameter: width in millimeters.
|===
