= CT Mobile Solution

СT Mobile is a mobile app for field sales reps and agents. It is native
to Salesforce and provides full Salesforce offline functionality along
with an advanced interactive Digital Sales Aid, otherwise referred to as
Closed Loop Marketing (CLM). A combination of Salesforce offline
features and interactive customer engagement makes CT Mobile a
disruptive sales tool, boasting all main sales KPIs, such as sales close
rate, customer loyalty, lead-to-cash time, etc. 

* link:android/ct-mobile-solution/ct-mobile-description-and-deployment[CT Mobile Description
and Deployment]
* link:technical-requirements-for-devices-and-network.html[Technical
Requirements for Devices and Network]
* link:recommendations-and-peculiarities.html[Recommendations for API
Names of Objects and Fields and Peculiarities of Working with Some Types
of Fields]



For your convenience, we prepared a guide in the following format:

* In the link:android/news/ct-mobile-news[News] section, we share with you the
latest CT Mobile updates, release notes, and Salesforce updates that
affect our CT Mobile solution.
* link:android/quick-reference-guides/quick-reference-guides[Quick Reference Guides] is a peek
into the CT Mobile setup. The articles are arranged in order from
installation to customization. Follow the steps in the article to set up
the CT Mobile app. 
* link:android/knowledge-base/knowledge-base[Knowledge Base] is a complete CT Mobile
guide, divided into:
** link:android/knowledge-base/configuration-guide/configuration-guide[Configuration Guide] is intended to
introduce all CT Mobile settings on the Salesforce side and how to
configure functionality available in the CT Mobile package.
** The link:android/knowledge-base/mobile-application/mobile-application[Mobile Application] section
describes the settings and functionalities available in the CT Mobile
app.
** The link:android/knowledge-base/ct-presenter/ct-presenter[CT Presenter] section is intended to
familiarize you with creating, managing, and displaying CLM
presentations in the CT Mobile app or through a co-browsing session. 
