= Step Conditions

Each step's item will be calculated only if the conditions of the step are met or if there are no conditions for the step.

[[h2_136084655]]
== Condition Level Keys

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#operator# |Enum |Yes a|
Available values:

* AND
* OR

|[.apiobject]#items# |Array |Yes |At least one item of the Condition Level or Condition Level Item object must be provided.
|===

[[h2_625014080]]
== Condition Level Item keys

[width="100%",cols="15%,20%,10%,55%"]
|===
|*Key* |*Type* |*Required* |*Comment*

|[.apiobject]#field# |String |Yes
|xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-2/pricing-procedure-v-2-steps/step-conditions.adoc#h2_680034043[The value] in the [.apiobject]#object# key to check. See xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-2/pricing-procedure-available-field-formats.adoc[Available Field Formats].

|[.apiobject]#operator# |Enum |Yes
|xref:admin-guide/managing-ct-orders/price-management/ref-guide/pricing-procedure-v-2/pricing-procedure-v-2-steps/step-conditions.adoc#h2_748327130[Available operators] depending on the field data type.

|[.apiobject]#value# |Boolean |No |Target values for fields with the *Boolean* data type.

| |Number | |Target values for fields with the *Currency* and *Number* data type.

| |String | a|
Target values for fields with the *Text* data type.

NOTE: The key is required if [.apiobject]#"operator" != "in"# or [.apiobject]#"operator "!= "notIn"#.

|[.apiobject]#values# |Array |No a|
Target values for fields with the *Text* data type.

[NOTE]
====
* The key is required if [.apiobject]#"operator" == "in"# or [.apiobject]#"operator "== "notIn"#.
* At least one item is required.
====
|===

[[h2_748327130]]
== Condition Operators

Check which operators can be used with the available field data types.

NOTE: The [.apiobject]#in# and [.apiobject]#notIn# keys must contain multiple values separated by commas.

[.highlighted-table]
[width="100%",cols="10%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%,^9%",]
|===

.2+|*Field Data Type* 10+|*Operator* |*contain* |*notContain* | *in* |*notIn* |*equal* |*notEqual* a| *greater* |*greaterOrEqual* | *less* | *lessOrEqual* |*Currency*

|No |No |No |No |Yes |Yes |Yes |Yes |Yes |Yes

|*Number* |No |No |No |No |Yes |Yes |Yes |Yes |Yes | Yes

|*Text* | Yes

|Yes |Yes |Yes |Yes |Yes |No |No |No |No
|===

[[h2_680034043]]
== Value in the Object Key

[width="100%",cols="50%,50%",]
|===
|*Value* |*CT Orders Object*

|[.apiobject]#procedure# |[.object]#Delivery Line Item#

|[.apiobject]#setValue# |a value in the [.apiobject]#object# key

|[.apiobject]#rollUp# |a value in the [.apiobject]#object# key

|[.apiobject]#drillDown# |a value in the [.apiobject]#object# key
|===

[[h2_1406500097]]
== Examples

Click to view:

* Standard AND condition:
+
[%collapsible]
====
--
[source,json]
----
{
    "operator": "AND",
    "items": [
        {
            "field": "orders__ManualDiscount__c",
            "operator": "greater",
            "value": 0
        },
        {
            "field": "CTCPG__ParentProductExternalId__c",
            "operator": "in",
            "values": [
                "40011",
                "40312"
            ]
        }
    ]
}
----
--
====

* Standard OR condition:
+
[%collapsible]
====
--
[source,json]
----
{
    "operator": "OR",
    "items": [
        {
            "field": "orders__ManualDiscount__c",
            "operator": "greater",
            "value": 0
        },
        {
            "field": "CTCPG__PromotionId__c",
            "operator": "notEqual",
            "value": ""
        }
    ]
}
----
--
====

* Standard complex condition:
+
[%collapsible]
====
--
[source,json]
----
{
    "operator": "AND",
    "items": [
        {
            "field": "orders__ManualDiscount__c",
            "operator": "greater",
            "value": 0
        },
        {
            "operator": "OR",
            "items": [
                {
                    "field": "CTCPG__PromotionId__c",
                    "operator": "notEqual",
                    "value": ""
                },
                {
                    "field": "CTCPG__PromotionId__c",
                    "operator": "notEqual",
                    "value": ""
                }
            ]
        }
    ]
}
----
--
====
