= Related Lists

Related lists are tabular forms for displaying records related to
another record if one object has a link to another object in
xref:reference-fields[the reference field]. In the CT Mobile app,
two types of related lists are available:

* xref:custom-related-lists[Custom Related Lists]
* xref:standard-related-lists[Standard Related Lists]

[[h2_384095523]]
=== Related List Features Comparison

Here is a table to help you understand the difference between standard
and custom related lists: how to set up related lists in Salesforce and
what features could be available in the CT Mobile app.



[width="100%",cols="25%,25%,25%,25%",]
|===
|*Feature* |*Standard Related List* |*Custom Related List* |*Notes*

|Set up a related list with the page layout editor |{plus} |– a|
* https://help.salesforce.com/articleView?id=customizing_related_lists.htm&type=5[Add
and customize a standard related list] on the page layout of the
required object.
* Not applicable for a custom related list.

|Set up a related list on CT Mobile Control Panel |{plus} |{plus} a|
* Go to xref:ct-mobile-control-panel-offline-objects[CT Mobile
Control Panel: Offline
Objects]/xref:ct-mobile-control-panel-offline-objects-new[CT Mobile
Control Panel 2.0: Offline Objects] to customize a standard related
list;
* Go to xref:ct-mobile-control-panel-custom-details[CT Mobile
Control Panel: Custom
details]/xref:ct-mobile-control-panel-custom-details-new[CT Mobile
Control Panel 2.0: Custom Details] to customize a custom related list.

|Create a record |{plus} |{plus} a|
Grant permission:

* on xref:ct-mobile-control-panel-offline-objects[CT Mobile Control
Panel: Offline
Objects]/xref:ct-mobile-control-panel-offline-objects-new[CT Mobile
Control Panel 2.0: Offline Objects] for a standard related list;
* on xref:ct-mobile-control-panel-custom-details[CT Mobile Control
Panel: Custom
details]/xref:ct-mobile-control-panel-custom-details-new[CT Mobile
Control Panel 2.0: Custom Details] for a custom related list.

Object permissions restrict common access permissions defined by the
user profile. The current user profile should have permission to edit
the selected offline objects.

|Delete a record |{plus} |{plus} a|
Grant permission:

* on xref:ct-mobile-control-panel-offline-objects[CT Mobile Control
Panel: Offline
Objects]/xref:ct-mobile-control-panel-offline-objects-new[CT Mobile
Control Panel 2.0: Offline Objects] for a standard related list;
* in xref:ct-mobile-control-panel-custom-details[CT Mobile Control
Panel: Custom
details]/xref:ct-mobile-control-panel-custom-details-new[CT Mobile
Control Panel 2.0: Custom Details] for a custom related list.

Object permissions restrict common access permissions defined by the
user profile. The current user profile should have permission to delete
the selected offline objects.

ifdef::ios[] ifdef::win[]The mobile user can delete
unsynchronized records regardless of granted permission.

|Edit field values |– |{plus} a|
* Not applicable for a standard related list;
* Go to xref:custom-related-lists#h2__773495381[Custom Related
Lists] to add the ability for editing fields of a custom related list.

|Drilldown to record details screen |{plus} |{plus} a|
* Available by default and cannot be disabled for a standard related
list;
* Grant permission on
xref:ct-mobile-control-panel-custom-details[CT Mobile Control
Panel: Custom
details]/xref:ct-mobile-control-panel-custom-details-new[CT Mobile
Control Panel 2.0: Custom Details] for custom related list.

|Control columns' width |{plus} |{plus} |ifdef::ios,kotlin[] For
more information, go to
xref:columns-width-for-related-lists[Columns' Widths for Standard
and Custom Related Lists]. ifdef::win,andr[][NOTE] ==== Not
in use. ====

|Filter records by using a SOQL query |{plus} |{plus} a|
In the CT Mobile app, switch between the display of all records or only
records that match filter criteria.

ifdef::kotlin[] ifdef::win[][NOTE] ==== Not applicable
for standard related lists. ====

|Timeline view |{plus} |– |ifdef::ios[] For more information, go to
xref:timeline-view[Timeline View]. ifdef::win,andr,kotlin[]
[NOTE] ==== Not in use. ====

|The sort order by the specific field |{plus} |{plus} |Tap the column
title to sort records by this field. For more information, go to
xref:filters-in-related-lists[Filters in Related Lists].
|===
