= Remote Detailing Setup

Configure the *Remote Detailing* functionality according to the
appropriate mode, and, optionally, specify the Remote Detailing logo for
the participant's *Waiting...* screen.

:toc: :toclevels: 3

[[h2_1279002041]]
=== Remote Detailing

Follow the steps to configure
xref:ios/ct-presenter/the-remote-detailing-functionality/index.adoc#h2_1279002041[the Remote
Detailing functionality]:

[width="100%",cols="50%,50%",]
|===
|In CT Mobile Control Panel a|
. Check that the presenter profile should have access to
the [.apiobject]#clm.Rest_OnlinePresenter# class, to
the xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[Application], xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-applicationstats.adoc[Application
Stats], xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-slide.adoc[Slide],
and xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-customscenario.adoc[Custom Scenario] objects. To obtain
access,
assign xref:ios/getting-started/application-permission-settings.adoc#ApplicationPermissionSettings-PermissionSets[one
of the pre-configured permission sets].
. Check xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-tools/index.adoc#CloudToken[the cloud
token] is specified and valid.
. Check that the records per each trigger are active in
xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/trigger-settings.adoc[Trigger Settings].
. Specify access to the CLM presentation(s) for Remote Detailing users.
. On the *CT Mobile Control Panel: Calendar* tab, specify
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-calendar.adoc#h3_1397263211[the API name of
the Activity object] and
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-calendar.adoc#h3_1674628596[the API name
for the Activity Start Date field].
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h2_249047963[Add
the Apex trigger and classes] to provide statistics collecting and
generate the invite link. For the Apex trigger, specify the API name of
the [.object]#Activity# object from step 4.
. On the *CT Mobile Control Panel: Presenter* tab,
xref:ct-mobile-control-panel-presenter#h2_985373192[enable the
Remote Detailing functionality] and specify options.
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h3_848494787[Add
the Applications button] to create the CLM presentation set for an
[.object]#Activity# object in Lightning Experience.
. xref:remote-detailing-setup#h2_1821657178[Specify a logo] for the
participant's *Waiting...* screen.
. Specify the ways xref:remote-detailing-launch[to launch the
Remote Detailing meeting] in Salesforce and the CT Mobile app.

|In CT Mobile Control Panel 2.0 a|
. Check that the presenter profile should have access to
the [.apiobject]#clm.Rest_OnlinePresenter# class, to
the xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-application.adoc[Application], xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-applicationstats.adoc[Application
Stats], xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-slide.adoc[Slide],
and xref:ios/ct-presenter/about-ct-presenter/clm-scheme/clm-customscenario.adoc[Custom Scenario] objects. To obtain
access,
assign xref:ios/getting-started/application-permission-settings.adoc#ApplicationPermissionSettings-PermissionSets[one
of the pre-configured permission sets].
. Check xref:ct-mobile-control-panel-tools-new#h2_2011978[the cloud
token] is specified and valid.
. Check that the records per each trigger are active in
xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/trigger-settings.adoc[Trigger Settings].
. Specify access to the CLM presentation(s) for Remote Detailing users.
. On the *CT Mobile Control Panel: Activities* tab, specify
the xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-activities-new.adoc#h2_2014841429[Activity
object] and
its xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-activities-new.adoc#h4_1766544266[Start
Date field].
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h2_249047963[Add
the Apex trigger and classes] to provide statistics collecting and
generate the invite link. For the Apex trigger, specify the API name of
the [.object]#Activity# object from step 4.
. On the xref:ct-mobile-control-panel-remote-detailing-new[CT
Mobile Control Panel: Remote Detailing] tab, enable the Remote Detailing
functionality and specify its options.
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h3_848494787[Add
the Applications button] to create the CLM presentation set for an
[.object]#Activity# object in Lightning Experience.
. xref:remote-detailing-setup#h2_1821657178[Specify a logo] for the
participant's *Waiting...* screen.
. Specify the ways xref:remote-detailing-launch[to launch the
Remote Detailing meeting] in Salesforce and the CT Mobile app.

|===

[[h2_1854710639]]
=== Self Detailing

Follow the steps to configure
xref:ios/ct-presenter/the-remote-detailing-functionality/index.adoc#h2_1854710639[the Self
Detailing functionality]:

[width="100%",cols="50%,50%",]
|===
|In CT Mobile Control Panel a|
. Check xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-tools/index.adoc#CloudToken[the cloud
token] is specified and valid.
. Check that the records per each trigger are active in
xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/trigger-settings.adoc[Trigger Settings].
. Specify access to the CLM presentation(s) for Self Detailing users.
. On the *CT Mobile Control Panel: Calendar* tab, specify
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-calendar.adoc#h3_1397263211[the API name of
the Activity object] and
xref:ios/admin-guide/ct-mobile-control-panel/ct-mobile-control-panel-calendar.adoc#h3_1674628596[the API name
for the Activity Start Date field].
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h2_249047963[Add
the Apex trigger and classes] to provide statistics collecting and
generate the invite link. For the Apex trigger, specify the API name of
the [.object]#Activity# object from step 3.
. According to the CT Mobile package version:


[width="100%",cols="50%,50%",]
!===
!*CT Mobile package below v. 3.63* !*CT Mobile package v. 3.63 or
higher*

! !
!===


. On the *CT Mobile Control Panel: Presenter* tab,
xref:ct-mobile-control-panel-presenter#h2_985373192[enable the
Remote Detailing functionality], specify options, and
xref:ct-mobile-control-panel-presenter#h2_891805269[refresh CLM
presentations].
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h3_848494787[Set
up a quick action] to create the CLM presentation set for an
[.object]#Activity# object in Lightning Experience.
. xref:remote-detailing-setup#h2_1821657178[Specify a logo] for the
participant's *Waiting...* screen.
. Specify the ways xref:remote-detailing-launch[to launch the Self
Detailing meeting] in Salesforce and the CT Mobile app.
. Additionally, create a process to send the invite link to participants
by SMS, e-mail, etc.

|In CT Mobile Control Panel 2.0 a|
. Check xref:ct-mobile-control-panel-tools-new#h2_2011978[the cloud
token] is specified and valid.
. Check that the records per each trigger are active in
xref:ios/admin-guide/ct-mobile-control-panel/custom-settings/trigger-settings.adoc[Trigger Settings].
. Specify access to the CLM presentation(s) for Self Detailing users.
. On the *CT Mobile Control Panel: Activities* tab, specify
the xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-activities-new.adoc#h2_2014841429[Activity
object] and
its xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-activities-new.adoc#h4_1766544266[Start
Date field].
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h2_249047963[Add
the Apex trigger and classes] to provide statistics collecting and
generate the invite link. For the Apex trigger, specify the API name of
the [.object]#Activity# object from step 3.
. On the xref:ct-mobile-control-panel-remote-detailing-new[CT
Mobile Control Panel: Remote Detailing] tab, enable the Remote Detailing
functionality and specify its options.
. xref:remote-detailing-apex-trigger-classes-and-quick-action#h3_848494787[Set
up a quick action] to create the CLM presentation set for an
[.object]#Activity# object in Lightning Experience.
. xref:remote-detailing-setup#h2_1821657178[Specify a logo] for the
participant's *Waiting...* screen.
. Specify the ways xref:remote-detailing-launch[to launch the Self
Detailing meeting] in Salesforce and the CT Mobile app.
. Additionally, create a process to send the invite link to participants
by SMS, e-mail, etc.

|===

[[h2_1821657178]]
=== Logo at the Waiting screen

To specify the logo on the *Waiting...* screen:

[width="100%",cols="50%,50%",]
|===
|In CT Mobile Control Panel a|
. Go to the *CT Mobile Control Panel: General* tab.
. {blank}
. In the *User Interface* section, click *Customize*.
. Click *Choose file* and upload the logo to use for the
xref:ios/mobile-application/ui/home-screen/index.adoc[Home screen].
. Click *Save*.

The logo is added.

|In CT Mobile Control Panel 2.0 a|
. Go to xref:ios/admin-guide/ct-mobile-control-panel-new/ct-mobile-control-panel-user-interface-new.adoc[CT Mobile
Control Panel 2.0: User Interface] tab.
. Select the required profile in the *Profile* picklist. To apply
settings to all the profiles, select *General Settings*.
. In the *Homepage Logo* section, click *Upload Files* and upload the
logo to use for the xref:ios/mobile-application/ui/home-screen/index.adoc[Home screen].
. Click *Save*.

The logo is added.

|===
