= Multiplicator

The Multiplicator option is responsible for adding the correct product
quantity to the order cart.



The quantity must always be divisible by a multiplicity factor value,
which can be set on multiple levels and is processed in turn in the
following order:



[width="100%",cols="^25%,^25%,^25%,^25%",]
|===
|*Order* |*Object* |*Responsible Field* |*Description*

|1 |[.object]#Catalog Line Item# or[.object]#Promotion
Line Item# |Units Count Step |This field is checked first in these
objects. If no records are found, the system uses the value in
the *Units Count Step* field on
the link:admin-guide/managing-ct-orders/product-management/product-data-model/ct-price-book-line-item-field-reference[CT Price Book Line
Item] record.

|2 |[.object]#Price Book Line Item# |Units Count Step a|
The field stores the multiplicity step in the order cart must be
divisible by the *Units in Package* value and also greater than that
value.

For example, if you set *Units in Package* to 5, the *Units Count Step*
must be at least 10.

|3 |[.object]#Product# |Units in Package a|
The field stores the number of products in a package.

This is the main value, which is always compared with the entered number
during quantity calculation.

|===

[[h2_818978857]]
=== Process Path

. After a product is added to your order cart, the system checks if the
*Unit Count Step* on _Catalog Line Item_ or _Promotion Line Item_ record
exists and the value is greater than 0. The quantity of the product in
the delivery, e.g., _Delivery Line Item_, must be divisible by the
*Units Count Step* value. The quantity field is defined in
the link:admin-guide/getting-started/setting-up-an-instance/configuring-order-and-order-line-item-mapping[Delivery
Line Item Mapping Setting].
. If no value is found on the _Catalog Line Item_ or _Promotion Line
Item_ record, the system checks the *Units Count Step* field on the _CT
Price Book Line Item_ record. The quantity of the product in the
delivery, e.g., _Delivery Line Item_, must be divisible by the *Units
Count Step* value on the _CT Price Book Line Item_ record.
. If no value is found on the _CT Price Book Line Item_ record, the
system checks the *Units in Package* field value on the corresponding
_Product_ record. The quantity of the product in the delivery, e.g.,
_Delivery Line Item_, must be divisible by the *Units in Package* value
on the corresponding _Product_ record.
. If no value is found on any of the objects, the applied multiplicity
factor is 1.

[[h2__868831931]]
=== Important Notes

* The Multiplicator logic is applied for each delivery separately.
* For link:admin-guide/managing-ct-orders/product-management/managing-bundles[bundles] with the quantity on _Product
Component_ records, the first step is omitted, as the _Catalog Line
Item_ or _Promotion Line Item_ records are copied from the header and
will be calculated equally for all components. The Multiplicator logic
is not applied for bundles with header-dependent quantity, as the
independent multiplier already exists on the _Product Component_
records.
* Multiplicator considers the
link:admin-guide/managing-ct-orders/product-management/index#h2_1138962735[minimum and maximum quantity
per delivery], which is specified on a _Product_ record.
* Multiplicator logic is not applied for freebies.
