= Default Gestures

Consider these gestures when implementing embedded interactions in a
slide markup. For example, do not call custom action double tapping on
the bottom of a slide.

[width="100%",cols="50%,50%",options="header",]
|===
|*Gesture* |*Action*
|Left/right double-finger swipe a|
A default gesture for swiping slides. It may be reconfigured to
one-finger swipe in the Swipe gesture type attribute of the CLM
presentation.

One-finger swipe may interfere with embedded interactions in slides.

|Up/down double-finger swipe |Use to like (up) or dislike (down) a
slide.

|Double-finger rotation |Use to restart a current slide.

|Double tap the right/left side a|
Display sidebar with action menu.

* The action menu width is 120 px.
* For more information about action menu, refer to
xref:clm-presentation-controls[CLM Presentation Controls].

|Double tap on the bottom a|
Display the navigator bar with the selected scenario and preview of
slides.

* Tap a slide to open it.
* Double tap the navigation bar to hide it.
* The navigation bar displays the preview of the slides with resolutions
of 100×75 px.
* The navigation bar resolutions are 1024×120 px.

|Two-finger pinch a|
Zoom in and out an open slide.

Not in use in Remote Detailing and Self-Detailing.

|===
