site:
  title: CT Software Help Portal
  start_page: root::index.adoc
content:
  sources:
  - url: https://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@github.com/vbelyakov-ct/help-ct-com.git
    branches: main
    start_path: docs
ui:
  bundle:
    url: ./ui-bundle-ct.zip
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: false
  supplemental_files:
  - path: css/vendor/tabs.css
    contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
  - path: js/vendor/tabs.js
    contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
  - path: partials/footer-scripts.hbs
    contents: |
      <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
      <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
      <script async src="{{{uiRootPath}}}/js/vendor/tabs.js"></script>
      {{#if env.SITE_SEARCH_PROVIDER}}
      {{> search-scripts}}
      {{/if}}
  - path: partials/head-styles.hbs
    contents: |
      <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
      <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
