= Roll-up Summary Fields

A roll-up summary field is used to calculate values from a set of related records. The child records must be directly related to the parent record through a master-detail relationship.

To create a roll-up summary field, refer to link:https://help.salesforce.com/articleView?id=sf.fields_about_roll_up_summary_fields.htm&type=5[Salesforce Help].

In the CT Mobile app, the roll-up field will automatically display a value on a parent record based on the values of child records. There is no need to start the sync process when the child record values have been changed:

* these operators are supported:
** [.apiobject]#equals#
** [.apiobject]#less than#
** [.apiobject]#greater than#
** [.apiobject]#less or equal#
** [.apiobject]#greater or equal#
** [.apiobject]#contains#
** [.apiobject]#not equal to#
** [.apiobject]#starts with#
** [.apiobject]#between#
** [.apiobject]#within# ([.apiobject]#DISTANCE# only)
* fields with these filed types are supported as criteria to filter records:
** Text
** Data
** Date/Time
** Currency
** Email
** Phone
** Picklist (several values)
** Time (recalculation only after synchronization)
** URL
