= CT Products and Assortments Management

xref:admin-guide/getting-started/configuring-application-settings[After configuring the main
Application Settings], specify _CT Products_ and _Assortments_ to track
them during visits to the clients.



Follow the guidelines to configure
xref:admin-guide/ct-products-and-assortments-management/index.adoc[_CT products_ and
_Assortments_] according to your company goals:

. xref:create-a-new-ct-product[Add the required products] to the
Salesforce organization.
* ​add a single product;
* ​upload product records via
https://help.salesforce.com/articleView?id=data_loader.htm&type=5[Data
Loader] or https://trailhead.salesforce.com/content/learn/modules/lex_implementation_data_management/lex_implementation_data_import[Data
Import Wizard];
* ​upload product catalogs from the external ERP-system.
. Upload or manually create a list of
products—xref:create-an-assortment.html[Assortments]_—based on _CT
Products_, brands, and hierarchy sets in your product catalogs to
promote them for different types of clients based on the clients' size,
contracts, loyalty, or other attributes.
. xref:assign-assortments-to-accounts[Assign
available assortments] to the clients who should have this
product list while it is active.
. xref:assign-inventories-to-accounts[Assign inventories] for the
required __Account __records to track rental items and their status.
