= Activating JS Bridge

The *JS Bridge* functionality is intended for managing CRM data on a CLM
presentation by generating pre-configured JavaScript methods on a slide.

To activate JS Bridge, enable the JS Bridge library in the
[.apiobject]#<head># tag of a slide:





The source code of the JS Bridge library can be downloaded from the
static resource of Salesforce. The file name is
[.apiobject]#JsLibrary.zip#.

[[h2__1614277225]]
=== Event of functional readiness of JS Bridge:

To check JS Bridge availability for use it is recommended to perform the
entire logic of interaction through addEventListener.



[[h2__1136353801]]
=== Available JS Bridge Methods

xref:methods-for-interaction-with-crm-data[Methods for Interaction
with CRM data]

xref:methods-for-accessing-external-functionality[Methods for
Accessing External Functionality]

xref:methods-for-clm-presentation-control[Methods for CLM
Presentation Control]

ifdef::ios,win[]

xref:methods-for-clm-presentation-navigation[Methods for
CLM-presentation Navigation]

xref:methods-for-remote-detailing-2-0[Methods for Remote Detailing
2.0]



The following methods are outdated:

*[.apiobject]#getUSValues#
*[.apiobject]##[.apiobject]#playVideo#
*[.apiobject]##[.apiobject]#skipTenPercent#
*[.apiobject]##[.apiobject]#CTAPPNewRecord#.
