= Activating JS Bridge

The *JS Bridge* functionality is intended for managing CRM data on a CLM presentation by generating pre-configured JavaScript methods on a slide.

To activate JS Bridge, enable the JS Bridge library in the [.apiobject]#<head># tag of a slide:

[source,html]
----
<script type="text/javascript" src="../JSLibrary/js/app.js"></script>
----

The source code of the JS Bridge library can be downloaded from the static resource of Salesforce. The file name is [.apiobject]#JsLibrary.zip#.

[[h2_1614277225]]
== Event of functional readiness of JS Bridge:

To check JS Bridge availability for use it is recommended to perform the entire logic of interaction through addEventListener.

[source,html]
----
document.addEventListener('WebViewJavascriptBridgeReady', function(event){
    console.log('JS Bridge is ready');
});
----

[[h2_1136353801]]
== Available JS Bridge Methods

* xref:./methods-for-interaction-with-crm-data/index.adoc[Methods for Interaction with CRM data]
* xref:./methods-for-accessing-external-functionality/index.adoc[Methods for Accessing External Functionality]
* xref:./methods-for-clm-presentation-control/index.adoc[Methods for CLM Presentation Control]
* xref:./methods-for-clm-presentation-navigation/index.adoc[Methods for CLM-presentation Navigation]
* xref:./methods-for-remote-detailing-2-0/index.adoc[Methods for Remote Detailing 2.0]

The following methods are outdated:

* [.apiobject]#getUSValues#
* [.apiobject]#playVideo#
* [.apiobject]#skipTenPercent#
* [.apiobject]#CTAPPNewRecord#.
