= Activity Layout Settings

*Activity Layout Settings* is responsible for displaying the
corresponding field set on the
_xref:activity-report-interface.html[Activity Report]_ page for the
_Activity_ with the specific record type. Also, it used to
display the *Activities List* __ and __ *Joint User Activities
List*__ __sections with available activities on the__ Activity
Report__ page.

'''''

API name in Salesforce: CTCPG\__ActivityLayoutSettings__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Field Set API Name |CTCPG\__FieldSetAPIName__c |Text(255)
|The API name of the specific field set.
[TIP] ==== The records for each available _Activity_ record type
are created by default. You can edit field sets and
xref:admin-guide/activity-report-management/manage-field-sets-for-activity-report-pages[create a new one]
for the newly created _Activity_ record type. ====

|Name |Name |Text(255) |The _CT CPG Activity_ record type for which the
specified field set will be used.
|===
