= Change Request Object Settings

*Important notes*:

* The information below is incomplete and will be updated.
* This setting is necessary for the **Change Request **functionality.



*Change Request Object Settings* is intended to store settings for
objects to be affected by the _Change Request: Create_ and _Change
Request: Succession_ processes.

* The object specified in the CTCPG\__Target_Object__c field
should have the _Target_ and __something_ record types, for example,
_Temrorarely or_Succession, to be able for changing the record
type during the _Change Request_ process.

'''''

API name in Salesforce: CTCPG\__Change_Request_Objects__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Change Request Driven Creation |CTCPG\__isCRDriven__c |Checkbox
|If enabled, the _Change Request_ is active.

|Custom Processor |CTCPG\__Custom_Processor__c |Text (255)
a|
If needed, create the Apex class, which will be responsible for the
custom logic, and add its API name:

* inherit processors from the ChangeRequestProcessors class;
* override the doProcess and doRegress methods.

|Read-Only Fields |CTCPG\__Read_Only_Fields__c |Text
(255) |Additional fields are displayed as read-only on the _Change
Request_ layout.

|Target Object |CTCPG\__Target_Object__c |Text (255)
(Unique Case Insensitive) |The API name of the target object, which
record is affected by the _Change Request_ process, for example,
Account.

|Target Object Lookup |CTCPG\__Target_Object_Lookup__c
|Text (255) |The lookup field API name of the[.object]#Change
Request# object that is related to the target object, for example,
AccountId__c.

|Target Object Record Type Suffix Create
|CTCPG\__Target_Object_Record_Type_Suffix_Create__c
|Text (255) |The suffix API Name, which will be attributed to a new
object creation via the _Change Request: Create_ process.

|Target Object Record Type Suffix Succeed
|CTCPG\__Target_Object_Record_Type_Suffix_Succeed__c
|Text (255)  |The suffix API Name, which will be attributed to a new
object creation via the _Change Request: Succession_ process.

|Target Object Status Field
|CTCPG\__Target_Object_Status_Field__c |Text
(255)  |The *Status* field API Name of the target object.

|Target Object Status Invalid
|CTCPG\__Target_Object_Status_Invalid__c |Text
(255)  |The value from the *Status* field of the target object, which
indicates the record of the target object is inactive.

|Target Object Status Succession
|CTCPG\__Target_Object_Status_Succession__c |Text
(255)  |The value from the *Status* field of the target object, which
indicates the record of the target object is on the *Awaiting
Succession* stage.

|Target Object Status Valid
|CTCPG\__Target_Object_Status_Valid__c |Text
(255)  |The value from the *Status* field of the target object, which
indicates the record of the target object is active.

|Target Object Succession Parent Lookup
|CTCPG\__Target_Object_Succession_Parent_Lookup__c
|Text (255)  |The lookup field API name of the target object that is
related to the succeeded object, for example,
Succession_from__c, via the _Change Request: Succession_
process.
|===
