= Trigger Settings

*Trigger Settings* is used to switch one certain trigger or trigger
context on/off.[NOTE] ==== Deactivation of a CT CPG trigger can
result in data inconsistency or loss of data.  ====

* Records CT CPG triggers are available by default and active.
* If you updated the CT CPG package, some triggers may not be present in
the *Trigger
Settings* list. Unless xref:admin-guide/triggers-management/manage-ct-cpg-triggers#h2_527552279[the
corresponding Trigger Settings record is present], the CT CPG trigger is
deactivated and will not in operation.

'''''

API name in Salesforce: CTCPG__TriggerSettings__c

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Active  |CTCPG__IsActive__c |Checkbox  |If selected, the
trigger is active.

|Bypass Logic |CTCPG__BypassLogic__c |Text Area (255)  |Enter
xref:admin-guide/triggers-management/triggers/trigger-contexts[the trigger event API name] to prevent the
trigger event from execution (separated by a comma, without blank
spaces).

|Comments |CTCPG__Comments__c |Text Area (255) |Specify the
description of a current setting.

|Name |Name | |API Name of the required trigger.

|Prevent re-execution |CTCPG__IsReexecutionPrevented__c
|Checkbox  a|
If selected, the trigger will not re-execute within one transaction, for
example, in case of another trigger invokes it.

If not, in case of the presence of the custom logic, such as Workflow or
Process Builder, the trigger will be invoked before and after custom
logic.

|===

ifdef::hidden[]

*trigger context* – контекст выполнения триггера, например before
insert, after update и т.д.

*trigger event* – событие, вызвавшее логику работы триггера - например
создание новой записи для контекста after insert

*trigger method* – метод, вызываемый при срабатывании определенного
эвента в определенном контексте, например,
afterInsert(trigger.new), который сработает при создании новой записи в
контексте after insert триггера (при наличии триггера на соответствующий
объект и объявлении в нем соответствующего контекста)


