= CG Cloud

CG Cloud is a powerful analytic tool to help managers optimize their
team's performance. CG Cloud helps to sell smarter in retail stores and
make better visit plans, so field reps will spend less time on
operational activities and spend more time building relationships with
retailers to drive sales and satisfaction.



CG Cloud supports presales and merchandising activities by using
assessment task definitions that hold information such as name,
description, category, and type of task and addresses the most common
activities with the predefined
https://help.salesforce.com/s/articleView?id=sf.retail_concept_admin_assesstask_types.htm&type=5[assessment
task definition types].



Integration with the CT Mobile app allows field reps to get advantages
from both solutions, for example, visiting smaller stores or kiosks
located in basements without internet connectivity or in remote areas
with poor internet speed. Follow this guide to activate CG Cloud in your
Salesforce org and the CT Mobile app, set up retail execution, and get
an idea of how to perform different types of assessment tasks offline.
