= Configuring Activity Report

Check this section to be fully aware of the Activity Report
functionality.

* Set up xref:activity-layout-settings[Activity Report page
layouts].
Users can view activity's details using standard pages or custom
Activity Report pages. Follow the instructions to customize the Activity
Report per the required activity type.
* Create and
manage xref:admin-guide/pharma-activity-report/configuring-activity-report/activity-layout-settings/create-a-new-filter-for-the-activities-list.adoc[Activity
Report filters].
Use filters on the Activity Report page to quickly find another Activity
Report according to the filter criteria.
* Customize xref:admin-guide/pharma-activity-report/configuring-activity-report/activity-report-tab-settings/index.adoc[Activity Report
related tabs].
Define which related tabs should be on the Activity Report tab according
to the activity type and your company business purposes.
* xref:override-basic-actions-for-activity[Override the link] for
standard buttons.
Set up access to the custom Activity Report pages via buttons.

[.aui-icon .aui-icon-small .aui-iconfont-approve .confluence-information-macro-icon]##

Also, you can customize these tabs for each Profile on
the *xref:ct-pharma-control-panel-activity-report[CT Pharma Control
Panel: Activity Report]* tab.

*See also*:

* xref:ct-pharma-control-panel-activity-report[CT Pharma Control
Panel: Activity Report]
