name: Publish Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Antora
        run: npm i antora @asciidoctor/tabs

      # Генерируем все версии
      - name: Generate Documentation
        run: |
          # Сохраняем оригинальный antora.yml
          if [ -f "docs/modules/ctmobile/antora.yml" ]; then
            cp docs/modules/ctmobile/antora.yml docs/modules/ctmobile/antora.yml.orig
          fi
          
          # iOS версия
          cat > docs/modules/ctmobile/antora.yml << EOF
          name: ctmobile
          title: CT Mobile for iOS
          version: '1.0-ios'
          nav:
          - modules/ROOT/nav.adoc
          EOF

          # Генерируем iOS версию
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Android версия
          cat > docs/modules/ctmobile/antora.yml << EOF
          name: ctmobile
          title: CT Mobile for Android
          version: '1.0-android'
          nav:
          - modules/ROOT/nav.adoc
          EOF

          # Генерируем Android версию
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Windows версия
          cat > docs/modules/ctmobile/antora.yml << EOF
          name: ctmobile
          title: CT Mobile for Windows
          version: '1.0-windows'
          nav:
          - modules/ROOT/nav.adoc
          EOF

          # Генерируем Windows версию
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Восстанавливаем оригинальный antora.yml
          if [ -f "docs/modules/ctmobile/antora.yml.orig" ]; then
            mv docs/modules/ctmobile/antora.yml.orig docs/modules/ctmobile/antora.yml
          fi

      # Публикация на GitHub Pages
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4