# Создаем временные playbook-файлы для разных платформ (с корректным URL)
- name: Create Platform-Specific Playbooks
  run: |
    # Извлекаем базовый URL из основного плейбука
    BASE_URL=$(grep -o 'url:.*' docs/antora-playbook.yml | sed 's/url: //')
    if [ -z "$BASE_URL" ]; then
      # Если URL не найден, используем относительный путь
      BASE_URL="/"
    fi
    
    echo "Using base URL: $BASE_URL"
    
    # iOS версия
    cat > docs/antora-playbook-ios.yml <<EOF
    site:
      title: CT Software Help Portal - iOS
      url: $BASE_URL
    content:
      sources:
      - url: .
        branches: HEAD
        start_path: docs
    ui:
      bundle:
        url: docs/ui-bundle.zip
        snapshot: false
    asciidoc:
      extensions:
        - '@asciidoctor/tabs'
      attributes:
        # Активируем только iOS, отключаем другие
        platform-ios: ''
        platform-android: null
        platform-windows: null
    output:
      dir: docs/build/site/ctmobile/ios
    EOF
    
    # Android версия
    cat > docs/antora-playbook-android.yml <<EOF
    site:
      title: CT Software Help Portal - Android
      url: $BASE_URL
    content:
      sources:
      - url: .
        branches: HEAD
        start_path: docs
    ui:
      bundle:
        url: docs/ui-bundle.zip
        snapshot: false
    asciidoc:
      extensions:
        - '@asciidoctor/tabs'
      attributes:
        # Активируем только Android, отключаем другие
        platform-ios: null
        platform-android: ''
        platform-windows: null
    output:
      dir: docs/build/site/ctmobile/android
    EOF
    
    # Windows версия
    cat > docs/antora-playbook-windows.yml <<EOF
    site:
      title: CT Software Help Portal - Windows
      url: $BASE_URL
    content:
      sources:
      - url: .
        branches: HEAD
        start_path: docs
    ui:
      bundle:
        url: docs/ui-bundle.zip
        snapshot: false
    asciidoc:
      extensions:
        - '@asciidoctor/tabs'
      attributes:
        # Активируем только Windows, отключаем другие
        platform-ios: null
        platform-android: null
        platform-windows: ''
    output:
      dir: docs/build/site/ctmobile/windows
    EOF