name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora, AsciiDoctor and Tabs
        run: npm i antora @asciidoctor/tabs asciidoctor@~2.2.8
      - name: Debug Installed Packages
        run: npm list

      # Изучаем текущую структуру и файлы для отладки
      - name: Debug Current Repository Structure
        run: |
          echo "Checking current repository structure..."
          if [ -d "docs/modules/ctmobile" ]; then
            echo "ctmobile module exists."
            echo "Contents of docs/modules/ctmobile:"
            ls -la docs/modules/ctmobile
          
            if [ -f "docs/modules/ctmobile/antora.yml" ]; then
              echo "antora.yml contents:"
              cat docs/modules/ctmobile/antora.yml
            fi
          
            if [ -d "docs/modules/ctmobile/modules/ROOT" ]; then
              echo "Contents of ROOT module:"
              ls -la docs/modules/ctmobile/modules/ROOT
          
              if [ -f "docs/modules/ctmobile/modules/ROOT/nav.adoc" ]; then
                echo "nav.adoc contents:"
                cat docs/modules/ctmobile/modules/ROOT/nav.adoc
              fi
            fi
          else
            echo "ctmobile module does not exist yet."
          fi
          
          echo "Current antora-playbook.yml contents:"
          cat docs/antora-playbook.yml

      # Генерация основного сайта (ctvision и другие модули)
      - name: Generate Main Site
        run: npx antora --stacktrace docs/antora-playbook.yml

      # Создаем временную структуру ctmobile если её ещё нет
      - name: Check and create ctmobile structure if needed
        run: |
          if [ ! -d "docs/modules/ctmobile" ]; then
            echo "Creating temporary ctmobile module structure..."
            mkdir -p docs/modules/ctmobile/modules/ROOT/pages
          
            # Создаем временный antora.yml
            echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
            echo "title: CT Mobile" >> docs/modules/ctmobile/antora.yml
            echo "version: '1.0'" >> docs/modules/ctmobile/antora.yml
            echo "nav:" >> docs/modules/ctmobile/antora.yml
            echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
            # Создаем временный nav.adoc
            echo "* xref:index.adoc[CT Mobile]" > docs/modules/ctmobile/modules/ROOT/nav.adoc
          
            # Создаем временную индексную страницу
            echo "= CT Mobile" > docs/modules/ctmobile/modules/ROOT/pages/index.adoc
            echo ":navtitle: Обзор CT Mobile" >> docs/modules/ctmobile/modules/ROOT/pages/index.adoc
            echo "" >> docs/modules/ctmobile/modules/ROOT/pages/index.adoc
            echo "Документация находится в процессе разработки." >> docs/modules/ctmobile/modules/ROOT/pages/index.adoc
          fi

      # Модифицируем навигацию для использования соответствующих версий
      - name: Update Navigation for Platform Versions
        run: |
          if [ -f "docs/modules/ctmobile/modules/ROOT/nav.adoc" ]; then
            # Сохраняем оригинальный nav.adoc
            cp docs/modules/ctmobile/modules/ROOT/nav.adoc docs/modules/ctmobile/modules/ROOT/nav.adoc.orig
          
            # Создаем новый nav.adoc с платформо-специфичными ссылками
            echo "* xref:index.adoc[CT Mobile]" > docs/modules/ctmobile/modules/ROOT/nav.adoc
          
            echo "ifdef::platform-ios[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "* iOS" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "** xref:features.adoc[Возможности iOS]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
          
            echo "ifdef::platform-android[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "* Android" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "** xref:features.adoc[Возможности Android]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
          
            echo "ifdef::platform-windows[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "* Windows" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "** xref:features.adoc[Возможности Windows]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
            echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/nav.adoc
          
            # Проверяем наличие файла features.adoc, создаем если нет
            if [ ! -f "docs/modules/ctmobile/modules/ROOT/pages/features.adoc" ]; then
              echo "= Возможности CT Mobile" > docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo ":navtitle: Возможности" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "== Общие возможности" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "Общие функции для всех платформ." >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "ifdef::platform-ios[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "== Особенности iOS" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "Функции, доступные только в iOS-версии." >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "ifdef::platform-android[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "== Особенности Android" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "Функции, доступные только в Android-версии." >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "ifdef::platform-windows[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "== Особенности Windows" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "Функции, доступные только в Windows-версии." >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
              echo "endif::[]" >> docs/modules/ctmobile/modules/ROOT/pages/features.adoc
            fi
          fi

      # Создаем плейбуки для каждой платформы
      - name: Create Platform-Specific Playbooks
        run: |
          # iOS версия
          echo "site:" > docs/antora-playbook-ios.yml
          echo "  title: CT Software Help Portal - iOS" >> docs/antora-playbook-ios.yml
          echo "  url: /" >> docs/antora-playbook-ios.yml
          echo "content:" >> docs/antora-playbook-ios.yml
          echo "  sources:" >> docs/antora-playbook-ios.yml
          echo "  - url: ." >> docs/antora-playbook-ios.yml
          echo "    branches: HEAD" >> docs/antora-playbook-ios.yml
          echo "    start_path: docs" >> docs/antora-playbook-ios.yml
          echo "ui:" >> docs/antora-playbook-ios.yml
          echo "  bundle:" >> docs/antora-playbook-ios.yml
          echo "    url: docs/ui-bundle.zip" >> docs/antora-playbook-ios.yml
          echo "    snapshot: false" >> docs/antora-playbook-ios.yml
          echo "asciidoc:" >> docs/antora-playbook-ios.yml
          echo "  extensions:" >> docs/antora-playbook-ios.yml
          echo "    - '@asciidoctor/tabs'" >> docs/antora-playbook-ios.yml
          echo "  attributes:" >> docs/antora-playbook-ios.yml
          echo "    platform-ios: ''" >> docs/antora-playbook-ios.yml
          echo "    platform-android: '!'" >> docs/antora-playbook-ios.yml
          echo "    platform-windows: '!'" >> docs/antora-playbook-ios.yml
          echo "output:" >> docs/antora-playbook-ios.yml
          echo "  dir: docs/build/site" >> docs/antora-playbook-ios.yml
          
          # Android версия
          echo "site:" > docs/antora-playbook-android.yml
          echo "  title: CT Software Help Portal - Android" >> docs/antora-playbook-android.yml
          echo "  url: /" >> docs/antora-playbook-android.yml
          echo "content:" >> docs/antora-playbook-android.yml
          echo "  sources:" >> docs/antora-playbook-android.yml
          echo "  - url: ." >> docs/antora-playbook-android.yml
          echo "    branches: HEAD" >> docs/antora-playbook-android.yml
          echo "    start_path: docs" >> docs/antora-playbook-android.yml
          echo "ui:" >> docs/antora-playbook-android.yml
          echo "  bundle:" >> docs/antora-playbook-android.yml
          echo "    url: docs/ui-bundle.zip" >> docs/antora-playbook-android.yml
          echo "    snapshot: false" >> docs/antora-playbook-android.yml
          echo "asciidoc:" >> docs/antora-playbook-android.yml
          echo "  extensions:" >> docs/antora-playbook-android.yml
          echo "    - '@asciidoctor/tabs'" >> docs/antora-playbook-android.yml
          echo "  attributes:" >> docs/antora-playbook-android.yml
          echo "    platform-ios: '!'" >> docs/antora-playbook-android.yml
          echo "    platform-android: ''" >> docs/antora-playbook-android.yml
          echo "    platform-windows: '!'" >> docs/antora-playbook-android.yml
          echo "output:" >> docs/antora-playbook-android.yml
          echo "  dir: docs/build/site" >> docs/antora-playbook-android.yml
          
          # Windows версия
          echo "site:" > docs/antora-playbook-windows.yml
          echo "  title: CT Software Help Portal - Windows" >> docs/antora-playbook-windows.yml
          echo "  url: /" >> docs/antora-playbook-windows.yml
          echo "content:" >> docs/antora-playbook-windows.yml
          echo "  sources:" >> docs/antora-playbook-windows.yml
          echo "  - url: ." >> docs/antora-playbook-windows.yml
          echo "    branches: HEAD" >> docs/antora-playbook-windows.yml
          echo "    start_path: docs" >> docs/antora-playbook-windows.yml
          echo "ui:" >> docs/antora-playbook-windows.yml
          echo "  bundle:" >> docs/antora-playbook-windows.yml
          echo "    url: docs/ui-bundle.zip" >> docs/antora-playbook-windows.yml
          echo "    snapshot: false" >> docs/antora-playbook-windows.yml
          echo "asciidoc:" >> docs/antora-playbook-windows.yml
          echo "  extensions:" >> docs/antora-playbook-windows.yml
          echo "    - '@asciidoctor/tabs'" >> docs/antora-playbook-windows.yml
          echo "  attributes:" >> docs/antora-playbook-windows.yml
          echo "    platform-ios: '!'" >> docs/antora-playbook-windows.yml
          echo "    platform-android: '!'" >> docs/antora-playbook-windows.yml
          echo "    platform-windows: ''" >> docs/antora-playbook-windows.yml
          echo "output:" >> docs/antora-playbook-windows.yml
          echo "  dir: docs/build/site" >> docs/antora-playbook-windows.yml

      # Создаем платформенные версии документации
      - name: Generate Platform-Specific Versions
        run: |
          # Сохраняем оригинальный antora.yml если он есть
          if [ -f "docs/modules/ctmobile/antora.yml" ]; then
            cp docs/modules/ctmobile/antora.yml docs/modules/ctmobile/antora.yml.orig
          fi
          
          # =====================
          # iOS версия
          # =====================
          echo "Creating and generating iOS version..."
          # Создаем версию antora.yml для iOS
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for iOS" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-ios'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          # Показываем содержимое файла для отладки
          echo "iOS antora.yml content:"
          cat docs/modules/ctmobile/antora.yml
          
          # Генерируем iOS версию
          npx antora --stacktrace docs/antora-playbook-ios.yml || echo "iOS generation failed but continuing"
          
          # =====================
          # Android версия
          # =====================
          echo "Creating and generating Android version..."
          # Создаем версию antora.yml для Android
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for Android" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-android'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          # Показываем содержимое файла для отладки
          echo "Android antora.yml content:"
          cat docs/modules/ctmobile/antora.yml
          
          # Генерируем Android версию
          npx antora --stacktrace docs/antora-playbook-android.yml || echo "Android generation failed but continuing"
          
          # =====================
          # Windows версия
          # =====================
          echo "Creating and generating Windows version..."
          # Создаем версию antora.yml для Windows
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for Windows" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-windows'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          # Показываем содержимое файла для отладки
          echo "Windows antora.yml content:"
          cat docs/modules/ctmobile/antora.yml
          
          # Генерируем Windows версию
          npx antora --stacktrace docs/antora-playbook-windows.yml || echo "Windows generation failed but continuing"
          
          # Восстанавливаем оригинальный antora.yml
          if [ -f "docs/modules/ctmobile/antora.yml.orig" ]; then
            mv docs/modules/ctmobile/antora.yml.orig docs/modules/ctmobile/antora.yml
          fi

      # Проверка сгенерированной структуры
      - name: Check Generated Site Structure
        run: |
          echo "Generated site structure:"
          find docs/build/site -type d | sort
          
          echo "Checking for iOS version files:"
          ls -la docs/build/site/ctmobile/1.0-ios || echo "iOS version not found"
          
          echo "Checking for Android version files:"
          ls -la docs/build/site/ctmobile/1.0-android || echo "Android version not found"
          
          echo "Checking for Windows version files:"
          ls -la docs/build/site/ctmobile/1.0-windows || echo "Windows version not found"

      # Создание страницы-переключателя с актуальными ссылками
      - name: Create Platform Selector
        run: |
          mkdir -p docs/build/site/ctmobile
          echo '<!DOCTYPE html>' > docs/build/site/ctmobile/index.html
          echo '<html lang="en">' >> docs/build/site/ctmobile/index.html
          echo '<head>' >> docs/build/site/ctmobile/index.html
          echo '  <meta charset="UTF-8">' >> docs/build/site/ctmobile/index.html
          echo '  <meta name="viewport" content="width=device-width, initial-scale=1.0">' >> docs/build/site/ctmobile/index.html
          echo '  <title>CT Mobile Documentation</title>' >> docs/build/site/ctmobile/index.html
          echo '  <style>' >> docs/build/site/ctmobile/index.html
          echo '    body {' >> docs/build/site/ctmobile/index.html
          echo '      font-family: sans-serif;' >> docs/build/site/ctmobile/index.html
          echo '      max-width: 800px;' >> docs/build/site/ctmobile/index.html
          echo '      margin: 0 auto;' >> docs/build/site/ctmobile/index.html
          echo '      padding: 20px;' >> docs/build/site/ctmobile/index.html
          echo '    }' >> docs/build/site/ctmobile/index.html
          echo '    h1 { color: #0366d6; }' >> docs/build/site/ctmobile/index.html
          echo '    .platform-btn {' >> docs/build/site/ctmobile/index.html
          echo '      display: inline-block;' >> docs/build/site/ctmobile/index.html
          echo '      margin: 10px;' >> docs/build/site/ctmobile/index.html
          echo '      padding: 10px 20px;' >> docs/build/site/ctmobile/index.html
          echo '      background-color: #0366d6;' >> docs/build/site/ctmobile/index.html
          echo '      color: white;' >> docs/build/site/ctmobile/index.html
          echo '      text-decoration: none;' >> docs/build/site/ctmobile/index.html
          echo '      border-radius: 4px;' >> docs/build/site/ctmobile/index.html
          echo '    }' >> docs/build/site/ctmobile/index.html
          echo '  </style>' >> docs/build/site/ctmobile/index.html
          echo '</head>' >> docs/build/site/ctmobile/index.html
          echo '<body>' >> docs/build/site/ctmobile/index.html
          echo '  <h1>CT Mobile Documentation</h1>' >> docs/build/site/ctmobile/index.html
          echo '  <p>Please select your platform:</p>' >> docs/build/site/ctmobile/index.html
          echo '  <div>' >> docs/build/site/ctmobile/index.html
          echo '    <a href="../ctmobile/1.0-ios/index.html" class="platform-btn">iOS</a>' >> docs/build/site/ctmobile/index.html
          echo '    <a href="../ctmobile/1.0-android/index.html" class="platform-btn">Android</a>' >> docs/build/site/ctmobile/index.html
          echo '    <a href="../ctmobile/1.0-windows/index.html" class="platform-btn">Windows</a>' >> docs/build/site/ctmobile/index.html
          echo '  </div>' >> docs/build/site/ctmobile/index.html
          echo '  <p><a href="../">&larr; Back to main documentation</a></p>' >> docs/build/site/ctmobile/index.html
          echo '</body>' >> docs/build/site/ctmobile/index.html
          echo '</html>' >> docs/build/site/ctmobile/index.html

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4