name: Publish Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install Antora
        run: npm i antora @asciidoctor/tabs

      # Создаем временные плейбуки
      - name: Create Platform Playbooks
        run: |
          # iOS
          echo "site:" > ios-playbook.yml
          echo "  title: CT Mobile для iOS" >> ios-playbook.yml
          echo "content:" >> ios-playbook.yml
          echo "  sources:" >> ios-playbook.yml
          echo "  - url: ." >> ios-playbook.yml
          echo "    start_path: docs" >> ios-playbook.yml
          echo "ui:" >> ios-playbook.yml
          echo "  bundle:" >> ios-playbook.yml
          echo "    url: ./ui-bundle.zip" >> ios-playbook.yml
          echo "asciidoc:" >> ios-playbook.yml
          echo "  extensions:" >> ios-playbook.yml
          echo "    - '@asciidoctor/tabs'" >> ios-playbook.yml
          echo "  attributes:" >> ios-playbook.yml
          echo "    platform-ios: ''" >> ios-playbook.yml
          echo "output:" >> ios-playbook.yml
          echo "  dir: ./build/ios" >> ios-playbook.yml
          
          # Аналогично для Android и Windows...

      # Генерируем все версии
      - name: Generate All Versions
        run: |
          npx antora --stacktrace ios-playbook.yml
          npx antora --stacktrace android-playbook.yml
          npx antora --stacktrace windows-playbook.yml
          
          # Создаем страницу-переключатель
          mkdir -p build/ctmobile
          echo '<!DOCTYPE html>' > build/ctmobile/index.html
          echo '<html><head><title>CT Mobile</title></head>' >> build/ctmobile/index.html
          echo '<body>' >> build/ctmobile/index.html
          echo '<h1>Выберите платформу</h1>' >> build/ctmobile/index.html
          echo '<ul>' >> build/ctmobile/index.html
          echo '<li><a href="../ios/">iOS</a></li>' >> build/ctmobile/index.html
          echo '<li><a href="../android/">Android</a></li>' >> build/ctmobile/index.html
          echo '<li><a href="../windows/">Windows</a></li>' >> build/ctmobile/index.html
          echo '</ul></body></html>' >> build/ctmobile/index.html

      # Публикация
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build