name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure Pages
      uses: actions/configure-pages@v5
      with:
        enablement: true
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Install Antora, AsciiDoctor and Tabs
      run: npm i antora @asciidoctor/tabs asciidoctor@~2.2.8
    - name: Debug Installed Packages
      run: npm list
      
    # Генерация основного сайта с модулем ctvision
    - name: Generate Main Site
      run: npx antora --stacktrace docs/antora-playbook.yml
      
    # Создаем временные playbook-файлы для разных платформ ctmobile
    - name: Create Platform-Specific Playbooks
      run: |
        # iOS версия
        cat > docs/antora-playbook-ios.yml <<EOF
        site:
          title: CT Software Help Portal - iOS
          url: ${{ steps.deployment.outputs.page_url }}ctmobile/ios/
        content:
          sources:
          - url: .
            branches: HEAD
            start_paths:
              - docs
        ui:
          bundle:
            url: ./ui-bundle.zip
            snapshot: false
        asciidoc:
          extensions:
            - '@asciidoctor/tabs'
          attributes:
            platform: ios
            platform-ios: ''
        output:
          dir: docs/build/site/ctmobile/ios
        EOF
        
        # Android версия
        cat > docs/antora-playbook-android.yml <<EOF
        site:
          title: CT Software Help Portal - Android
          url: ${{ steps.deployment.outputs.page_url }}ctmobile/android/
        content:
          sources:
          - url: .
            branches: HEAD
            start_paths:
              - docs
        ui:
          bundle:
            url: ./ui-bundle.zip
            snapshot: false
        asciidoc:
          extensions:
            - '@asciidoctor/tabs'
          attributes:
            platform: android
            platform-android: ''
        output:
          dir: docs/build/site/ctmobile/android
        EOF
        
        # Windows версия
        cat > docs/antora-playbook-windows.yml <<EOF
        site:
          title: CT Software Help Portal - Windows
          url: ${{ steps.deployment.outputs.page_url }}ctmobile/windows/
        content:
          sources:
          - url: .
            branches: HEAD
            start_paths:
              - docs
        ui:
          bundle:
            url: ./ui-bundle.zip
            snapshot: false
        asciidoc:
          extensions:
            - '@asciidoctor/tabs'
          attributes:
            platform: windows
            platform-windows: ''
        output:
          dir: docs/build/site/ctmobile/windows
        EOF
    
    # Генерация сайтов для разных платформ
    - name: Generate Platform-Specific Sites
      run: |
        npx antora --stacktrace docs/antora-playbook-ios.yml
        npx antora --stacktrace docs/antora-playbook-android.yml
        npx antora --stacktrace docs/antora-playbook-windows.yml
    
    # Создание страницы-переключателя платформ
    - name: Create Platform Selector Page
      run: |
        mkdir -p docs/build/site/ctmobile
        cat > docs/build/site/ctmobile/index.html <<EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <meta http-equiv="refresh" content="0; url=./ios/ctmobile/index.html">
          <title>CT Mobile Documentation</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
              line-height: 1.6;
              color: #333;
              max-width: 800px;
              margin: 0 auto;
              padding: 20px;
            }
            h1 {
              color: #0366d6;
              border-bottom: 1px solid #eaecef;
              padding-bottom: 0.3em;
            }
            .platform-selector {
              margin: 2em 0;
              display: flex;
              gap: 10px;
            }
            .platform-btn {
              display: inline-block;
              padding: 10px 20px;
              background-color: #0366d6;
              color: white;
              text-decoration: none;
              border-radius: 4px;
              font-weight: 500;
            }
            .platform-btn:hover {
              background-color: #0056b3;
            }
          </style>
        </head>
        <body>
          <h1>CT Mobile Documentation</h1>
          <p>Please select your platform:</p>
          <div class="platform-selector">
            <a href="./ios/ctmobile/index.html" class="platform-btn">iOS</a>
            <a href="./android/ctmobile/index.html" class="platform-btn">Android</a>
            <a href="./windows/ctmobile/index.html" class="platform-btn">Windows</a>
          </div>
          <p>You will be automatically redirected to iOS documentation in a few seconds...</p>
        </body>
        </html>
        EOF
        
        # Добавляем ссылку на CT Mobile на основной странице
        if [ -f docs/build/site/index.html ]; then
          sed -i '/<\/body>/i <script>\
          document.addEventListener("DOMContentLoaded", function() {\
            const nav = document.querySelector(".nav-menu");\
            if(nav) {\
              const ctmobileLink = document.createElement("a");\
              ctmobileLink.href = "./ctmobile/";\
              ctmobileLink.className = "nav-link";\
              ctmobileLink.textContent = "CT Mobile";\
              const navItem = document.createElement("li");\
              navItem.className = "nav-item";\
              navItem.appendChild(ctmobileLink);\
              nav.appendChild(navItem);\
            }\
          });\
          </script>' docs/build/site/index.html
        fi
        
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
          path: docs/build/site    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
