name: Build and Deploy to GitHub Pages and Firebase
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Antora, AsciiDoctor and Tabs
        run: npm i antora @antora/lunr-extension @asciidoctor/tabs asciidoctor@~2.2.8
      - name: Debug Installed Packages
        run: npm list
      - name: Generate Site
        run: npx antora --stacktrace docs/antora-playbook.yml
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      #- name: Deploy to Firebase Hosting
      #  uses: FirebaseExtended/action-hosting-deploy@v0
      #  with:
      #    repoToken: ${{ secrets.GITHUB_TOKEN }}
      #    firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CT_HELP }}
      #    channelId: live
      #    projectId: ct-help
