name: Publish Documentation
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Antora
        run: npm i antora @asciidoctor/tabs

      # Проверяем текущую структуру
      - name: Check Current Structure
        run: |
          echo "Current repository structure:"
          find docs -type f -name "antora*.yml" -exec echo {} \; -exec cat {} \;
          
          if [ -d "docs/modules/ctmobile" ]; then
            echo "Content of ctmobile module:"
            find docs/modules/ctmobile -type f | sort
          
            if [ -f "docs/modules/ctmobile/antora.yml" ]; then
              echo "Current antora.yml content:"
              cat docs/modules/ctmobile/antora.yml
            fi
          fi

      # Генерируем все версии с разными версиями модуля
      - name: Generate Documentation
        run: |
          # Сохраняем оригинальный antora.yml
          if [ -f "docs/modules/ctmobile/antora.yml" ]; then
            cp docs/modules/ctmobile/antora.yml docs/modules/ctmobile/antora.yml.orig
          else
            echo "WARNING: ctmobile/antora.yml not found!"
            mkdir -p docs/modules/ctmobile
            echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
            echo "title: CT Mobile" >> docs/modules/ctmobile/antora.yml
            echo "version: '1.0'" >> docs/modules/ctmobile/antora.yml
          fi
          
          # iOS версия
          echo "Generating iOS version..."
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for iOS" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-ios'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          cat docs/modules/ctmobile/antora.yml
          
          # Временно модифицируем основной плейбук для iOS
          sed -i '/asciidoc:/,/^[a-z]/ s/^  attributes:/  attributes:\n    platform-ios: ""/' docs/antora-playbook.yml
          
          # Генерируем документацию для iOS
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Android версия
          echo "Generating Android version..."
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for Android" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-android'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          cat docs/modules/ctmobile/antora.yml
          
          # Временно модифицируем основной плейбук для Android
          cp docs/antora-playbook.yml docs/antora-playbook.yml.ios
          sed -i '/asciidoc:/,/^[a-z]/ s/platform-ios: ""/platform-android: ""/' docs/antora-playbook.yml
          
          # Генерируем документацию для Android
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Windows версия
          echo "Generating Windows version..."
          echo "name: ctmobile" > docs/modules/ctmobile/antora.yml
          echo "title: CT Mobile for Windows" >> docs/modules/ctmobile/antora.yml
          echo "version: '1.0-windows'" >> docs/modules/ctmobile/antora.yml
          echo "nav:" >> docs/modules/ctmobile/antora.yml
          echo "- modules/ROOT/nav.adoc" >> docs/modules/ctmobile/antora.yml
          
          cat docs/modules/ctmobile/antora.yml
          
          # Временно модифицируем основной плейбук для Windows
          cp docs/antora-playbook.yml docs/antora-playbook.yml.android
          sed -i '/asciidoc:/,/^[a-z]/ s/platform-android: ""/platform-windows: ""/' docs/antora-playbook.yml
          
          # Генерируем документацию для Windows
          npx antora --stacktrace docs/antora-playbook.yml
          
          # Восстанавливаем оригинальные файлы
          if [ -f "docs/modules/ctmobile/antora.yml.orig" ]; then
            mv docs/modules/ctmobile/antora.yml.orig docs/modules/ctmobile/antora.yml
          fi
          if [ -f "docs/antora-playbook.yml.ios" ]; then
            mv docs/antora-playbook.yml.ios docs/antora-playbook.yml
          fi
          
          # Проверяем сгенерированные файлы
          echo "Generated files:"
          find docs/build/site -type d | grep -E "ctmobile/(1\.0|1\.0-ios|1\.0-android|1\.0-windows)" || echo "No ctmobile versions found!"

      # Публикация на GitHub Pages
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4