= Offline Objects

[NOTE] ==== Not available. ====

The *Offline Objects* record type is intended to store settings for an
offline object as well as permissions and available actions with records
of the offline object for a specific profile.

[TIP] ==== To create or update the settings of offline objects,
go to xref:android/knowledge-base/configuration-guide/ct-mobile-control-panel/index.adoc-offline-objects[CT Mobile
Control Panel: Offline Objects]. ====

'''''

Record Type API name:[.apiobject]#OfflineObjects#

'''''

[width="100%",cols="25%,25%,25%,25%",]
|===
|*Field* |*API Name* |*Type* |*Description*

|Conflict Manager
|[.apiobject]#clm__IsConflictManagerEnabled__c#
|Checkbox |Allows the
https://help.customertimes.com/smart/project-ct-mobile-en/conflict-manager-control[Conflict
Manager] functionality for records of the offline object. It is used to
track the changes made in a single record in the mobile application and
on the Salesforce side.

|Creating Allowed
|[.apiobject]#clm__IsCreatingAllowed__c# |Checkbox a|
Enables the creation of records of the offline object.

[NOTE] ==== The permission to create a record cannot overcome
the same profile permission. ====

|Criteria |[.apiobject]#clm__Criteria__c# |Long Text
Area(32768) a|
Stores a SOQL query to filter records of the offline object to download
in the mobile application.

[NOTE] ==== The criteria line should start with the
[.apiobject]#'WHERE' ==== keyword. #

|Deleting Allowed
|[.apiobject]#clm__IsDeletingAllowed__c# |Checkbox a|
Enables the deletion of records of the offline object.

[NOTE] ==== The permission to delete a record cannot overcome
the same profile permission. ====[NOTE] ==== The records which
have not been synchronized may always be deleted no matter what access
the profile is granted. ====

|External Id |[.apiobject]#clm__ExternalId__c#
|Text(255) |Contains the ID of the corresponding record of custom
settings.

|Object |[.apiobject]#clm__Object__c# |Text(255) |Stores
an API Name of xref:android/quick-reference-guides/managing-offline-objects.adoc[an offline object].

|Online Fetching
|[.apiobject]#clm__IsOnlineFetchingEnabled__c# |Checkbox
|Defines if the
https://help.customertimes.com/smart/project-ct-mobile-en/online-records-fetching[Load
more records] button is available in the application, in case some
records of the offline object were not downloaded due to the criteria
specified in the[.apiobject]#clm__Criteria__c# field.

|Order |[.apiobject]#clm__Order__c# |Number(18,0)
|Defines a sequence of offline objects' records to download.

|Org ID/Profile ID |[.apiobject]#clm__OrgProfileId__c#
|Text(255) |Stores a profile's ID. Left blank or specify an Organization
ID to apply for all non-configured profiles.

|Quick Sync |[.apiobject]#clm__IsQuickSyncEnabled__c#
|Checkbox |Allows xref:android/synchronization-launch[Quick Record
Synchronization] for records of the offline object.

|Sync Recovery |[.apiobject]#clm__SyncRecovery__c#
|Picklist a|
Enables
https://help.customertimes.com/smart/project-ct-mobile-en/sync-recovery[Sync
Recovery] to deliver records that could not be synchronized to
Salesforce anyway. If the parameter is filled with a specific value, it
enables the work of Apex web service and passes the data to Salesforce
through it.

* An empty value means that the web service is not involved.
* *Direct access* means the pushing of the record changes directly to an
object via the additional web service.
* *Proxy object* means the pushing of the record changes as a modifiable
JSON file in the xref:android/sync-log[Sync Log] object attachments.

|===
